/* Copyright 2026 Rhett Creighton - Apache License 2.0
 * purpose: The ZVCS snapshot exclusion policy (vcs_path_ignored), dependency-free so namespace-evidence readers share it. */

#include "vcs/vcs_manifest.h"

#include <string.h>

/* Return the final path component of relpath. */
static const char *base_of(const char *relpath)
{
    const char *slash = strrchr(relpath, '/');
    return slash ? slash + 1 : relpath;
}

/* Does relpath (or any ancestor component) equal one of the ignored dir
 * names, or start with an ignored dir prefix? */
static bool has_dir_component(const char *relpath, const char *comp)
{
    size_t clen = strlen(comp);
    const char *p = relpath;
    while (*p) {
        /* p points at the start of a component. */
        if (strncmp(p, comp, clen) == 0 && (p[clen] == '/' || p[clen] == '\0'))
            return true;
        const char *slash = strchr(p, '/');
        if (!slash)
            break;
        p = slash + 1;
    }
    return false;
}

/* Root-relative directory match. Unlike has_dir_component(), this does not
 * hide a same-named directory nested inside tracked source. */
static bool has_root_prefix(const char *relpath, const char *prefix)
{
    size_t len = strlen(prefix);
    return strncmp(relpath, prefix, len) == 0 &&
           (relpath[len] == '/' || relpath[len] == '\0');
}

/* Directory components and checkout-root prefixes that never enter a
 * snapshot. */
static bool ignored_dir(const char *relpath)
{
    /* dir prefixes / components */
    if (has_dir_component(relpath, ".git") ||
        has_dir_component(relpath, ".zvcs") ||
        has_dir_component(relpath, "build"))
        return true;
    /* Checkout-local agent worktrees and generated caches can contain many
     * complete repository copies. Walking them made the first dev-loop
     * provenance snapshot recursively index ~150k files and stall a hot swap
     * for minutes. Keep tracked .claude commands/skills; prune only runtime
     * subtrees. These paths mirror the repository's generated-file policy. */
    static const char *const ignored_roots[] = {
        ".cache",
        ".claude/tmp",
        ".claude/worktrees",
        ".codeindex",
        ".zcl_test_render",
        "chaos-output",
        "examples/bin",
        "obj",
        "bin",
        "vendor/.build",
        "vendor/.cache",
        "vendor/lib",
        "vendor/tor",
        "vendor/zclassic-ref",
        "zcode",
        NULL,
    };
    for (size_t i = 0; ignored_roots[i]; i++)
        if (has_root_prefix(relpath, ignored_roots[i]))
            return true;
    return false;
}

/* make vendor materializes these from the already-carried, pinned
 * archives in vendor/.cache.  They are build outputs (and are ignored by
 * Git), not independent source inputs.  Capturing them made a sovereign
 * carrier contain both an archive and its expanded/generated bytes,
 * needlessly exhausting the shared content.v2 package bound. */
static bool ignored_vendor_output(const char *relpath)
{
    return strcmp(relpath, "vendor/sqlite3.c") == 0 ||
           strcmp(relpath, "vendor/include/zlib.h") == 0 ||
           strcmp(relpath, "vendor/include/zconf.h") == 0 ||
           has_root_prefix(relpath, "vendor/include/openssl");
}

static bool has_suffix(const char *b, size_t blen, const char *suffix)
{
    size_t n = strlen(suffix);
    return blen >= n && strcmp(b + blen - n, suffix) == 0;
}

/* Runtime state by basename: databases, logs, test scratch, locks. */
static bool ignored_runtime_file(const char *relpath)
{
    const char *b = base_of(relpath);
    size_t blen = strlen(b);
    /* *.db, *.db-wal, *.db-shm, *.log */
    if (has_suffix(b, blen, ".db") || has_suffix(b, blen, ".db-wal") ||
        has_suffix(b, blen, ".db-shm") || has_suffix(b, blen, ".log"))
        return true;
    /* node.db* (covers node.db, node.db-wal, node.db-shm) and test-tmp* */
    if (strncmp(b, "node.db", 7) == 0 || strncmp(b, "test-tmp", 8) == 0)
        return true;
    return strcmp(relpath, ".claude/scheduled_tasks.lock") == 0 ||
           strcmp(b, "compile_commands.json") == 0 ||
           strcmp(b, ".core-unseal-token") == 0;
}

bool vcs_path_ignored(const char *relpath)
{
    if (!relpath || !relpath[0])
        return true;
    return ignored_dir(relpath) || ignored_vendor_output(relpath) ||
           ignored_runtime_file(relpath);
}
