#!/usr/bin/env bash
# Copyright 2026 Rhett Creighton. Licensed under Apache-2.0.
# Offline public fixtures only; no original node/wallet is executed.
set -euo pipefail
reference=${1:?Usage: project-original-legacy-sources.sh <original-checkout> <new-output-directory>}
report=${2:?A new output directory is required}
commit=14a83d510ffd109d3fa09bf74ebf8c28854a263f
git -C "$reference" cat-file -e "$commit:src/test/data/tx_valid.json"
mkdir -- "$report"
for name in sighash tx_valid; do
 git -C "$reference" show "$commit:src/test/data/$name.json" > "$report/$name.json"
done
(cd "$report" && printf '%s\n' \
 '6e10f3e5649c876a8968a3ba13885aeb8dcee8040fd89e7e39651b041d07f30c  sighash.json' \
 '557d39924c814671855c38f4ef33e41ebd988460b1ff52e9cc6b9ecc9b1514a3  tx_valid.json' | sha256sum -c -)
awk -F '"' -v out="$report" '
function byte(n,a,b) {
 if(n<0 || n*2+2>length(s))exit 1;
 a=index("0123456789abcdef",substr(s,2*n+1,1))-1;
 b=index("0123456789abcdef",substr(s,2*n+2,1))-1;
 if(a<0 || b<0)exit 1;return a*16+b;
}
function count(n) {n=byte(p++);if(n>252)exit 1;return n;}
function prefix(start,n,i) {
 p=start;ins=count();for(i=0;i<ins;i++){p+=36;n=count();p+=n+4;}
 outs=count();for(i=0;i<outs;i++){p+=8;n=count();if(n>25)exit 1;p+=n;}
 lock=p;p+=4;
}
FILENAME ~ /tx_valid.json$/ && FNR==11 {
 s=$2;if(substr(s,1,8)!="01000000" || length(s)!=450)exit 1;
 prefix(4);if(p*2!=length(s))exit 1;
 print s > (out "/original-v1-11.hex");
 print "original-v1-11",ins,outs,0,lock,0,1 > (out "/layout.txt");seen++;
}
FILENAME ~ /sighash.json$/ && (FNR==8 || FNR==10 || FNR==12) {
 s=$2;if(substr(s,1,16)!="030000807082c403" || length(s)>8000 || length(s)%2)exit 1;
 prefix(8);p+=4;joins=count();joinstart=p;
 p+=1802*joins;if(joins)p+=96;if(p*2!=length(s))exit 1;
 name="original-v3-" FNR;print s > (out "/" name ".hex");
 print name,ins,outs,joins,lock,joinstart,3 > (out "/layout.txt");seen++;
 # Explicit projection: version2; remove version-group and expiry bytes only.
 # PHGR descriptions/signatures are unchanged. Not untouched original v2 wire.
 name="projected-v2-" FNR;
 projected="02000000" substr(s,17,(lock+4-8)*2) substr(s,(lock+8)*2+1);
 if(length(projected)!=length(s)-16)exit 1;
 print projected > (out "/" name ".hex");
 print name,ins,outs,joins,lock-4,joinstart-8,2 > (out "/layout.txt");seen++;
}
END{if(seen!=7)exit 1;}
' "$report/tx_valid.json" "$report/sighash.json"
for path in "$report"/*.hex; do
 stem=${path%.hex}
 xxd -r -p "$path" > "$stem.bin"
 openssl dgst -sha256 -binary "$stem.bin" | openssl dgst -sha256 -binary |
 od -An -v -tx1 | awk '{for(i=1;i<=NF;i++)a[++n]=$i}END{if(n!=32)exit 1;for(i=n;i>0;i--)printf "%s",a[i];print ""}' > "$stem.txid"
done
{
 printf '%s\n' '/* Public original Zclassic 14a83d510ffd109d3fa09bf74ebf8c28854a263f fixtures.' \
  ' * Original MIT notice: ../../docs/transaction-reference.LICENSE.' \
  ' * v1/v3 are untouched; v2 is explicitly projected from v3.' \
  ' * Generated by tools/project-original-legacy-sources.sh; SHA256d via OpenSSL. */' \
  'static const struct { size_t length, inputs, outputs, joins, lock_offset, join_offset;' \
  '    uint32_t version; uint8_t id[32], wire[4000]; } legacy_vectors[] = {'
 while read -r name inputs outputs joins lock joinstart version; do
  length=$(wc -c < "$report/$name.bin")
  printf '    {%s,%s,%s,%s,%s,%s,%s, {' "$length" "$inputs" "$outputs" "$joins" "$lock" "$joinstart" "$version"
  awk '{for(i=1;i<=length($0);i+=2)printf "0x%s,",substr($0,i,2)}' "$report/$name.txid"
  printf '}, {\n'
  od -An -v -tx1 "$report/$name.bin" | awk '{printf "        ";for(i=1;i<=NF;i++)printf "0x%s,",$i;print ""}'
  printf '    }},\n'
 done < "$report/layout.txt"
 printf '};\n'
} > "$report/legacy_source_vectors.h"
(cd "$report" && sha256sum original-* projected-* layout.txt legacy_source_vectors.h > SHA256SUMS)
printf 'Four untouched v1/v3 and three projected v2 fixtures with independent IDs recorded.\n'
