#!/usr/bin/env bash
# Copyright 2026 Rhett Creighton. Licensed under Apache-2.0.
# Offline projection of pinned public source objects; never runs a node/wallet.
set -euo pipefail
ulimit -t 10
umask 077
reference=${1:?Usage: project-original-context.sh <original-checkout> <new-output-directory>}
report=${2:?A new output directory is required}
commit=14a83d510ffd109d3fa09bf74ebf8c28854a263f
mkdir -- "$report"
git -C "$reference" show "$commit:src/chainparams.cpp" >"$report/chainparams.cpp"
git -C "$reference" show "$commit:src/consensus/upgrades.cpp" >"$report/upgrades.cpp"
git -C "$reference" show "$commit:src/consensus/params.h" >"$report/params.h"
git -C "$reference" show "$commit:src/main.cpp" >"$report/main.cpp"
cat >"$report/original.sha256" <<'EOF'
47acda5340e350a2a1b70e7ee8b4bc55c76dd3f09609e28274f069e69765a1ff  chainparams.cpp
fb66803b30f52362947409fff4f03b0c203775fd7ee9d8a0820515942ca12d51  upgrades.cpp
7f400fc468b3808a259d9b7cc763e6f54ef720de98c124dcea1308d9ae6dc239  params.h
3013da897d89a799331e1e97267256cfd388cf1b60afb7bcb9b1759fbee8fb69  main.cpp
EOF
(cd "$report"; sha256sum -c original.sha256)
printf '%s\n' "$commit" >"$report/original-commit.txt"
awk '
/enum UpgradeIndex/ { inside=1; next }
inside && /^[[:space:]]*(BASE_SPROUT|UPGRADE_[A-Z]+),/ {
    gsub(/[[:space:],]/, ""); print; ++seen;
}
inside && /MAX_NETWORK_UPGRADES/ { exit }
END { if (seen!=7) exit 1 }
' "$report/params.h" >"$report/epochs.txt"
awk '
/nBranchId =/ {
    sub(/^.*=\*\/[[:space:]]*/, ""); sub(/,.*/, "");
    if ($0!="0" && $0!~/^0x[0-9a-f]+$/) exit 1;
    print; ++seen;
}
END { if (seen!=7) exit 1 }
' "$report/upgrades.cpp" >"$report/branches.txt"
cat >"$report/chain_context_reference.h" <<'EOF'
/* Generated by tools/project-original-context.sh; do not hand-edit.
 * Zclassic 14a83d510ffd109d3fa09bf74ebf8c28854a263f consensus parameter data.
 * Copyright (c) 2018 The Zcash developers; MIT license, see
 * ../../docs/transaction-reference.LICENSE. No wallet implementation imported.
 */
#ifndef ZCL_CHAIN_CONTEXT_REFERENCE_H
#define ZCL_CHAIN_CONTEXT_REFERENCE_H
#include <stdint.h>
static const struct { int32_t activation[2]; uint32_t branch; } reference_epochs[] = {
EOF
awk '
BEGIN { network=-1 }
FILENAME==ARGV[1] { order[++epochs]=$0; next }
FILENAME==ARGV[2] { branches[++ids]=$0; next }
/^class CMainParams / { network=0 }
/^class CTestNetParams / { network=1 }
/^class CRegTestParams / { network=-1 }
network>=0 && /consensus.vUpgrades\[Consensus::[A-Z_]+\].nActivationHeight =/ {
    split($0,a,"\\[Consensus::"); split(a[2],b,"\\]"); epoch=b[1];
    sub(/^.*nActivationHeight =[[:space:]]*/, "");
    if ($0=="") { if (getline!=1) exit 1; sub(/^[[:space:]]*/, ""); }
    if ($0=="Consensus::NetworkUpgrade::ALWAYS_ACTIVE;") $0="0;";
    if ($0=="Consensus::NetworkUpgrade::NO_ACTIVATION_HEIGHT;") $0="-1;";
    if ($0!~/^(-1|[0-9]+);$/ || ((network SUBSEP epoch) in heights)) exit 1;
    sub(/;$/, ""); heights[network,epoch]=$0; ++seen;
}
END {
    if (epochs!=7 || ids!=7 || seen!=14) exit 1;
    for (i=1;i<=epochs;i++) {
        name=order[i];
        if (!((0 SUBSEP name) in heights) || !((1 SUBSEP name) in heights)) exit 1;
        printf "    {{%s, %s}, UINT32_C(%s)}, /* %s */\n", heights[0,name],heights[1,name],branches[i],name;
        if (name=="UPGRADE_SAPLING") sapling=i-1;
    }
    if (sapling!=3) exit 1;
    print "};";
    printf "enum { ZCL_REFERENCE_SAPLING_EPOCH = %d };\n",sapling;
    print "#endif";
}
' "$report/epochs.txt" "$report/branches.txt" "$report/chainparams.cpp" >>"$report/chain_context_reference.h"
(cd "$report"; sha256sum chain_context_reference.h >chain-context-reference.sha256)
printf '%s\n' 'Projected both pinned network schedules and all epoch branch IDs; no current-chain authentication claimed.'
