#!/usr/bin/env bash
# Copyright 2026 Rhett Creighton. Licensed under Apache-2.0.
# Public fixture extraction only; never executes a reference node or wallet.
set -euo pipefail
reference=${1:?Usage: project-original-sources.sh <pinned-sighash.json> <new-output-directory>}
report=${2:?A new output directory is required}
expected=6e10f3e5649c876a8968a3ba13885aeb8dcee8040fd89e7e39651b041d07f30c
actual=$(sha256sum "$reference" | cut -d ' ' -f1)
test "$actual" = "$expected"
mkdir -- "$report"
awk -F '"' -v out="$report" '
function byte(n,a,b) {
    if(n<0 || 2*n+2>length(s))exit 1;
    a=index("0123456789abcdef",substr(s,2*n+1,1))-1;
    b=index("0123456789abcdef",substr(s,2*n+2,1))-1;
    if(a<0 || b<0)exit 1; return 16*a+b;
}
function count(max,n) {n=byte(p++);if(n>max)exit 1;return n;}
NR==153 || NR==203 || NR==208 || NR==296 {
    s=$2;if(substr(s,1,16)!="0400008085202f89" || length(s)>22000 || length(s)%2)exit 1;
    p=8;ins=count(8);for(i=0;i<ins;i++){p+=36;n=count(128);p+=n+4;}
    outs=count(16);for(i=0;i<outs;i++){p+=8;n=count(25);p+=n;}
    p+=8;prefix=p;p+=8;
    spends=count(4);p+=384*spends;shielded=count(4);p+=948*shielded;
    joins=count(3);p+=1698*joins;if(joins)p+=96;if(spends || shielded)p+=64;
    if(p*2!=length(s))exit 1;
    print s > (out "/original-" NR ".hex");
    print NR,ins,outs,prefix,spends,shielded,joins > (out "/layout.txt");seen++;
}
END{if(seen!=4)exit 1;}
' "$reference"
for row in 153 203 208 296; do
    xxd -r -p "$report/original-$row.hex" > "$report/original-$row.bin"
    openssl dgst -sha256 -binary "$report/original-$row.bin" | openssl dgst -sha256 -binary |
        od -An -v -tx1 | awk '{for(i=1;i<=NF;i++)a[++n]=$i}END{if(n!=32)exit 1;for(i=n;i>0;i--)printf "%s",a[i];print ""}' > "$report/original-$row.txid"
done
{
    printf '%s\n' '/* Public untouched Zclassic 14a83d510ffd109d3fa09bf74ebf8c28854a263f vectors.' ' * Original MIT notice: ../../docs/transaction-reference.LICENSE.' ' * Generated by tools/project-original-sources.sh; SHA256d uses OpenSSL. */'
    printf '%s\n' 'static const struct { size_t length, inputs, outputs, prefix, spends, shielded, joins;' '    uint8_t id[32], wire[11000]; } source_vectors[] = {'
    while read -r row inputs outputs prefix spends shielded joins; do
        length=$(wc -c < "$report/original-$row.bin")
        printf '    {%s,%s,%s,%s,%s,%s,%s, {' "$length" "$inputs" "$outputs" "$prefix" "$spends" "$shielded" "$joins"
        awk '{for(i=1;i<=length($0);i+=2)printf "0x%s,",substr($0,i,2)}' "$report/original-$row.txid"
        printf '}, {\n'
        od -An -v -tx1 "$report/original-$row.bin" | awk '{printf "        ";for(i=1;i<=NF;i++)printf "0x%s,",$i;print ""}'
        printf '    }},\n'
    done < "$report/layout.txt"
    printf '};\n'
} > "$report/source_vectors.h"
(cd "$report" && sha256sum original-* layout.txt source_vectors.h > SHA256SUMS)
printf 'Four full v4 wire fixtures and independent identities extracted.\n'
