/* Copyright 2026 Rhett Creighton - Apache License 2.0
 * purpose: Live cases of the semantic sensor's warm session: warm equals the cold oracle across edits, and a forced mismatch never writes warm bytes.
 *
 * ACCEPTANCE BAR for `z23-clang-manifest session` (tools/sensors/
 * clang_manifest_session.c; contract in docs/work/SEMANTIC_MANIFEST.md,
 * "Warm session"). One session process serves every emit of a case while
 * the test edits the fixture tree between requests. After every request the
 * manifest the session wrote must be byte-identical to a separate cold
 * `emit` process over the same tree and argv, and the session must report
 * the TU reuse the contract requires:
 *   - a function-body edit and a main-file macro edit reparse the live TU;
 *   - a header macro edit, a header layout edit, a header that newly shadows
 *     the one used, a header that newly shadows one a system header
 *     includes (no LOOKUPS record covers that include) and a flag change
 *     each recreate it;
 *   - with ZCL_CLANG_MANIFEST_INJECT_WARM_MISMATCH=1 the warm bytes are
 *     corrupted, the oracle reports the mismatch, the cold bytes are written
 *     and warm reuse stays off for that TU while it holds its slot;
 *   - the attribute call refs (cleanup(f)) and alias address refs (alias,
 *     asm label, including one declared in a preamble header) of a reparse
 *     equal a cold parse's, verified and qualified;
 *   - a conditional lookup the text scan cannot replay (a macro operand
 *     that is no string literal, the GNU spellings, __has_embed, #embed,
 *     one a line continuation runs through) recreates and verifies its TU
 *     on every emit, even while the header it asks about appears and goes;
 *     a literal or string-literal-macro __has_include, a __has_include_next
 *     and a probe word in a comment or a string stay warm;
 *   - a reparse whose own manifest has a shadow candidate the TU's baseline
 *     lacks (a header only that reparse read), or a lookup with no negative
 *     claim (a computed include below the preamble), is retried as a fresh
 *     parse;
 *   - an argv holding a response file (@file) or -fmodules recreates the TU
 *     on every emit, argv unchanged or not;
 *   - the stdin protocol refuses a request line with a NUL byte, one that is
 *     not UTF-8 and one past the line bound, each whole, and goes on; a
 *     UTF-8 path comes back as JSON code-point escapes; --max-tus takes
 *     digits only;
 *   - every reply names its trust: "verified" for a first emit the oracle
 *     checked, "qualified" for warm bytes written unverified, "cold" for
 *     cold bytes no warm parse matched.
 *
 * Do not edit this file to make the implementation pass. */
#if !defined(_WIN32) && !defined(_DEFAULT_SOURCE)
#define _DEFAULT_SOURCE
#endif

#include "test/semantic_sensor_session.h"

#include "base/hex.h"
#include "sha3/sha3.h"
#include "test/test_core.h"
#include "util/spawn.h"
#include "vcs/semantic_manifest.h"

#include <fcntl.h>
#include <poll.h>
#include <signal.h>
#include <sys/wait.h>

#define SSS_SENSOR "build/bin/z23-clang-manifest"
#define SSS_INJECT "ZCL_CLANG_MANIFEST_INJECT_WARM_MISMATCH"
#define SSS_REPLY_MAX 4096

extern char **environ;

static const char k_sss_header[] =
    "#ifndef FX_H\n"
    "#define FX_H\n"
    "#define FX_SCALE 3\n"
    "struct fx_pair { int a; int b; };\n"
    "int fx_sum(const struct fx_pair *p);\n"
    "#endif\n";

static const char k_sss_main[] =
    "#include \"fx.h\"\n"
    "#include <stdint.h>\n"
    "#define FX_LOCAL 2\n"
    "int fx_sum(const struct fx_pair *p) { return p->a + p->b; }\n"
    "int fx_run(int v)\n"
    "{\n"
    "    struct fx_pair p = {v, FX_SCALE + FX_LOCAL};\n"
    "    return fx_sum(&p) * 2;\n"
    "}\n";

/* ── the fixture tree ─────────────────────────────────────────────────── */

static bool sss_write(const char *root, const char *rel, const char *body)
{
    char path[PATH_MAX];
    FILE *fp;
    bool ok;
    for (const char *s = strchr(rel, '/'); s != NULL; s = strchr(s + 1, '/')) {
        (void)snprintf(path, sizeof(path), "%s/%.*s", root, (int)(s - rel), rel);
        if (mkdir(path, 0700) != 0 && errno != EEXIST)
            return false;
    }
    (void)snprintf(path, sizeof(path), "%s/%s", root, rel);
    fp = fopen(path, "wb");
    if (fp == NULL)
        return false;
    ok = fputs(body, fp) >= 0;
    return fclose(fp) == 0 && ok;
}

static bool sss_read(const char *path, char **out, size_t *len)
{
    FILE *fp = fopen(path, "rb");
    long size;
    bool ok = false;
    *out = NULL;
    if (fp == NULL)
        return false;
    if (fseek(fp, 0, SEEK_END) == 0 && (size = ftell(fp)) >= 0 &&
        fseek(fp, 0, SEEK_SET) == 0) {
        *out = malloc((size_t)size + 1);
        ok = *out != NULL && fread(*out, 1, (size_t)size, fp) == (size_t)size;
        *len = (size_t)size;
    }
    (void)fclose(fp);
    if (ok)
        (*out)[*len] = '\0';
    return ok;
}

/* Replace the first `from` in root/rel with `to`. */
static bool sss_edit(const char *root, const char *rel, const char *from,
                     const char *to)
{
    char path[PATH_MAX], next[8192];
    char *body = NULL, *hit;
    size_t n = 0;
    bool ok = false;
    (void)snprintf(path, sizeof(path), "%s/%s", root, rel);
    if (!sss_read(path, &body, &n))
        return false;
    hit = strstr(body, from);
    if (hit != NULL && n + strlen(to) < sizeof(next)) {
        (void)snprintf(next, sizeof(next), "%.*s%s%s", (int)(hit - body), body,
                       to, hit + strlen(from));
        ok = sss_write(root, rel, next);
    }
    free(body);
    return ok;
}

static bool sss_tree(const char *root)
{
    char dir[PATH_MAX];
    (void)snprintf(dir, sizeof(dir), "%s/inc", root);
    if (mkdir(dir, 0700) != 0 && errno != EEXIST)
        return false;
    (void)snprintf(dir, sizeof(dir), "%s/inc/a", root);
    if (mkdir(dir, 0700) != 0 && errno != EEXIST)
        return false;
    return sss_write(root, "inc/b/fx.h", k_sss_header) &&
           sss_write(root, "src/main.c", k_sss_main);
}

/* ── the edits, in session order ─────────────────────────────────────────── */

static bool sss_none(const char *root)
{
    (void)root;
    return true;
}

static bool sss_body(const char *root)
{
    return sss_edit(root, "src/main.c", "p->a + p->b", "p->a - p->b");
}

/* A #define right after the includes lies inside the preamble region, so
 * the front end rebuilds the preamble inside the reparse. */
static bool sss_main_macro(const char *root)
{
    return sss_edit(root, "src/main.c", "FX_LOCAL 2", "FX_LOCAL 7");
}

static bool sss_header_macro(const char *root)
{
    return sss_edit(root, "inc/b/fx.h", "FX_SCALE 3", "FX_SCALE 4");
}

/* The same length and, restored after the write, the same modification
 * time: the front end's own preamble check (size and mtime) cannot see this
 * edit; only the session's content digests can. */
static bool sss_header_same_stat(const char *root)
{
    char path[PATH_MAX];
    struct stat before;
    struct timespec times[2];
    (void)snprintf(path, sizeof(path), "%s/inc/b/fx.h", root);
    if (stat(path, &before) != 0 ||
        !sss_edit(root, "inc/b/fx.h", "FX_SCALE 4", "FX_SCALE 5"))
        return false;
    times[0] = before.st_atim;
    times[1] = before.st_mtim;
    return utimensat(AT_FDCWD, path, times, 0) == 0;
}

static bool sss_layout(const char *root)
{
    return sss_edit(root, "inc/b/fx.h", "int b; };", "int b; long c; };");
}

/* inc/a is searched before inc/b: the new file shadows the one in use. The
 * shadow candidates see it before the reparse. */
static bool sss_shadow(const char *root)
{
    return sss_write(root, "inc/a/fx.h",
                     "#ifndef FX_H\n#define FX_H\n#define FX_SCALE 9\n"
                     "struct fx_pair { long a; int b; };\n"
                     "int fx_sum(const struct fx_pair *p);\n#endif\n");
}

/* The includer's own directory is searched first for a quoted include and is
 * no search dir: only the fresh probes of the LOOKUPS record see this one,
 * after the reparse, which is then retried as a fresh parse. */
static bool sss_shadow_beside(const char *root)
{
    return sss_write(root, "src/fx.h",
                     "#ifndef FX_H\n#define FX_H\n#define FX_SCALE 11\n"
                     "struct fx_pair { short a; int b; };\n"
                     "int fx_sum(const struct fx_pair *p);\n#endif\n");
}

/* A leaf system header that the base TU read only through another system
 * header: no LOOKUPS record covers its include. */
struct sss_leaf {
    char path[PATH_MAX];
    char *body;
};

/* The host path of a system file's manifest path: "@sys/x" is "/x". */
static bool sss_sys_path(const char *p, size_t n, char *out, size_t cap)
{
    int w;
    if (n < 5 || memcmp(p, "@sys/", 5) != 0)
        return false;
    w = snprintf(out, cap, "/%.*s", (int)(n - 5), p + 5);
    return w > 0 && (size_t)w < cap;
}

static bool sss_leaf_cb(void *ctx, const struct vcs_semantic_fields_v1 *f)
{
    struct sss_leaf *l = ctx;
    size_t n = 0;
    if (l->body != NULL || f->ntext < 1 || f->nnum < 1 ||
        f->num[0] != VCS_SEMANTIC_ORIGIN_V1_SYSTEM ||
        !sss_sys_path(f->text[0], f->text_len[0], l->path, sizeof(l->path)) ||
        !sss_read(l->path, &l->body, &n))
        return true;
    if (n == 0 || strstr(l->body, "include") != NULL) {
        free(l->body);
        l->body = NULL;
    }
    return true;
}

/* A copy of that header in inc/a, the first angled dir, under every tail of
 * its path, so whichever relative name the system header spelled now finds
 * the copy first. A cold parse reads the copy; a reused preamble would not. */
static bool sss_system_shadow(const char *root)
{
    struct sss_leaf l = {0};
    char base[PATH_MAX], rel[PATH_MAX], *m = NULL;
    size_t n = 0;
    bool ok;
    (void)snprintf(base, sizeof(base), "%s/base.cold.bin", root);
    ok = sss_read(base, &m, &n) &&
         vcs_semantic_section_v1_each((const uint8_t *)m, n,
                                      VCS_SEMANTIC_SECTION_V1_FILES,
                                      sss_leaf_cb, &l) &&
         l.body != NULL;
    free(m);
    if (!ok)
        printf("FAIL no leaf system header in %s\n", base);
    for (const char *s = strchr(l.path + 1, '/'); ok && s != NULL;
         s = strchr(s + 1, '/')) {
        (void)snprintf(rel, sizeof(rel), "inc/a/%s", s + 1);
        ok = sss_write(root, rel, l.body);
    }
    free(l.body);
    return ok;
}

static bool sss_body_again(const char *root)
{
    return sss_edit(root, "src/main.c", "p->a - p->b", "p->a * p->b");
}

struct sss_step {
    const char *name;
    bool (*edit)(const char *root);
    bool extra_flag;  /* argv gains -DFX_EXTRA=1 from here on */
    const char *tu;   /* the TU reuse the session must report */
    const char *why;  /* a prefix of its reason ("" when none is required) */
};

static const struct sss_step k_sss_steps[] = {
    {"base", sss_none, false, "created", "first-parse"},
    {"body", sss_body, false, "reparsed", ""},
    {"main-macro", sss_main_macro, false, "reparsed", ""},
    {"header-macro", sss_header_macro, false, "recreated",
     "file-changed inc/b/fx.h"},
    {"header-same-stat", sss_header_same_stat, false, "recreated",
     "file-changed inc/b/fx.h"},
    {"header-layout",sss_layout, false, "recreated", "file-changed inc/b/fx.h"},
    {"shadow-header", sss_shadow, false, "recreated",
     "include-shadow-appeared inc/a/fx.h"},
    {"shadow-beside", sss_shadow_beside, false, "recreated",
     "warm-unusable: lookup-moved fx.h"},
    {"system-shadow", sss_system_shadow, false, "recreated",
     "include-shadow-appeared inc/a/"},
    {"flag", sss_none, true, "recreated", "argv-changed"},
    {"body-after-flag", sss_body_again, true, "reparsed", ""},
};
#define SSS_STEPS (sizeof(k_sss_steps) / sizeof(k_sss_steps[0]))

/* ── attribute and alias facts ──────────────────────────────────────────── */

/* An asm label in a header (inside the preamble), and in the main file a
 * cleanup(f) local and an alias("x") definition: the attribute call refs and
 * alias address refs the facts extractor derives by tokenizing attribute
 * extents. A reparse must derive them exactly as a cold parse does. */
static bool sss_attr_setup(const char *root)
{
    return sss_write(root, "inc/b/fx_attr.h",
                     "int fx_label(int v) __asm__(\"fx_label_impl\");\n") &&
           sss_edit(root, "src/main.c", "#include <stdint.h>\n",
                    "#include <stdint.h>\n#include \"fx_attr.h\"\n") &&
           sss_edit(root, "src/main.c", "    return fx_sum(&p) * 2;\n}\n",
                    "    return fx_sum(&p) * 2;\n}\n"
                    "static void fx_drop(int *p) { (void)p; }\n"
                    "int fx_orig(int v)\n{\n"
                    "    int t __attribute__((cleanup(fx_drop))) = "
                    "v + fx_label(v);\n"
                    "    return t;\n}\n"
                    "int fx_alias(int v) __attribute__((alias(\"fx_orig\")));\n");
}

static bool sss_attr_body(const char *root)
{
    return sss_edit(root, "src/main.c", "v + fx_label(v)", "v - fx_label(v)");
}

static bool sss_attr_retarget(const char *root)
{
    return sss_edit(root, "src/main.c", "alias(\"fx_orig\")", "alias(\"fx_run\")");
}

static bool sss_attr_label(const char *root)
{
    return sss_edit(root, "inc/b/fx_attr.h", "fx_label_impl", "fx_label_impl2");
}

static const struct sss_step k_sss_attr_steps[] = {
    {"attr-base", sss_attr_setup, false, "created", "first-parse"},
    {"attr-body", sss_attr_body, false, "reparsed", ""},
    {"attr-retarget", sss_attr_retarget, false, "reparsed", ""},
    {"attr-label", sss_attr_label, false, "recreated",
     "file-changed inc/b/fx_attr.h"},
};
#define SSS_ATTR_STEPS (sizeof(k_sss_attr_steps) / sizeof(k_sss_attr_steps[0]))

/* ── the sensor: cold emits and one session process ─────────────────────── */

struct sss_argv {
    const char *items[8];
    size_t n;
};

static void sss_argv(struct sss_argv *a, bool extra)
{
    static const char *const base[] = {"-std=c23", "-Iinc/a", "-Iinc/b",
                                       "-DFX_MODE=1"};
    a->n = 0;
    for (size_t k = 0; k < sizeof(base) / sizeof(base[0]); k++)
        a->items[a->n++] = base[k];
    if (extra)
        a->items[a->n++] = "-DFX_EXTRA=1";
}

static bool sss_cold(const char *sensor, const char *root, const char *out,
                     const struct sss_argv *a)
{
    const char *argv[24];
    char buf[4096];
    bool timed_out = false;
    size_t k = 0;
    int rc;
    const char *head[] = {sensor, "emit", "--root", root, "--source",
                          "src/main.c", "--out", out, "--facts", "--"};
    for (size_t i = 0; i < sizeof(head) / sizeof(head[0]); i++)
        argv[k++] = head[i];
    for (size_t i = 0; i < a->n; i++)
        argv[k++] = a->items[i];
    argv[k] = NULL;
    rc = zcl_spawn_capture_merged_observed(argv, buf, sizeof(buf), 60000,
                                           &timed_out);
    if (rc != 0)
        printf("FAIL cold emit exited %d: %s\n", rc, buf);
    return rc == 0;
}

/* Cold `emit` with an explicit --cc / --toolchain-id (either may be NULL).
 * message carries stdout+stderr; the caller checks rc itself, so a refused
 * emit (a bad --cc or --toolchain-id) is not itself a FAIL here. */
static int sss_cold_cc(const char *sensor, const char *root, const char *out,
                       const char *cc, const char *tc,
                       const struct sss_argv *a, char *message, size_t cap)
{
    const char *argv[28];
    bool timed_out = false;
    size_t k = 0;
    const char *head[] = {sensor, "emit", "--root", root, "--source",
                          "src/main.c", "--out", out, "--facts"};
    for (size_t i = 0; i < sizeof(head) / sizeof(head[0]); i++)
        argv[k++] = head[i];
    if (cc != NULL) {
        argv[k++] = "--cc";
        argv[k++] = cc;
    }
    if (tc != NULL) {
        argv[k++] = "--toolchain-id";
        argv[k++] = tc;
    }
    argv[k++] = "--";
    for (size_t i = 0; i < a->n; i++)
        argv[k++] = a->items[i];
    argv[k] = NULL;
    return zcl_spawn_capture_merged_observed(argv, message, cap, 60000,
                                             &timed_out);
}

struct sss_proc {
    pid_t pid;
    int to, from;
    char buf[SSS_REPLY_MAX * 2];
    size_t have;
};

/* The environment for the session: the caller's, minus any inherited fault
 * flag, plus the fault flag when inject is set. Built before fork. */
static char **sss_env(bool inject)
{
    size_t n = 0, w = 0;
    char **env;
    while (environ[n] != NULL)
        n++;
    env = calloc(n + 2, sizeof(char *));
    if (env == NULL)
        return NULL;
    for (size_t k = 0; k < n; k++) {
        if (strncmp(environ[k], SSS_INJECT "=", sizeof(SSS_INJECT)) != 0)
            env[w++] = environ[k];
    }
    if (inject)
        env[w++] = SSS_INJECT "=1";
    return env;
}

/* Start `sensor session opt...` (opt: up to 3, NULL-terminated early). */
static bool sss_start_opts(struct sss_proc *p, const char *sensor,
                           const char *const opt[3], bool inject,
                           const char *err_log)
{
    char *argv[6] = {(char *)sensor, "session"};
    for (size_t k = 0; k < 3 && opt[k] != NULL; k++)
        argv[2 + k] = (char *)opt[k];
    char **env = sss_env(inject);
    int in[2], out[2];
    if (env == NULL || pipe(in) != 0 || pipe(out) != 0) {
        free(env);
        return false;
    }
    p->pid = fork();
    if (p->pid == 0) {
        int fd = open(err_log, O_WRONLY | O_CREAT | O_TRUNC, 0600);
        (void)dup2(in[0], 0);
        (void)dup2(out[1], 1);
        if (fd >= 0)
            (void)dup2(fd, 2);
        (void)close(in[1]);
        (void)close(out[0]);
        execve(sensor, argv, env);
        _exit(127);
    }
    free(env);
    (void)close(in[0]);
    (void)close(out[1]);
    p->to = in[1];
    p->from = out[0];
    p->have = 0;
    return p->pid > 0;
}

static bool sss_start(struct sss_proc *p, const char *sensor, bool verify,
                      bool inject, const char *err_log)
{
    const char *opt[3] = {verify ? "--verify-cold" : NULL, NULL, NULL};
    return sss_start_opts(p, sensor, opt, inject, err_log);
}

static bool sss_write_all(int fd, const char *s, size_t n)
{
    struct sigaction ign = {.sa_handler = SIG_IGN}, old;
    bool ok = true;
    (void)sigaction(SIGPIPE, &ign, &old);
    while (ok && n > 0) {
        ssize_t w = write(fd, s, n);
        ok = w > 0;
        if (ok) {
            s += w;
            n -= (size_t)w;
        }
    }
    (void)sigaction(SIGPIPE, &old, NULL);
    return ok;
}

/* One stdout line of the session, without its newline. */
static bool sss_line(struct sss_proc *p, char *out, size_t cap)
{
    for (;;) {
        char *nl = memchr(p->buf, '\n', p->have);
        struct pollfd pf = {.fd = p->from, .events = POLLIN};
        ssize_t got;
        if (nl != NULL) {
            size_t n = (size_t)(nl - p->buf);
            (void)snprintf(out, cap, "%.*s", (int)n, p->buf);
            memmove(p->buf, nl + 1, p->have - n - 1);
            p->have -= n + 1;
            return true;
        }
        if (p->have == sizeof(p->buf) || poll(&pf, 1, 120000) <= 0)
            return false;
        got = read(p->from, p->buf + p->have, sizeof(p->buf) - p->have);
        if (got <= 0)
            return false;
        p->have += (size_t)got;
    }
}

/* The request text of one emit, without its newline; its length, or 0. */
static size_t sss_request_text(const char *root, const char *source,
                               const char *out, const struct sss_argv *a,
                               char *line, size_t cap)
{
    int w = snprintf(line, cap,
                     "emit\t--root\t%s\t--source\t%s\t--out\t%s\t--facts\t--",
                     root, source, out);
    for (size_t k = 0; k < a->n && w > 0 && (size_t)w < cap; k++)
        w += snprintf(line + w, cap - (size_t)w, "\t%s", a->items[k]);
    return w <= 0 || (size_t)w + 2 > cap ? 0 : (size_t)w;
}

/* Like sss_request_text, with --cc / --toolchain-id inserted before `--`
 * (either may be NULL). */
static size_t sss_request_text_cc(const char *root, const char *source,
                                  const char *out, const char *cc,
                                  const char *tc, const struct sss_argv *a,
                                  char *line, size_t cap)
{
    int w = snprintf(line, cap, "emit\t--root\t%s\t--source\t%s\t--out\t%s"
                                "\t--facts", root, source, out);
    if (w > 0 && cc != NULL)
        w += snprintf(line + w, cap - (size_t)w, "\t--cc\t%s", cc);
    if (w > 0 && tc != NULL)
        w += snprintf(line + w, cap - (size_t)w, "\t--toolchain-id\t%s", tc);
    if (w > 0)
        w += snprintf(line + w, cap - (size_t)w, "\t--");
    for (size_t k = 0; k < a->n && w > 0 && (size_t)w < cap; k++)
        w += snprintf(line + w, cap - (size_t)w, "\t%s", a->items[k]);
    return w <= 0 || (size_t)w + 2 > cap ? 0 : (size_t)w;
}

static bool sss_request(struct sss_proc *p, const char *root, const char *out,
                        const struct sss_argv *a, char *reply, size_t cap)
{
    char line[8192];
    size_t w = sss_request_text(root, "src/main.c", out, a, line, sizeof(line));
    if (w == 0)
        return false;
    line[w++] = '\n';
    return sss_write_all(p->to, line, w) && sss_line(p, reply, cap);
}

/* End the session: its summary line, then its exit status. */
static int sss_finish(struct sss_proc *p, char *summary, size_t cap)
{
    int status = -1;
    (void)close(p->to);
    if (!sss_line(p, summary, cap))
        summary[0] = '\0';
    (void)close(p->from);
    if (waitpid(p->pid, &status, 0) != p->pid)
        return -1;
    return WIFEXITED(status) ? WEXITSTATUS(status) : -1;
}

/* A string field of a flat JSON reply. */
static bool sss_field(const char *reply, const char *key, char *out,
                      size_t cap)
{
    char pat[64];
    const char *s, *e;
    (void)snprintf(pat, sizeof(pat), "\"%s\":\"", key);
    s = strstr(reply, pat);
    if (s == NULL)
        return false;
    s += strlen(pat);
    e = strchr(s, '"');
    if (e == NULL)
        return false;
    (void)snprintf(out, cap, "%.*s", (int)(e - s), s);
    return true;
}

static bool sss_is(const char *reply, const char *key, const char *want)
{
    char got[512];
    if (sss_field(reply, key, got, sizeof(got)) && strcmp(got, want) == 0)
        return true;
    printf("FAIL reply %s is not \"%s\": %s\n", key, want, reply);
    return false;
}

static bool sss_starts(const char *reply, const char *key, const char *prefix)
{
    char got[512];
    if (sss_field(reply, key, got, sizeof(got)) &&
        strncmp(got, prefix, strlen(prefix)) == 0)
        return true;
    printf("FAIL reply %s does not start \"%s\": %s\n", key, prefix, reply);
    return false;
}

static bool sss_same(const char *x, const char *y)
{
    char *a = NULL, *b = NULL;
    size_t an = 0, bn = 0;
    bool same = sss_read(x, &a, &an) && sss_read(y, &b, &bn) && an == bn &&
                memcmp(a, b, an) == 0;
    free(a);
    free(b);
    if (!same)
        printf("FAIL %s and %s differ\n", x, y);
    return same;
}

/* ── the cases ────────────────────────────────────────────────────────────── */

struct sss_ctx {
    char sensor[PATH_MAX];
    char dir[1024];
    char root[1100];
    const char *extra[2]; /* argv appended to every request of a case */
};

static bool sss_fresh(struct sss_ctx *c, const char *name)
{
    (void)snprintf(c->root, sizeof(c->root), "%s/%s", c->dir, name);
    (void)test_rm_rf_recursive(c->root);
    return mkdir(c->root, 0700) == 0 && sss_tree(c->root);
}

/* Emit step s through the session, then cold; the two files must match.
 * tu and why override the step's expectation when not NULL. */
static bool sss_run_step(struct sss_ctx *c, struct sss_proc *p,
                         const struct sss_step *s, const char *tu,
                         const char *why, char *reply, size_t cap)
{
    char warm[PATH_MAX], cold[PATH_MAX];
    struct sss_argv a;
    sss_argv(&a, s->extra_flag);
    for (size_t k = 0; k < 2 && c->extra[k] != NULL; k++)
        a.items[a.n++] = c->extra[k];
    (void)snprintf(warm, sizeof(warm), "%s/%s.session.bin", c->root, s->name);
    (void)snprintf(cold, sizeof(cold), "%s/%s.cold.bin", c->root, s->name);
    if (!s->edit(c->root) || !sss_request(p, c->root, warm, &a, reply, cap)) {
        printf("FAIL step %s: no session reply\n", s->name);
        return false;
    }
    tu = tu != NULL ? tu : s->tu;
    why = why != NULL ? why : s->why;
    return sss_is(reply, "tu", tu) &&
           (why[0] == '\0' || sss_starts(reply, "reason", why)) &&
           sss_cold(c->sensor, c->root, cold, &a) && sss_same(warm, cold);
}

static bool sss_step_as(struct sss_ctx *c, struct sss_proc *p, size_t k,
                        const char *tu, const char *why, char *reply,
                        size_t cap)
{
    return sss_run_step(c, p, &k_sss_steps[k], tu, why, reply, cap);
}

static bool sss_step(struct sss_ctx *c, struct sss_proc *p, size_t k,
                     char *reply, size_t cap)
{
    return sss_step_as(c, p, k, NULL, NULL, reply, cap);
}

static int sss_t_verified(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX];
    bool started = false;
    TEST_CASE("semantic_sensor: session --verify-cold equals cold after body, "
              "macro, layout, shadow and flag edits") {
        ASSERT(sss_fresh(c, "verified"));
        (void)snprintf(log, sizeof(log), "%s/session.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, true, false, log));
        started = true;
        for (size_t k = 0; k < SSS_STEPS; k++) {
            ASSERT(sss_step(c, &p, k, reply, sizeof(reply)));
            ASSERT(sss_is(reply, "verify", "equal"));
            ASSERT(sss_is(reply, "written", "cold"));
            ASSERT(sss_is(reply, "trust", "verified"));
        }
        started = false;
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 0);
        ASSERT(strstr(reply, "\"mismatches\":0,") != NULL);
        ASSERT(strstr(reply, "\"reparsed\":3,") != NULL);
        ASSERT(strstr(reply, "\"recreated\":7}") != NULL);
    } TEST_END
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

/* The default mode: the first emit is verified, a qualified reparse writes
 * the warm bytes unverified, and they still equal a cold process's. */
static int sss_t_qualified(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX];
    bool started = false;
    TEST_CASE("semantic_sensor: a qualified warm reparse writes warm bytes "
              "equal to cold") {
        ASSERT(sss_fresh(c, "qualified"));
        (void)snprintf(log, sizeof(log), "%s/qualified.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, false, false, log));
        started = true;
        ASSERT(sss_step(c, &p, 0, reply, sizeof(reply)));
        ASSERT(sss_is(reply, "verify", "equal"));
        ASSERT(sss_is(reply, "trust", "verified"));
        ASSERT(sss_step(c, &p, 1, reply, sizeof(reply)));
        ASSERT(sss_is(reply, "written", "warm"));
        ASSERT(sss_is(reply, "verify", "skipped"));
        ASSERT(sss_is(reply, "trust", "qualified"));
        /* A verified TU, then a shadow of an include made inside a system
         * header: only the shadow candidates can see it. Unseen, the warm
         * bytes written here would differ from the cold ones. */
        ASSERT(sss_step(c, &p, 8, reply, sizeof(reply)));
        ASSERT(sss_is(reply, "verify", "equal"));
        ASSERT(sss_step(c, &p, 2, reply, sizeof(reply)));
        ASSERT(sss_is(reply, "written", "warm"));
        ASSERT(sss_step(c, &p, 3, reply, sizeof(reply)));
        ASSERT(sss_is(reply, "verify", "equal"));
        started = false;
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 0);
        ASSERT(strstr(reply, "\"warm_written\":2,") != NULL);
    } TEST_END
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

static int sss_t_injected(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX];
    bool started = false;
    char sections[256];
    TEST_CASE("semantic_sensor: a forced warm mismatch disables reuse and "
              "never writes the warm bytes") {
        ASSERT(sss_fresh(c, "injected"));
        (void)snprintf(log, sizeof(log), "%s/injected.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, false, true, log));
        started = true;
        /* The corrupted warm bytes differ from cold, so a written warm
         * manifest would fail sss_same inside sss_step. */
        ASSERT(sss_step(c, &p, 0, reply, sizeof(reply)));
        ASSERT(sss_is(reply, "verify", "mismatch"));
        ASSERT(sss_is(reply, "written", "cold"));
        ASSERT(sss_is(reply, "trust", "cold"));
        ASSERT(sss_field(reply, "sections", sections, sizeof(sections)) &&
               sections[0] != '\0');
        for (size_t k = 1; k < 3; k++) {
            ASSERT(sss_step_as(c, &p, k, "none", "warm-disabled", reply,
                               sizeof(reply)));
            ASSERT(sss_is(reply, "written", "cold"));
            ASSERT(sss_is(reply, "trust", "cold"));
            ASSERT(sss_is(reply, "verify", "skipped"));
        }
        started = false;
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 0);
        ASSERT(strstr(reply, "\"warm_written\":0,") != NULL);
        ASSERT(strstr(reply, "\"mismatches\":1,") != NULL);
    } TEST_END
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

/* Does the manifest the session wrote for step s carry `needle`? */
static bool sss_carries(const struct sss_ctx *c, const struct sss_step *s,
                        const char *needle)
{
    char path[PATH_MAX], *m = NULL;
    size_t n = 0, len = strlen(needle);
    bool hit = false;
    (void)snprintf(path, sizeof(path), "%s/%s.session.bin", c->root, s->name);
    if (sss_read(path, &m, &n))
        for (size_t k = 0; !hit && k + len <= n; k++)
            hit = memcmp(m + k, needle, len) == 0;
    free(m);
    if (!hit)
        printf("FAIL %s does not carry \"%s\"\n", path, needle);
    return hit;
}

/* The attribute and alias refs of main and preamble declarations, in both
 * modes: every emit verified, and the default (qualified reparses write the
 * warm bytes). Each written manifest equals a cold process's. */
static int sss_t_attrs(struct sss_ctx *c, bool verify)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX];
    bool started = false;
    TEST_CASE(verify ? "semantic_sensor: session --verify-cold equals cold on "
                       "attribute and alias refs"
                     : "semantic_sensor: qualified warm reparses keep attribute "
                       "and alias refs equal to cold") {
        ASSERT(sss_fresh(c, verify ? "attrs-verified" : "attrs-qualified"));
        (void)snprintf(log, sizeof(log), "%s/attrs.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, verify, false, log));
        started = true;
        for (size_t k = 0; k < SSS_ATTR_STEPS; k++) {
            const struct sss_step *s = &k_sss_attr_steps[k];
            bool first = strcmp(s->tu, "reparsed") != 0;
            ASSERT(sss_run_step(c, &p, s, NULL, NULL, reply, sizeof(reply)));
            ASSERT(sss_is(reply, "verify",
                          verify || first ? "equal" : "skipped"));
            ASSERT(sss_is(reply, "written",
                          verify || first ? "cold" : "warm"));
        }
        ASSERT(sss_carries(c, &k_sss_attr_steps[0], "f:fx_label_impl"));
        ASSERT(sss_carries(c, &k_sss_attr_steps[3], "f:fx_label_impl2"));
        started = false;
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 0);
        ASSERT(strstr(reply, "\"mismatches\":0,") != NULL);
        ASSERT(strstr(reply, verify ? "\"warm_written\":0,"
                                    : "\"warm_written\":2,") != NULL);
    } TEST_END
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

/* ── lookups the scan cannot replay ─────────────────────────────────────── */

/* A repo header whose answer depends on a __has_include the scan cannot
 * replay (a macro operand that expands to a header name, not a string
 * literal): nothing binds that answer, so no emit of the TU may be a
 * qualified reparse. opt.h sits in the search path, then goes. */
static const char k_sss_gate[] =
    "#ifndef GATE_H\n"
    "#define GATE_H\n"
    "#define OPT_HDR <opt.h>\n"
    "#if __has_include(OPT_HDR)\n"
    "typedef long fx_opt_t;\n"
    "#else\n"
    "typedef short fx_opt_t;\n"
    "#endif\n"
    "#endif\n";

static bool sss_gate_setup(const char *root)
{
    return sss_write(root, "inc/b/opt.h", "int fx_opt(void);\n") &&
           sss_write(root, "inc/b/gate.h", k_sss_gate) &&
           sss_edit(root, "src/main.c", "#include \"fx.h\"\n",
                    "#include \"fx.h\"\n#include \"gate.h\"\n") &&
           sss_edit(root, "src/main.c", "#define FX_LOCAL 2\n",
                    "#define FX_LOCAL 2\nfx_opt_t fx_opt_v;\n");
}

static bool sss_gate_gone(const char *root)
{
    char path[PATH_MAX];
    (void)snprintf(path, sizeof(path), "%s/inc/b/opt.h", root);
    return unlink(path) == 0;
}

static bool sss_gate_back(const char *root)
{
    return sss_write(root, "inc/b/opt.h", "int fx_opt(void);\n");
}

static const struct sss_step k_sss_gate_steps[] = {
    {"gate-base", sss_gate_setup, false, "created", "first-parse"},
    {"gate-body", sss_body, false, "recreated",
     "lookup-unbound #embed? __has_include(OPT_HDR)"},
    {"gate-gone", sss_gate_gone, false, "recreated", "lookup-unbound"},
    {"gate-back", sss_gate_back, false, "recreated", "lookup-unbound"},
};
#define SSS_GATE_STEPS (sizeof(k_sss_gate_steps) / sizeof(k_sss_gate_steps[0]))

/* The other spellings the scan cannot replay, each alone in gate.h (inside
 * #if 0: the scan reads text, the compiler need not accept it). The emit
 * after the rewrite recreates for the changed file; the untouched emit after
 * it must recreate again, naming the unbound lookup. */
struct sss_unbound {
    const char *name;
    const char *body;
    const char *why; /* the reason prefix of the untouched emit */
};

static const struct sss_unbound k_sss_unbound[] = {
    {"gnu-next", "#if 0\n#if __has_include_next__(<opt.h>)\n#endif\n#endif\n",
     "lookup-unbound #embed? __has_include_next__(<opt.h>)"},
    {"has-embed", "#if 0\n#if __has_embed(\"opt.h\")\n#endif\n#endif\n",
     "lookup-unbound __has_embed("},
    {"embed", "#if 0\nstatic const char b[] = {\n#embed \"opt.h\"\n};\n#endif\n",
     "lookup-unbound #embed"},
    {"embed-spaced", "#if 0\n  %: /* x */ embed <opt.h>\n#endif\n",
     "lookup-unbound #embed"},
    {"continued", "#if 0\n#if __has_include(\\\n\"opt.h\")\n#endif\n#endif\n",
     "lookup-unbound #embed? __has_include("},
    {"split-word", "#if 0\n#if __has_inc\\\nlude(<opt.h>)\n#endif\n#endif\n",
     "lookup-unbound #embed? __has_include(<opt.h>)"},
    {"gnu-word", "#if 0\n#if __has_include__(<opt.h>)\n#endif\n#endif\n",
     "lookup-unbound #embed? __has_include__(<opt.h>)"},
};
#define SSS_UNBOUND (sizeof(k_sss_unbound) / sizeof(k_sss_unbound[0]))

/* The spellings the scan replays, or that are no lookup at all: each keeps
 * its TU warm. */
static const struct sss_unbound k_sss_warm[] = {
    {"literal", "#if __has_include(\"opt.h\")\n#endif\n", ""},
    {"macro-literal",
     "#define OPT_NAME \"opt.h\"\n#if __has_include(OPT_NAME)\n#endif\n", ""},
    {"next-literal", "#if __has_include_next(<opt.h>)\n#endif\n", ""},
    {"comment-words",
     "/* __has_embed(\"opt.h\") __has_include_next(<opt.h>) */\n"
     "// #embed <opt.h>\n"
     "const char *const fx_word = \"__has_include(OPT_HDR)\";\n",
     ""},
};
#define SSS_WARM (sizeof(k_sss_warm) / sizeof(k_sss_warm[0]))

static const char *g_sss_gate_body;

/* gate.h keeps the typedef main.c uses; the construct follows it. */
static bool sss_gate_rewrite(const char *root)
{
    char body[1024];
    (void)snprintf(body, sizeof(body), "typedef long fx_opt_t;\n%s",
                   g_sss_gate_body);
    return sss_write(root, "inc/b/gate.h", body);
}

/* Rewrite gate.h to body, then emit twice: file-changed, then why. */
static bool sss_unbound_pair(struct sss_ctx *c, struct sss_proc *p,
                             const char *name, const char *body,
                             const char *why, char *reply, size_t cap)
{
    char first[64], second[64];
    struct sss_step s = {first, sss_gate_rewrite, false, "recreated",
                         "file-changed inc/b/gate.h"};
    (void)snprintf(first, sizeof(first), "unbound-%s", name);
    (void)snprintf(second, sizeof(second), "unbound-%s-again", name);
    g_sss_gate_body = body;
    if (!sss_run_step(c, p, &s, NULL, NULL, reply, cap))
        return false;
    s = (struct sss_step){second, sss_none, false, why[0] ? "recreated"
                                                          : "reparsed", why};
    return sss_run_step(c, p, &s, NULL, NULL, reply, cap);
}

static int sss_t_unbound(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX];
    bool started = false;
    TEST_CASE("semantic_sensor: a __has_include the scan cannot replay makes "
              "every emit of its TU recreate and verify") {
        ASSERT(sss_fresh(c, "unbound"));
        (void)snprintf(log, sizeof(log), "%s/unbound.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, false, false, log));
        started = true;
        for (size_t k = 0; k < SSS_GATE_STEPS; k++) {
            ASSERT(sss_run_step(c, &p, &k_sss_gate_steps[k], NULL, NULL,
                                reply, sizeof(reply)));
            ASSERT(sss_is(reply, "verify", "equal"));
            ASSERT(sss_is(reply, "written", "cold"));
        }
        for (size_t k = 0; k < SSS_UNBOUND; k++) {
            const struct sss_unbound *u = &k_sss_unbound[k];
            ASSERT(sss_unbound_pair(c, &p, u->name, u->body, u->why, reply,
                                    sizeof(reply)));
            ASSERT(sss_is(reply, "verify", "equal"));
        }
        /* A literal or string-literal-macro operand and a __has_include_next
         * are replayed, and a word in a comment or a string is no lookup:
         * each TU stays warm. */
        for (size_t k = 0; k < SSS_WARM; k++) {
            const struct sss_unbound *u = &k_sss_warm[k];
            ASSERT(sss_unbound_pair(c, &p, u->name, u->body, u->why, reply,
                                    sizeof(reply)));
            ASSERT(sss_is(reply, "written", "warm"));
        }
        started = false;
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 0);
        ASSERT(strstr(reply, "\"mismatches\":0,") != NULL);
    } TEST_END
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

/* ── post-checks of a reparse's own manifest ─────────────────────────────── */

/* inc/a/fx2.h is a directory, so the front end takes inc/b/fx2.h: once a
 * reparse reads that file, its manifest has a shadow candidate the TU's
 * baseline lacks. fx3.h is reached through a computed include, a lookup no
 * negative claim covers. Both are made in the main file below its preamble,
 * where every pre-check of the accepted manifest still passes. */
static bool sss_post_setup(const char *root)
{
    char dir[PATH_MAX];
    (void)snprintf(dir, sizeof(dir), "%s/inc/a/fx2.h", root);
    return (mkdir(dir, 0700) == 0 || errno == EEXIST) &&
           sss_write(root, "inc/b/fx2.h", "int fx_two(void);\n") &&
           sss_write(root, "inc/b/fx3.h", "int fx_three(void);\n");
}

static bool sss_post_shadow(const char *root)
{
    return sss_edit(root, "src/main.c", "    return fx_sum(&p) * 2;\n}\n",
                    "    return fx_sum(&p) * 2;\n}\n#include \"fx2.h\"\n");
}

static bool sss_post_computed(const char *root)
{
    return sss_edit(root, "src/main.c", "#include \"fx2.h\"\n",
                    "#include \"fx2.h\"\n#define FX_H3 \"fx3.h\"\n"
                    "#include FX_H3\n");
}

static const struct sss_step k_sss_post_steps[] = {
    {"post-base", sss_post_setup, false, "created", "first-parse"},
    {"post-body", sss_body, false, "reparsed", ""},
    {"post-shadow", sss_post_shadow, false, "recreated",
     "warm-unusable: include-shadow-appeared inc/a/fx2.h"},
    {"post-steady", sss_none, false, "reparsed", ""},
    {"post-computed", sss_post_computed, false, "recreated",
     "warm-unusable: lookup-unbound"},
};
#define SSS_POST_STEPS (sizeof(k_sss_post_steps) / sizeof(k_sss_post_steps[0]))

static int sss_t_post(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX];
    bool started = false;
    TEST_CASE("semantic_sensor: a reparse whose own manifest has a new shadow "
              "candidate or an unbound lookup is not written warm") {
        ASSERT(sss_fresh(c, "post"));
        (void)snprintf(log, sizeof(log), "%s/post.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, false, false, log));
        started = true;
        for (size_t k = 0; k < SSS_POST_STEPS; k++) {
            const struct sss_step *s = &k_sss_post_steps[k];
            bool reparse = strcmp(s->tu, "reparsed") == 0;
            ASSERT(sss_run_step(c, &p, s, NULL, NULL, reply, sizeof(reply)));
            ASSERT(sss_is(reply, "written", reparse ? "warm" : "cold"));
            ASSERT(sss_is(reply, "verify", reparse ? "skipped" : "equal"));
        }
        started = false;
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 0);
        ASSERT(strstr(reply, "\"mismatches\":0,") != NULL);
    } TEST_END
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

/* ── argv a reparse cannot bind ───────────────────────────────────────────── */

/* A response file could change the compiler's argv unseen, so the sensor
 * refuses it before parsing and writes nothing. An implicit module map lies
 * outside every file the manifest hashes: such a TU is recreated on every
 * emit. */
static bool sss_rsp_setup(const char *root)
{
    return sss_write(root, "rsp.txt", "-DFX_RSP=1\n");
}

/* The session refuses argv carrying a response file and writes no output. */
static bool sss_rsp_refused(struct sss_ctx *c, struct sss_proc *p, char *reply,
                            size_t cap)
{
    char out[PATH_MAX];
    struct sss_argv a;
    sss_argv(&a, false);
    a.items[a.n++] = "@rsp.txt";
    (void)snprintf(out, sizeof(out), "%s/rsp.session.bin", c->root);
    if (!sss_rsp_setup(c->root) || !sss_request(p, c->root, out, &a, reply, cap))
        return false;
    if (strstr(reply, "\"ok\":false") == NULL ||
        strstr(reply, "indirect compiler options") == NULL) {
        printf("FAIL response-file argv is not refused: %s\n", reply);
        return false;
    }
    if (access(out, F_OK) == 0) {
        printf("FAIL a refused request wrote %s\n", out);
        return false;
    }
    return true;
}

static int sss_t_untrackable(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX];
    bool started = false;
    const struct sss_step mod = {"modules", sss_none, false, "created",
                                 "first-parse"};
    const struct sss_step mod_again = {"modules-again", sss_body, false,
                                       "recreated", "argv-untrackable"};
    TEST_CASE("semantic_sensor: a response file is refused, and a -fmodules "
              "argv recreates the TU on every emit") {
        ASSERT(sss_fresh(c, "untrackable"));
        (void)snprintf(log, sizeof(log), "%s/untrackable.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, false, false, log));
        started = true;
        ASSERT(sss_rsp_refused(c, &p, reply, sizeof(reply)));
        c->extra[0] = "-fmodules";
        c->extra[1] = "-fmodules-cache-path=mc";
        ASSERT(sss_run_step(c, &p, &mod, NULL, NULL, reply, sizeof(reply)));
        ASSERT(sss_run_step(c, &p, &mod_again, NULL, NULL, reply,
                            sizeof(reply)));
        ASSERT(sss_is(reply, "verify", "equal"));
        started = false;
        /* the refused response-file request makes the session exit 3 */
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 3);
        ASSERT(strstr(reply, "\"warm_written\":0,") != NULL);
    } TEST_END
    c->extra[0] = NULL;
    c->extra[1] = NULL;
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

/* ── the stdin protocol ───────────────────────────────────────────────────── */

/* Send n bytes as one request (the caller supplies the newline). */
static bool sss_send(struct sss_proc *p, const char *line, size_t n,
                     char *reply, size_t cap)
{
    return sss_write_all(p->to, line, n) && sss_line(p, reply, cap);
}

/* No byte of a reply is outside ASCII: JSON escapes carry the rest. */
static bool sss_ascii(const char *reply)
{
    for (const unsigned char *s = (const unsigned char *)reply; *s; s++) {
        if (*s >= 0x80) {
            printf("FAIL reply carries a raw byte 0x%02x: %s\n", *s, reply);
            return false;
        }
    }
    return true;
}

static bool sss_refused(const char *reply, const char *why)
{
    if (strstr(reply, "\"ok\":false") != NULL)
        return why == NULL || sss_starts(reply, "why", why);
    printf("FAIL reply is not a refusal: %s\n", reply);
    return false;
}

static int sss_t_bad_opts(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX];
    static const char *const bad[][3] = {
        {"--max-tus", "64x", NULL},
        {"--max-tus", "", NULL},
        {"--max-tus", " 64", NULL},
        {"--max-tus", "0", NULL},
    };
    TEST_CASE("semantic_sensor: session refuses --max-tus with anything but "
              "a number from 1 to 256") {
        (void)snprintf(log, sizeof(log), "%s/opts.err", c->dir);
        for (size_t k = 0; k < sizeof(bad) / sizeof(bad[0]); k++) {
            ASSERT(sss_start_opts(&p, c->sensor, bad[k], false, log));
            ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 2);
        }
    } TEST_END
    return failures;
}

static int sss_t_protocol(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX], line[8192], out[PATH_MAX];
    struct sss_argv a;
    bool started = false;
    char *big = NULL;
    size_t w;
    TEST_CASE("semantic_sensor: session refuses a NUL, non-UTF-8 or overlong "
              "request line and escapes non-ASCII paths in its reply") {
        ASSERT(sss_fresh(c, "protocol"));
        ASSERT(sss_write(c->root, "src/m\xc3\xa9.c", k_sss_main));
        (void)snprintf(log, sizeof(log), "%s/protocol.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, false, false, log));
        started = true;
        sss_argv(&a, false);
        /* A whole request, then a NUL and more bytes before the newline. */
        (void)snprintf(out, sizeof(out), "%s/nul.bin", c->root);
        w = sss_request_text(c->root, "src/main.c", out, &a, line,
                             sizeof(line) - 8);
        ASSERT(w > 0);
        memcpy(line + w, "\0junk\n", 6);
        ASSERT(sss_send(&p, line, w + 6, reply, sizeof(reply)));
        ASSERT(sss_refused(reply, "request line has a NUL byte"));
        /* A source path in UTF-8 is served, and escaped in the reply. */
        (void)snprintf(out, sizeof(out), "%s/utf8-\xc3\xa9.bin", c->root);
        w = sss_request_text(c->root, "src/m\xc3\xa9.c", out, &a, line,
                             sizeof(line));
        ASSERT(w > 0);
        line[w++] = '\n';
        ASSERT(sss_send(&p, line, w, reply, sizeof(reply)));
        ASSERT(strstr(reply, "\"ok\":true") != NULL);
        ASSERT(strstr(reply, "\"source\":\"src/m\\u00e9.c\"") != NULL);
        ASSERT(strstr(reply, "/utf8-\\u00e9.bin\"") != NULL);
        ASSERT(sss_ascii(reply));
        /* A byte that is not UTF-8 is refused, and not echoed raw. */
        w = sss_request_text(c->root, "src/m\xff.c", out, &a, line,
                             sizeof(line));
        ASSERT(w > 0);
        line[w++] = '\n';
        ASSERT(sss_send(&p, line, w, reply, sizeof(reply)));
        ASSERT(sss_refused(reply, "request line is not UTF-8"));
        ASSERT(sss_ascii(reply));
        /* A line past the bound is refused; the session goes on. */
        big = malloc((1u << 20) + 2);
        ASSERT(big != NULL);
        memset(big, 'a', (1u << 20) + 1);
        big[(1u << 20) + 1] = '\n';
        ASSERT(sss_send(&p, big, (1u << 20) + 2, reply, sizeof(reply)));
        ASSERT(sss_refused(reply, "request line too long"));
        (void)snprintf(out, sizeof(out), "%s/after.bin", c->root);
        w = sss_request_text(c->root, "src/main.c", out, &a, line,
                             sizeof(line));
        ASSERT(w > 0);
        line[w++] = '\n';
        ASSERT(sss_send(&p, line, w, reply, sizeof(reply)));
        ASSERT(strstr(reply, "\"ok\":true") != NULL);
        started = false;
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 3);
        ASSERT(strstr(reply, "\"refused\":3,") != NULL);
    } TEST_END
    free(big);
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

/* ── the session's --cc / --toolchain-id (docs/work/SEMANTIC_MANIFEST.md,
 * "Warm session"; IDENTITY drift is object-compiler drift) ───────────────── */

#define SSS_TC_A "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a"
#define SSS_TC_B "b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6"
#define SSS_TC_ZERO                                                            \
    "0000000000000000000000000000000000000000000000000000000000000000"
#define SSS_TC_NOTHEX                                                          \
    "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"

/* A stand-in compiler under root, never run, only hashed; its "object-cc
 * <path> sha3-256 <hex>" IDENTITY text, spelled root-relative as IDENTITY
 * itself spells it (cm_spell_real), not by its filesystem path. */
static bool sss_write_cc(const char *root, const char *rel, const char *body,
                         char *text, size_t cap)
{
    char path[PATH_MAX];
    uint8_t d[32];
    char hex[65];
    if (!sss_write(root, rel, body))
        return false;
    (void)snprintf(path, sizeof(path), "%s/%s", root, rel);
    if (chmod(path, 0755) != 0)
        return false;
    zcl_sha3_256((const unsigned char *)body, strlen(body), d);
    zcl_hex_encode(d, 32, hex);
    return (size_t)snprintf(text, cap, "object-cc %s sha3-256 %s", rel,
                            hex) < cap;
}

static bool sss_bytes_scan(const char *path, const char *needle)
{
    char *m = NULL;
    size_t n = 0, len = strlen(needle);
    bool hit = false;
    if (sss_read(path, &m, &n))
        for (size_t k = 0; !hit && k + len <= n; k++)
            hit = memcmp(m + k, needle, len) == 0;
    free(m);
    return hit;
}

static bool sss_bytes_has(const char *path, const char *needle)
{
    bool hit = sss_bytes_scan(path, needle);
    if (!hit)
        printf("FAIL %s does not carry \"%s\"\n", path, needle);
    return hit;
}

static bool sss_bytes_lacks(const char *path, const char *needle)
{
    bool hit = sss_bytes_scan(path, needle);
    if (hit)
        printf("FAIL %s carries \"%s\" (a stale compiler identity)\n", path,
               needle);
    return !hit;
}

/* One request with --cc/--toolchain-id, its cold twin, and the equality and
 * IDENTITY-text checks every accepted case here needs. */
static bool sss_cc_step(struct sss_ctx *c, struct sss_proc *p,
                        const char *name, const char *cc, const char *tc,
                        const char *identity_text, char *reply, size_t cap)
{
    char warm[PATH_MAX], cold[PATH_MAX], line[8192], message[4096];
    struct sss_argv a;
    size_t w;
    int rc;
    sss_argv(&a, false);
    (void)snprintf(warm, sizeof(warm), "%s/%s.session.bin", c->root, name);
    (void)snprintf(cold, sizeof(cold), "%s/%s.cold.bin", c->root, name);
    w = sss_request_text_cc(c->root, "src/main.c", warm, cc, tc, &a, line,
                            sizeof(line));
    if (w == 0)
        return false;
    line[w++] = '\n';
    if (!sss_send(p, line, w, reply, cap)) {
        printf("FAIL step %s: no session reply\n", name);
        return false;
    }
    if (strstr(reply, "\"ok\":true") == NULL) {
        printf("FAIL step %s: refused: %s\n", name, reply);
        return false;
    }
    rc = sss_cold_cc(c->sensor, c->root, cold, cc, tc, &a, message,
                     sizeof(message));
    if (rc != 0) {
        printf("FAIL step %s: cold emit exited %d: %s\n", name, rc, message);
        return false;
    }
    return sss_same(warm, cold) &&
           (identity_text == NULL || (sss_bytes_has(warm, identity_text) &&
                                      sss_bytes_has(cold, identity_text)));
}

/* Case 1: a session request with --cc/--toolchain-id equals a cold emit of
 * the same options, and its IDENTITY names the same object compiler. Case 2:
 * changing --toolchain-id or --cc for the same TU never reuses the old warm
 * bytes, the new manifest's IDENTITY reflects the new compiler, and the
 * reply is never trusted "verified" without a cold check of the new
 * options (every step here is checked byte-for-byte against a fresh cold
 * emit of its own options, so a stale reuse would fail sss_same). */
static int sss_t_object_cc(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX];
    char cc_a[PATH_MAX], cc_b[PATH_MAX], text_a[160], text_b[160];
    char path[PATH_MAX];
    bool started = false;
    TEST_CASE("semantic_sensor: session --cc/--toolchain-id equal cold, and "
              "changing either never reuses the old warm bytes") {
        ASSERT(sss_fresh(c, "object-cc"));
        ASSERT(sss_write_cc(c->root, "bin-a/cc", "#!/bin/sh\nexit 0 # a\n",
                            text_a, sizeof(text_a)));
        ASSERT(sss_write_cc(c->root, "bin-b/cc", "#!/bin/sh\nexit 0 # b\n",
                            text_b, sizeof(text_b)));
        (void)snprintf(cc_a, sizeof(cc_a), "%s/bin-a/cc", c->root);
        (void)snprintf(cc_b, sizeof(cc_b), "%s/bin-b/cc", c->root);
        (void)snprintf(log, sizeof(log), "%s/object-cc.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, false, false, log));
        started = true;
        /* Case 1: base request, --cc A / toolchain A. */
        ASSERT(sss_cc_step(c, &p, "cc-base", cc_a, SSS_TC_A, text_a, reply,
                           sizeof(reply)));
        ASSERT(sss_is(reply, "trust", "verified"));
        /* Case 2a: same TU, same --cc, a new --toolchain-id: the manifest
         * changes (IDENTITY carries the toolchain) and must equal a fresh
         * cold emit under the new id, never the old warm bytes. */
        ASSERT(sss_cc_step(c, &p, "cc-new-toolchain", cc_a, SSS_TC_B, text_a,
                           reply, sizeof(reply)));
        ASSERT(strstr(reply, "\"trust\":\"qualified\"") == NULL);
        /* Case 2b: same TU, a different --cc (same toolchain id): IDENTITY
         * must name the new compiler, not the old one. */
        ASSERT(sss_cc_step(c, &p, "cc-new-compiler", cc_b, SSS_TC_B, text_b,
                           reply, sizeof(reply)));
        ASSERT(strstr(reply, "\"trust\":\"qualified\"") == NULL);
        (void)snprintf(path, sizeof(path), "%s/cc-new-compiler.session.bin",
                      c->root);
        ASSERT(sss_bytes_lacks(path, text_a));
        /* Back to the first compiler and toolchain: still equal to cold,
         * still not a stale "qualified" reuse of the intervening TUs. */
        ASSERT(sss_cc_step(c, &p, "cc-back-to-a", cc_a, SSS_TC_A, text_a,
                           reply, sizeof(reply)));
        started = false;
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 0);
        ASSERT(strstr(reply, "\"mismatches\":0,") != NULL);
    } TEST_END
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

/* Case 5: a --cc that resolves only to a compile-cache wrapper (a masquerade
 * link with no real compiler behind it) gives "object-cc unknown", the same
 * as cold. */
static int sss_t_object_cc_wrapper(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX], cc[PATH_MAX];
    bool started = false;
    TEST_CASE("semantic_sensor: a --cc naming only a compile-cache wrapper "
              "is object-cc unknown, the same as cold") {
        ASSERT(sss_fresh(c, "object-cc-wrapper"));
        ASSERT(sss_write_cc(c->root, "bin-w/ccache",
                            "#!/bin/sh\nexit 0 # compile cache\n", reply,
                            sizeof(reply)));
        (void)snprintf(cc, sizeof(cc), "%s/bin-w/ccache", c->root);
        (void)snprintf(log, sizeof(log), "%s/object-cc-wrapper.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, false, false, log));
        started = true;
        ASSERT(sss_cc_step(c, &p, "wrapper", cc, SSS_TC_A,
                           "; object-cc unknown", reply, sizeof(reply)));
        started = false;
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 0);
    } TEST_END
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

/* A refused --cc/--toolchain-id request: ok:false, no output file, and the
 * session exits 3 (refused) once its stdin ends. */
static bool sss_cc_refused(struct sss_ctx *c, struct sss_proc *p,
                           const char *name, const char *cc, const char *tc,
                           char *reply, size_t cap)
{
    char out[PATH_MAX], line[8192];
    struct sss_argv a;
    size_t w;
    sss_argv(&a, false);
    (void)snprintf(out, sizeof(out), "%s/%s.session.bin", c->root, name);
    w = sss_request_text_cc(c->root, "src/main.c", out, cc, tc, &a, line,
                            sizeof(line));
    if (w == 0)
        return false;
    line[w++] = '\n';
    if (!sss_send(p, line, w, reply, cap))
        return false;
    if (strstr(reply, "\"ok\":false") == NULL) {
        printf("FAIL step %s is not refused: %s\n", name, reply);
        return false;
    }
    if (access(out, F_OK) == 0) {
        printf("FAIL a refused request wrote %s\n", out);
        return false;
    }
    return true;
}

/* Case 3: an invalid --toolchain-id (all zeros, or not hex) is refused.
 * Case 4: a --cc naming a missing executable is refused the same way. */
static int sss_t_object_cc_invalid(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX], cc[PATH_MAX], missing[PATH_MAX];
    bool started = false;
    TEST_CASE("semantic_sensor: session refuses an invalid --toolchain-id "
              "and a --cc naming no executable, writing nothing") {
        ASSERT(sss_fresh(c, "object-cc-invalid"));
        ASSERT(sss_write_cc(c->root, "bin-a/cc", "#!/bin/sh\nexit 0 # a\n",
                            reply, sizeof(reply)));
        (void)snprintf(cc, sizeof(cc), "%s/bin-a/cc", c->root);
        (void)snprintf(missing, sizeof(missing), "%s/no-such-cc", c->root);
        (void)snprintf(log, sizeof(log), "%s/object-cc-invalid.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, false, false, log));
        started = true;
        ASSERT(sss_cc_refused(c, &p, "zero-toolchain", cc, SSS_TC_ZERO, reply,
                              sizeof(reply)));
        ASSERT(sss_refused(reply, "--toolchain-id"));
        ASSERT(sss_cc_refused(c, &p, "nothex-toolchain", cc, SSS_TC_NOTHEX,
                              reply, sizeof(reply)));
        ASSERT(sss_refused(reply, "--toolchain-id"));
        ASSERT(sss_cc_refused(c, &p, "missing-cc", missing, SSS_TC_A, reply,
                              sizeof(reply)));
        ASSERT(sss_refused(reply, "object compiler"));
        /* The session still serves a good request afterward. */
        ASSERT(sss_cc_step(c, &p, "after-invalid", cc, SSS_TC_A, NULL, reply,
                           sizeof(reply)));
        started = false;
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 3);
        ASSERT(strstr(reply, "\"refused\":3,") != NULL);
    } TEST_END
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

int semantic_sensor_session_cases(void)
{
    int failures = 0;
    struct sss_ctx c = {0};
    if (realpath(SSS_SENSOR, c.sensor) == NULL ||
        test_mkdtemp(c.dir, sizeof(c.dir), "semsensor_session") == NULL) {
        printf("FAIL semantic_sensor session: no sensor path or temp dir\n");
        return 1;
    }
    failures += sss_t_verified(&c);
    failures += sss_t_qualified(&c);
    failures += sss_t_injected(&c);
    failures += sss_t_attrs(&c, true);
    failures += sss_t_attrs(&c, false);
    failures += sss_t_unbound(&c);
    failures += sss_t_post(&c);
    failures += sss_t_untrackable(&c);
    failures += sss_t_object_cc(&c);
    failures += sss_t_object_cc_wrapper(&c);
    failures += sss_t_object_cc_invalid(&c);
    failures += sss_t_bad_opts(&c);
    failures += sss_t_protocol(&c);
    (void)test_rm_rf_recursive(c.dir);
    return failures;
}
