/* Copyright 2026 Rhett Creighton - Apache License 2.0
 * purpose: Live cases of the semantic sensor's warm session: warm equals the cold oracle across edits, and a forced mismatch never writes warm bytes.
 *
 * ACCEPTANCE BAR for `z23-clang-manifest session` (tools/sensors/
 * clang_manifest_session.c; contract in docs/work/SEMANTIC_MANIFEST.md,
 * "Warm session"). One session process serves every emit of a case while
 * the test edits the fixture tree between requests. After every request the
 * manifest the session wrote must be byte-identical to a separate cold
 * `emit` process over the same tree and argv, and the session must report
 * the TU reuse the contract requires:
 *   - a function-body edit and a main-file macro edit reparse the live TU;
 *   - a header macro edit, a header layout edit, a header that newly shadows
 *     the one used, a header that newly shadows one a system header
 *     includes (no LOOKUPS record covers that include) and a flag change
 *     each recreate it;
 *   - with ZCL_CLANG_MANIFEST_INJECT_WARM_MISMATCH=1 the warm bytes are
 *     corrupted, the oracle reports the mismatch, the cold bytes are written
 *     and warm reuse stays off for that TU for the rest of the session.
 *
 * Do not edit this file to make the implementation pass. */
#if !defined(_WIN32) && !defined(_DEFAULT_SOURCE)
#define _DEFAULT_SOURCE
#endif

#include "test/semantic_sensor_session.h"

#include "test/test_core.h"
#include "util/spawn.h"
#include "vcs/semantic_manifest.h"

#include <fcntl.h>
#include <poll.h>
#include <signal.h>
#include <sys/wait.h>

#define SSS_SENSOR "build/bin/z23-clang-manifest"
#define SSS_INJECT "ZCL_CLANG_MANIFEST_INJECT_WARM_MISMATCH"
#define SSS_REPLY_MAX 4096

extern char **environ;

static const char k_sss_header[] =
    "#ifndef FX_H\n"
    "#define FX_H\n"
    "#define FX_SCALE 3\n"
    "struct fx_pair { int a; int b; };\n"
    "int fx_sum(const struct fx_pair *p);\n"
    "#endif\n";

static const char k_sss_main[] =
    "#include \"fx.h\"\n"
    "#include <stdint.h>\n"
    "#define FX_LOCAL 2\n"
    "int fx_sum(const struct fx_pair *p) { return p->a + p->b; }\n"
    "int fx_run(int v)\n"
    "{\n"
    "    struct fx_pair p = {v, FX_SCALE + FX_LOCAL};\n"
    "    return fx_sum(&p) * 2;\n"
    "}\n";

/* ── the fixture tree ─────────────────────────────────────────────────── */

static bool sss_write(const char *root, const char *rel, const char *body)
{
    char path[PATH_MAX];
    FILE *fp;
    bool ok;
    for (const char *s = strchr(rel, '/'); s != NULL; s = strchr(s + 1, '/')) {
        (void)snprintf(path, sizeof(path), "%s/%.*s", root, (int)(s - rel), rel);
        if (mkdir(path, 0700) != 0 && errno != EEXIST)
            return false;
    }
    (void)snprintf(path, sizeof(path), "%s/%s", root, rel);
    fp = fopen(path, "wb");
    if (fp == NULL)
        return false;
    ok = fputs(body, fp) >= 0;
    return fclose(fp) == 0 && ok;
}

static bool sss_read(const char *path, char **out, size_t *len)
{
    FILE *fp = fopen(path, "rb");
    long size;
    bool ok = false;
    *out = NULL;
    if (fp == NULL)
        return false;
    if (fseek(fp, 0, SEEK_END) == 0 && (size = ftell(fp)) >= 0 &&
        fseek(fp, 0, SEEK_SET) == 0) {
        *out = malloc((size_t)size + 1);
        ok = *out != NULL && fread(*out, 1, (size_t)size, fp) == (size_t)size;
        *len = (size_t)size;
    }
    (void)fclose(fp);
    if (ok)
        (*out)[*len] = '\0';
    return ok;
}

/* Replace the first `from` in root/rel with `to`. */
static bool sss_edit(const char *root, const char *rel, const char *from,
                     const char *to)
{
    char path[PATH_MAX], next[8192];
    char *body = NULL, *hit;
    size_t n = 0;
    bool ok = false;
    (void)snprintf(path, sizeof(path), "%s/%s", root, rel);
    if (!sss_read(path, &body, &n))
        return false;
    hit = strstr(body, from);
    if (hit != NULL && n + strlen(to) < sizeof(next)) {
        (void)snprintf(next, sizeof(next), "%.*s%s%s", (int)(hit - body), body,
                       to, hit + strlen(from));
        ok = sss_write(root, rel, next);
    }
    free(body);
    return ok;
}

static bool sss_tree(const char *root)
{
    char dir[PATH_MAX];
    (void)snprintf(dir, sizeof(dir), "%s/inc", root);
    if (mkdir(dir, 0700) != 0 && errno != EEXIST)
        return false;
    (void)snprintf(dir, sizeof(dir), "%s/inc/a", root);
    if (mkdir(dir, 0700) != 0 && errno != EEXIST)
        return false;
    return sss_write(root, "inc/b/fx.h", k_sss_header) &&
           sss_write(root, "src/main.c", k_sss_main);
}

/* ── the edits, in session order ─────────────────────────────────────────── */

static bool sss_none(const char *root)
{
    (void)root;
    return true;
}

static bool sss_body(const char *root)
{
    return sss_edit(root, "src/main.c", "p->a + p->b", "p->a - p->b");
}

/* A #define right after the includes lies inside the preamble region, so
 * the front end rebuilds the preamble inside the reparse. */
static bool sss_main_macro(const char *root)
{
    return sss_edit(root, "src/main.c", "FX_LOCAL 2", "FX_LOCAL 7");
}

static bool sss_header_macro(const char *root)
{
    return sss_edit(root, "inc/b/fx.h", "FX_SCALE 3", "FX_SCALE 4");
}

/* The same length and, restored after the write, the same modification
 * time: the front end's own preamble check (size and mtime) cannot see this
 * edit; only the session's content digests can. */
static bool sss_header_same_stat(const char *root)
{
    char path[PATH_MAX];
    struct stat before;
    struct timespec times[2];
    (void)snprintf(path, sizeof(path), "%s/inc/b/fx.h", root);
    if (stat(path, &before) != 0 ||
        !sss_edit(root, "inc/b/fx.h", "FX_SCALE 4", "FX_SCALE 5"))
        return false;
    times[0] = before.st_atim;
    times[1] = before.st_mtim;
    return utimensat(AT_FDCWD, path, times, 0) == 0;
}

static bool sss_layout(const char *root)
{
    return sss_edit(root, "inc/b/fx.h", "int b; };", "int b; long c; };");
}

/* inc/a is searched before inc/b: the new file shadows the one in use. The
 * shadow candidates see it before the reparse. */
static bool sss_shadow(const char *root)
{
    return sss_write(root, "inc/a/fx.h",
                     "#ifndef FX_H\n#define FX_H\n#define FX_SCALE 9\n"
                     "struct fx_pair { long a; int b; };\n"
                     "int fx_sum(const struct fx_pair *p);\n#endif\n");
}

/* The includer's own directory is searched first for a quoted include and is
 * no search dir: only the fresh probes of the LOOKUPS record see this one,
 * after the reparse, which is then retried as a fresh parse. */
static bool sss_shadow_beside(const char *root)
{
    return sss_write(root, "src/fx.h",
                     "#ifndef FX_H\n#define FX_H\n#define FX_SCALE 11\n"
                     "struct fx_pair { short a; int b; };\n"
                     "int fx_sum(const struct fx_pair *p);\n#endif\n");
}

/* A leaf system header that the base TU read only through another system
 * header: no LOOKUPS record covers its include. */
struct sss_leaf {
    char path[PATH_MAX];
    char *body;
};

/* The host path of a system file's manifest path: "@sys/x" is "/x". */
static bool sss_sys_path(const char *p, size_t n, char *out, size_t cap)
{
    int w;
    if (n < 5 || memcmp(p, "@sys/", 5) != 0)
        return false;
    w = snprintf(out, cap, "/%.*s", (int)(n - 5), p + 5);
    return w > 0 && (size_t)w < cap;
}

static bool sss_leaf_cb(void *ctx, const struct vcs_semantic_fields_v1 *f)
{
    struct sss_leaf *l = ctx;
    size_t n = 0;
    if (l->body != NULL || f->ntext < 1 || f->nnum < 1 ||
        f->num[0] != VCS_SEMANTIC_ORIGIN_V1_SYSTEM ||
        !sss_sys_path(f->text[0], f->text_len[0], l->path, sizeof(l->path)) ||
        !sss_read(l->path, &l->body, &n))
        return true;
    if (n == 0 || strstr(l->body, "include") != NULL) {
        free(l->body);
        l->body = NULL;
    }
    return true;
}

/* A copy of that header in inc/a, the first angled dir, under every tail of
 * its path, so whichever relative name the system header spelled now finds
 * the copy first. A cold parse reads the copy; a reused preamble would not. */
static bool sss_system_shadow(const char *root)
{
    struct sss_leaf l = {0};
    char base[PATH_MAX], rel[PATH_MAX], *m = NULL;
    size_t n = 0;
    bool ok;
    (void)snprintf(base, sizeof(base), "%s/base.cold.bin", root);
    ok = sss_read(base, &m, &n) &&
         vcs_semantic_section_v1_each((const uint8_t *)m, n,
                                      VCS_SEMANTIC_SECTION_V1_FILES,
                                      sss_leaf_cb, &l) &&
         l.body != NULL;
    free(m);
    if (!ok)
        printf("FAIL no leaf system header in %s\n", base);
    for (const char *s = strchr(l.path + 1, '/'); ok && s != NULL;
         s = strchr(s + 1, '/')) {
        (void)snprintf(rel, sizeof(rel), "inc/a/%s", s + 1);
        ok = sss_write(root, rel, l.body);
    }
    free(l.body);
    return ok;
}

static bool sss_body_again(const char *root)
{
    return sss_edit(root, "src/main.c", "p->a - p->b", "p->a * p->b");
}

struct sss_step {
    const char *name;
    bool (*edit)(const char *root);
    bool extra_flag;  /* argv gains -DFX_EXTRA=1 from here on */
    const char *tu;   /* the TU reuse the session must report */
    const char *why;  /* a prefix of its reason ("" when none is required) */
};

static const struct sss_step k_sss_steps[] = {
    {"base", sss_none, false, "created", "first-parse"},
    {"body", sss_body, false, "reparsed", ""},
    {"main-macro", sss_main_macro, false, "reparsed", ""},
    {"header-macro", sss_header_macro, false, "recreated",
     "file-changed inc/b/fx.h"},
    {"header-same-stat", sss_header_same_stat, false, "recreated",
     "file-changed inc/b/fx.h"},
    {"header-layout",sss_layout, false, "recreated", "file-changed inc/b/fx.h"},
    {"shadow-header", sss_shadow, false, "recreated",
     "include-shadow-appeared inc/a/fx.h"},
    {"shadow-beside", sss_shadow_beside, false, "recreated",
     "warm-unusable: lookup-moved fx.h"},
    {"system-shadow", sss_system_shadow, false, "recreated",
     "include-shadow-appeared inc/a/"},
    {"flag", sss_none, true, "recreated", "argv-changed"},
    {"body-after-flag", sss_body_again, true, "reparsed", ""},
};
#define SSS_STEPS (sizeof(k_sss_steps) / sizeof(k_sss_steps[0]))

/* ── the sensor: cold emits and one session process ─────────────────────── */

struct sss_argv {
    const char *items[8];
    size_t n;
};

static void sss_argv(struct sss_argv *a, bool extra)
{
    static const char *const base[] = {"-std=c23", "-Iinc/a", "-Iinc/b",
                                       "-DFX_MODE=1"};
    a->n = 0;
    for (size_t k = 0; k < sizeof(base) / sizeof(base[0]); k++)
        a->items[a->n++] = base[k];
    if (extra)
        a->items[a->n++] = "-DFX_EXTRA=1";
}

static bool sss_cold(const char *sensor, const char *root, const char *out,
                     const struct sss_argv *a)
{
    const char *argv[24];
    char buf[4096];
    bool timed_out = false;
    size_t k = 0;
    int rc;
    const char *head[] = {sensor, "emit", "--root", root, "--source",
                          "src/main.c", "--out", out, "--facts", "--"};
    for (size_t i = 0; i < sizeof(head) / sizeof(head[0]); i++)
        argv[k++] = head[i];
    for (size_t i = 0; i < a->n; i++)
        argv[k++] = a->items[i];
    argv[k] = NULL;
    rc = zcl_spawn_capture_merged_observed(argv, buf, sizeof(buf), 60000,
                                           &timed_out);
    if (rc != 0)
        printf("FAIL cold emit exited %d: %s\n", rc, buf);
    return rc == 0;
}

struct sss_proc {
    pid_t pid;
    int to, from;
    char buf[SSS_REPLY_MAX * 2];
    size_t have;
};

/* The environment for the session: the caller's, minus any inherited fault
 * flag, plus the fault flag when inject is set. Built before fork. */
static char **sss_env(bool inject)
{
    size_t n = 0, w = 0;
    char **env;
    while (environ[n] != NULL)
        n++;
    env = calloc(n + 2, sizeof(char *));
    if (env == NULL)
        return NULL;
    for (size_t k = 0; k < n; k++) {
        if (strncmp(environ[k], SSS_INJECT "=", sizeof(SSS_INJECT)) != 0)
            env[w++] = environ[k];
    }
    if (inject)
        env[w++] = SSS_INJECT "=1";
    return env;
}

static bool sss_start(struct sss_proc *p, const char *sensor, bool verify,
                      bool inject, const char *err_log)
{
    char *argv[] = {(char *)sensor, "session",
                    verify ? "--verify-cold" : NULL, NULL};
    char **env = sss_env(inject);
    int in[2], out[2];
    if (env == NULL || pipe(in) != 0 || pipe(out) != 0) {
        free(env);
        return false;
    }
    p->pid = fork();
    if (p->pid == 0) {
        int fd = open(err_log, O_WRONLY | O_CREAT | O_TRUNC, 0600);
        (void)dup2(in[0], 0);
        (void)dup2(out[1], 1);
        if (fd >= 0)
            (void)dup2(fd, 2);
        (void)close(in[1]);
        (void)close(out[0]);
        execve(sensor, argv, env);
        _exit(127);
    }
    free(env);
    (void)close(in[0]);
    (void)close(out[1]);
    p->to = in[1];
    p->from = out[0];
    p->have = 0;
    return p->pid > 0;
}

static bool sss_write_all(int fd, const char *s, size_t n)
{
    struct sigaction ign = {.sa_handler = SIG_IGN}, old;
    bool ok = true;
    (void)sigaction(SIGPIPE, &ign, &old);
    while (ok && n > 0) {
        ssize_t w = write(fd, s, n);
        ok = w > 0;
        if (ok) {
            s += w;
            n -= (size_t)w;
        }
    }
    (void)sigaction(SIGPIPE, &old, NULL);
    return ok;
}

/* One stdout line of the session, without its newline. */
static bool sss_line(struct sss_proc *p, char *out, size_t cap)
{
    for (;;) {
        char *nl = memchr(p->buf, '\n', p->have);
        struct pollfd pf = {.fd = p->from, .events = POLLIN};
        ssize_t got;
        if (nl != NULL) {
            size_t n = (size_t)(nl - p->buf);
            (void)snprintf(out, cap, "%.*s", (int)n, p->buf);
            memmove(p->buf, nl + 1, p->have - n - 1);
            p->have -= n + 1;
            return true;
        }
        if (p->have == sizeof(p->buf) || poll(&pf, 1, 120000) <= 0)
            return false;
        got = read(p->from, p->buf + p->have, sizeof(p->buf) - p->have);
        if (got <= 0)
            return false;
        p->have += (size_t)got;
    }
}

static bool sss_request(struct sss_proc *p, const char *root, const char *out,
                        const struct sss_argv *a, char *reply, size_t cap)
{
    char line[8192];
    int w = snprintf(line, sizeof(line),
                     "emit\t--root\t%s\t--source\tsrc/main.c\t--out\t%s\t"
                     "--facts\t--",
                     root, out);
    for (size_t k = 0; k < a->n && w > 0 && (size_t)w < sizeof(line); k++)
        w += snprintf(line + w, sizeof(line) - (size_t)w, "\t%s", a->items[k]);
    if (w <= 0 || (size_t)w + 2 > sizeof(line))
        return false;
    line[w++] = '\n';
    return sss_write_all(p->to, line, (size_t)w) && sss_line(p, reply, cap);
}

/* End the session: its summary line, then its exit status. */
static int sss_finish(struct sss_proc *p, char *summary, size_t cap)
{
    int status = -1;
    (void)close(p->to);
    if (!sss_line(p, summary, cap))
        summary[0] = '\0';
    (void)close(p->from);
    if (waitpid(p->pid, &status, 0) != p->pid)
        return -1;
    return WIFEXITED(status) ? WEXITSTATUS(status) : -1;
}

/* A string field of a flat JSON reply. */
static bool sss_field(const char *reply, const char *key, char *out,
                      size_t cap)
{
    char pat[64];
    const char *s, *e;
    (void)snprintf(pat, sizeof(pat), "\"%s\":\"", key);
    s = strstr(reply, pat);
    if (s == NULL)
        return false;
    s += strlen(pat);
    e = strchr(s, '"');
    if (e == NULL)
        return false;
    (void)snprintf(out, cap, "%.*s", (int)(e - s), s);
    return true;
}

static bool sss_is(const char *reply, const char *key, const char *want)
{
    char got[512];
    if (sss_field(reply, key, got, sizeof(got)) && strcmp(got, want) == 0)
        return true;
    printf("FAIL reply %s is not \"%s\": %s\n", key, want, reply);
    return false;
}

static bool sss_starts(const char *reply, const char *key, const char *prefix)
{
    char got[512];
    if (sss_field(reply, key, got, sizeof(got)) &&
        strncmp(got, prefix, strlen(prefix)) == 0)
        return true;
    printf("FAIL reply %s does not start \"%s\": %s\n", key, prefix, reply);
    return false;
}

static bool sss_same(const char *x, const char *y)
{
    char *a = NULL, *b = NULL;
    size_t an = 0, bn = 0;
    bool same = sss_read(x, &a, &an) && sss_read(y, &b, &bn) && an == bn &&
                memcmp(a, b, an) == 0;
    free(a);
    free(b);
    if (!same)
        printf("FAIL %s and %s differ\n", x, y);
    return same;
}

/* ── the cases ────────────────────────────────────────────────────────────── */

struct sss_ctx {
    char sensor[PATH_MAX];
    char dir[1024];
    char root[1100];
};

static bool sss_fresh(struct sss_ctx *c, const char *name)
{
    (void)snprintf(c->root, sizeof(c->root), "%s/%s", c->dir, name);
    (void)test_rm_rf_recursive(c->root);
    return mkdir(c->root, 0700) == 0 && sss_tree(c->root);
}

/* Emit step k through the session, then cold; the two files must match.
 * tu and why override the step's expectation when not NULL. */
static bool sss_step_as(struct sss_ctx *c, struct sss_proc *p, size_t k,
                        const char *tu, const char *why, char *reply,
                        size_t cap)
{
    const struct sss_step *s = &k_sss_steps[k];
    char warm[PATH_MAX], cold[PATH_MAX];
    struct sss_argv a;
    sss_argv(&a, s->extra_flag);
    (void)snprintf(warm, sizeof(warm), "%s/%s.session.bin", c->root, s->name);
    (void)snprintf(cold, sizeof(cold), "%s/%s.cold.bin", c->root, s->name);
    if (!s->edit(c->root) || !sss_request(p, c->root, warm, &a, reply, cap)) {
        printf("FAIL step %s: no session reply\n", s->name);
        return false;
    }
    tu = tu != NULL ? tu : s->tu;
    why = why != NULL ? why : s->why;
    return sss_is(reply, "tu", tu) &&
           (why[0] == '\0' || sss_starts(reply, "reason", why)) &&
           sss_cold(c->sensor, c->root, cold, &a) && sss_same(warm, cold);
}

static bool sss_step(struct sss_ctx *c, struct sss_proc *p, size_t k,
                     char *reply, size_t cap)
{
    return sss_step_as(c, p, k, NULL, NULL, reply, cap);
}

static int sss_t_verified(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX];
    bool started = false;
    TEST_CASE("semantic_sensor: session --verify-cold equals cold after body, "
              "macro, layout, shadow and flag edits") {
        ASSERT(sss_fresh(c, "verified"));
        (void)snprintf(log, sizeof(log), "%s/session.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, true, false, log));
        started = true;
        for (size_t k = 0; k < SSS_STEPS; k++) {
            ASSERT(sss_step(c, &p, k, reply, sizeof(reply)));
            ASSERT(sss_is(reply, "verify", "equal"));
            ASSERT(sss_is(reply, "written", "cold"));
        }
        started = false;
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 0);
        ASSERT(strstr(reply, "\"mismatches\":0,") != NULL);
        ASSERT(strstr(reply, "\"reparsed\":3,") != NULL);
        ASSERT(strstr(reply, "\"recreated\":7}") != NULL);
    } TEST_END
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

/* The default mode: the first emit is verified, a qualified reparse writes
 * the warm bytes unverified, and they still equal a cold process's. */
static int sss_t_qualified(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX];
    bool started = false;
    TEST_CASE("semantic_sensor: a qualified warm reparse writes warm bytes "
              "equal to cold") {
        ASSERT(sss_fresh(c, "qualified"));
        (void)snprintf(log, sizeof(log), "%s/qualified.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, false, false, log));
        started = true;
        ASSERT(sss_step(c, &p, 0, reply, sizeof(reply)));
        ASSERT(sss_is(reply, "verify", "equal"));
        ASSERT(sss_step(c, &p, 1, reply, sizeof(reply)));
        ASSERT(sss_is(reply, "written", "warm"));
        ASSERT(sss_is(reply, "verify", "skipped"));
        /* A verified TU, then a shadow of an include made inside a system
         * header: only the shadow candidates can see it. Unseen, the warm
         * bytes written here would differ from the cold ones. */
        ASSERT(sss_step(c, &p, 8, reply, sizeof(reply)));
        ASSERT(sss_is(reply, "verify", "equal"));
        ASSERT(sss_step(c, &p, 2, reply, sizeof(reply)));
        ASSERT(sss_is(reply, "written", "warm"));
        ASSERT(sss_step(c, &p, 3, reply, sizeof(reply)));
        ASSERT(sss_is(reply, "verify", "equal"));
        started = false;
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 0);
        ASSERT(strstr(reply, "\"warm_written\":2,") != NULL);
    } TEST_END
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

static int sss_t_injected(struct sss_ctx *c)
{
    int failures = 0;
    struct sss_proc p = {0};
    char reply[SSS_REPLY_MAX], log[PATH_MAX];
    bool started = false;
    char sections[256];
    TEST_CASE("semantic_sensor: a forced warm mismatch disables reuse and "
              "never writes the warm bytes") {
        ASSERT(sss_fresh(c, "injected"));
        (void)snprintf(log, sizeof(log), "%s/injected.err", c->dir);
        ASSERT(sss_start(&p, c->sensor, false, true, log));
        started = true;
        /* The corrupted warm bytes differ from cold, so a written warm
         * manifest would fail sss_same inside sss_step. */
        ASSERT(sss_step(c, &p, 0, reply, sizeof(reply)));
        ASSERT(sss_is(reply, "verify", "mismatch"));
        ASSERT(sss_is(reply, "written", "cold"));
        ASSERT(sss_field(reply, "sections", sections, sizeof(sections)) &&
               sections[0] != '\0');
        for (size_t k = 1; k < 3; k++) {
            ASSERT(sss_step_as(c, &p, k, "none", "warm-disabled", reply,
                               sizeof(reply)));
            ASSERT(sss_is(reply, "written", "cold"));
            ASSERT(sss_is(reply, "verify", "skipped"));
        }
        started = false;
        ASSERT_EQ(sss_finish(&p, reply, sizeof(reply)), 0);
        ASSERT(strstr(reply, "\"warm_written\":0,") != NULL);
        ASSERT(strstr(reply, "\"mismatches\":1,") != NULL);
    } TEST_END
    if (started)
        (void)sss_finish(&p, reply, sizeof(reply));
    return failures;
}

int semantic_sensor_session_cases(void)
{
    int failures = 0;
    struct sss_ctx c = {0};
    if (realpath(SSS_SENSOR, c.sensor) == NULL ||
        test_mkdtemp(c.dir, sizeof(c.dir), "semsensor_session") == NULL) {
        printf("FAIL semantic_sensor session: no sensor path or temp dir\n");
        return 1;
    }
    failures += sss_t_verified(&c);
    failures += sss_t_qualified(&c);
    failures += sss_t_injected(&c);
    (void)test_rm_rf_recursive(c.dir);
    return failures;
}
