/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * Purpose: strict-C23 Windows acceptance for the canonical semantic
 * manifest reader (contexts/commons/modules/vcs/src/semantic_manifest*.c,
 * docs/work/SEMANTIC_MANIFEST.md). It:
 *
 *   1. builds the golden vector from the doc with the public builder API
 *      and pins its exact length, root and hint root -- the same constants
 *      tests/harness/src/test_semantic_manifest.c pins (SMT_GOLDEN_*);
 *   2. strict-decodes every checked-in fixture under
 *      tests/fixtures/semantic_manifest/ (*.bin) and
 *      tests/fixtures/semantic_facts/ (*.zsm), embedded at compile time
 *      (semantic_manifest_windows_fixtures.h) so this program needs no
 *      runtime file access, prints each one's exact root and hint root,
 *      and folds all of them into one pinned SHA3 ledger digest;
 *   3. checks the decoder's refusals: truncation, magic, section order, an
 *      absolute path, a `..` component and a trailing byte.
 *
 * This program calls no Windows API: the logic is plain, portable C23. It
 * is still gated on `#if defined(_WIN32)`, like every other program under
 * tests/harness/src named "*_windows_acceptance.c" (this directory is swept into the
 * native test_parallel_fast monolith off Windows too, and an unguarded
 * main() here would collide with test_parallel.c's), so off Windows it
 * compiles to an empty translation unit and contributes nothing to that
 * link. The other half of the cross-platform proof is
 * tests/harness/src/test_semantic_manifest.c (smt_t_ledger): it computes
 * the identical ledger digest over the identical fixture files, read live
 * from disk instead of embedded, and both pin SMT_LEDGER_DIGEST /
 * SMWA_LEDGER_DIGEST to the same bytes. Equal bytes out of two independent
 * readings (one embedded and cross-linked for Windows, one live off disk,
 * natively executed, on Linux) is the evidence that the reader's output
 * does not depend on the platform it runs on. Native Windows execution of
 * the cross-linked .exe is NOT observed here -- there is no Windows
 * runtime or Wine in this environment; that gap is reported by
 * windows-portability-acceptance and by the caller of this catalog entry,
 * never silently assumed closed.
 *
 * Do not edit this file to make the implementation pass.
 */
#if defined(_WIN32)

#include "vcs/semantic_manifest.h"

#include "semantic_manifest_windows_fixtures.h"

#include "sha3/sha3.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ── shared golden vector (docs/work/SEMANTIC_MANIFEST.md) ───────────────
 * Byte-for-byte the same records as
 * tests/harness/src/test_semantic_manifest.c smt_golden_*(); a change to
 * either without the other is caught because the pinned constants below
 * would then disagree. */

#define SMWA_GOLDEN_LEN 775u
#define SMWA_GOLDEN_ROOT \
    "7ece87deea7ec79254851b5e02eef5f01ecc49829958ef22514208d026c6bb77"
#define SMWA_GOLDEN_HINT \
    "5b3caf953603b4c347bd0423e2d52a079d8b8c8b17d4fb22192a7b40a388baf6"

/* SHA3-256("zcl.semantic_manifest_windows_ledger.v1" || sorted "name root
 * hint" lines), one line per replayed fixture (see smwa_ledger below). The
 * Linux-native run (test_semantic_manifest.c smt_t_ledger) must produce the
 * identical digest over the identical fixture files read from disk. */
#define SMWA_LEDGER_DIGEST \
    "410a13f3370324250f7320d10113c87c75ce15d72289aa3e39340ea6222ba231"

static int g_failures;

static void smwa_fail(const char *what)
{
    fprintf(stderr, "semantic_manifest_windows_acceptance: FAIL: %s\n", what);
    g_failures++;
}

static void smwa_hex(const uint8_t *d, size_t n, char *out)
{
    static const char hx[] = "0123456789abcdef";
    for (size_t k = 0; k < n; k++) {
        out[2 * k] = hx[d[k] >> 4];
        out[2 * k + 1] = hx[d[k] & 15];
    }
    out[2 * n] = '\0';
}

/* ---- golden vector builder (matches test_semantic_manifest.c exactly) -- */

static void smwa_rec_texts(struct vcs_semantic_record_v1 *r,
                           const char *const *items, size_t n)
{
    vcs_semantic_record_v1_u32(r, (uint32_t)n);
    for (size_t k = 0; k < n; k++)
        vcs_semantic_record_v1_cstr(r, items[k]);
}

static bool smwa_golden_identity(struct vcs_semantic_builder_v1 *b,
                                 struct vcs_semantic_record_v1 *r)
{
    static const char *const argv[] = {"-std=c23", "-I@root/inc"};
    static const char *const angled[] = {"inc", "@sys/usr/include"};
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "golden-cc 1.0");
    vcs_semantic_record_v1_cstr(r, "");
    vcs_semantic_record_v1_cstr(r, "x86_64-pc-linux-gnu");
    vcs_semantic_record_v1_cstr(r, "src/a.c");
    smwa_rec_texts(r, argv, 2);
    smwa_rec_texts(r, NULL, 0);
    smwa_rec_texts(r, angled, 2);
    smwa_rec_texts(r, NULL, 0);
    vcs_semantic_record_v1_u32(r, 2);
    vcs_semantic_record_v1_cstr(r, "CPATH");
    vcs_semantic_record_v1_u8(r, 0);
    vcs_semantic_record_v1_cstr(r, "");
    vcs_semantic_record_v1_cstr(r, "C_INCLUDE_PATH");
    vcs_semantic_record_v1_u8(r, 0);
    vcs_semantic_record_v1_cstr(r, "");
    return vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_IDENTITY, r);
}

static bool smwa_golden_file(struct vcs_semantic_builder_v1 *b,
                             struct vcs_semantic_record_v1 *r,
                             const char *path, const char *body,
                             uint8_t origin)
{
    uint8_t d[32];
    zcl_sha3_256((const unsigned char *)body, strlen(body), d);
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, path);
    vcs_semantic_record_v1_digest(r, d);
    vcs_semantic_record_v1_u8(r, origin);
    return vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_FILES, r);
}

static bool smwa_golden_lookup_macro_decl(struct vcs_semantic_builder_v1 *b,
                                          struct vcs_semantic_record_v1 *r)
{
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "src/a.c");
    vcs_semantic_record_v1_cstr(r, "a.h");
    vcs_semantic_record_v1_u8(r, VCS_SEMANTIC_FORM_V1_QUOTED);
    vcs_semantic_record_v1_u8(r, VCS_SEMANTIC_LOOKUP_V1_INCLUDE);
    vcs_semantic_record_v1_cstr(r, "inc/a.h");
    vcs_semantic_record_v1_u32(r, 1);
    vcs_semantic_record_v1_u8(r, VCS_SEMANTIC_MISS_V1_DERIVED_STAT);
    vcs_semantic_record_v1_u32(r, 0);
    if (!vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_LOOKUPS, r))
        return false;
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "inc/a.h");
    vcs_semantic_record_v1_cstr(r, "A_MAX");
    vcs_semantic_record_v1_u8(r, 0);
    vcs_semantic_record_v1_cstr(r, "16");
    vcs_semantic_record_v1_u8(r, 1);
    if (!vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_MACROS, r))
        return false;
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "src/a.c");
    vcs_semantic_record_v1_cstr(r, "function");
    vcs_semantic_record_v1_cstr(r, "f");
    vcs_semantic_record_v1_cstr(r, "int (void)");
    vcs_semantic_record_v1_u8(r, 4);
    return vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_DECLS, r);
}

static bool smwa_golden_layout_enum(struct vcs_semantic_builder_v1 *b,
                                    struct vcs_semantic_record_v1 *r)
{
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "inc/a.h");
    vcs_semantic_record_v1_cstr(r, "pair");
    vcs_semantic_record_v1_u8(r, 1);
    vcs_semantic_record_v1_u64(r, 8);
    vcs_semantic_record_v1_u64(r, 4);
    vcs_semantic_record_v1_u32(r, 2);
    vcs_semantic_record_v1_cstr(r, "x");
    vcs_semantic_record_v1_u64(r, 0);
    vcs_semantic_record_v1_u32(r, UINT32_MAX);
    vcs_semantic_record_v1_cstr(r, "int");
    vcs_semantic_record_v1_cstr(r, "y");
    vcs_semantic_record_v1_u64(r, 32);
    vcs_semantic_record_v1_u32(r, UINT32_MAX);
    vcs_semantic_record_v1_cstr(r, "int");
    if (!vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_LAYOUTS, r))
        return false;
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "inc/a.h");
    vcs_semantic_record_v1_cstr(r, "mode");
    vcs_semantic_record_v1_cstr(r, "MODE_ON");
    vcs_semantic_record_v1_i64(r, -1);
    return vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_ENUMS, r);
}

static bool smwa_golden_function(struct vcs_semantic_builder_v1 *b,
                                 struct vcs_semantic_record_v1 *r)
{
    static const char *const toks[] = {"int", "f", "(", "void", ")", "{",
                                       "return", "A_MAX", ";", "}"};
    static const char *const callees[] = {"g", "(indirect)"};
    static const char *const macros[] = {"A_MAX"};
    struct vcs_semantic_token_hash_v1 h;
    uint8_t d[32];
    vcs_semantic_token_hash_v1_init(&h);
    for (size_t k = 0; k < sizeof(toks) / sizeof(toks[0]); k++)
        vcs_semantic_token_hash_v1_add(&h, toks[k], strlen(toks[k]));
    vcs_semantic_token_hash_v1_final(&h, d);
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "src/a.c");
    vcs_semantic_record_v1_cstr(r, "f");
    vcs_semantic_record_v1_u8(r, 4);
    vcs_semantic_record_v1_cstr(r, "int (void)");
    vcs_semantic_record_v1_digest(r, d);
    vcs_semantic_record_v1_sorted_texts(r, callees, 2);
    vcs_semantic_record_v1_sorted_texts(r, macros, 1);
    if (!vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_FUNCTIONS, r))
        return false;
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "src/a.c");
    vcs_semantic_record_v1_cstr(r, "f");
    vcs_semantic_record_v1_u32(r, 2);
    vcs_semantic_record_v1_u32(r, 2);
    vcs_semantic_record_v1_u64(r, 18);
    vcs_semantic_record_v1_u64(r, 46);
    return vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_SPANS, r);
}

static bool smwa_golden(uint8_t **out, size_t *len)
{
    struct vcs_semantic_builder_v1 *b = vcs_semantic_builder_v1_new();
    struct vcs_semantic_record_v1 r = {0};
    char why[256];
    bool ok = b != NULL &&
             smwa_golden_identity(b, &r) && smwa_golden_function(b, &r) &&
             smwa_golden_layout_enum(b, &r) &&
             smwa_golden_file(b, &r, "inc/a.h", "#define A_MAX 16\n",
                              VCS_SEMANTIC_ORIGIN_V1_REPO) &&
             smwa_golden_file(b, &r, "src/a.c",
                              "#include \"a.h\"\nint f(void) { return A_MAX; }\n",
                              VCS_SEMANTIC_ORIGIN_V1_MAIN) &&
             smwa_golden_lookup_macro_decl(b, &r);
    ok = ok && vcs_semantic_builder_v1_finish(b, out, len, why, sizeof(why));
    if (!ok)
        fprintf(stderr,
                "semantic_manifest_windows_acceptance: golden build refused: %s\n",
                why);
    vcs_semantic_record_v1_free(&r);
    vcs_semantic_builder_v1_free(b);
    return ok;
}

static void smwa_check_golden(void)
{
    uint8_t *bytes = NULL;
    size_t len = 0;
    char why[256];
    uint8_t root[32], hint[32];
    char root_hex[65], hint_hex[65];

    if (!smwa_golden(&bytes, &len)) {
        smwa_fail("golden vector build");
        return;
    }
    if (len != SMWA_GOLDEN_LEN) {
        fprintf(stderr,
                "semantic_manifest_windows_acceptance: FAIL: golden length "
                "%zu != %u\n",
                len, SMWA_GOLDEN_LEN);
        g_failures++;
    }
    if (!vcs_semantic_root_v1(bytes, len, root, why, sizeof(why))) {
        smwa_fail("golden root");
    } else {
        smwa_hex(root, 32, root_hex);
        if (strcmp(root_hex, SMWA_GOLDEN_ROOT) != 0) {
            fprintf(stderr,
                    "semantic_manifest_windows_acceptance: FAIL: golden root "
                    "%s != %s\n",
                    root_hex, SMWA_GOLDEN_ROOT);
            g_failures++;
        }
    }
    if (!vcs_semantic_hint_root_v1(bytes, len, hint, why, sizeof(why))) {
        smwa_fail("golden hint root");
    } else {
        smwa_hex(hint, 32, hint_hex);
        if (strcmp(hint_hex, SMWA_GOLDEN_HINT) != 0) {
            fprintf(stderr,
                    "semantic_manifest_windows_acceptance: FAIL: golden hint "
                    "%s != %s\n",
                    hint_hex, SMWA_GOLDEN_HINT);
            g_failures++;
        }
    }
    printf("semantic_manifest_windows_acceptance: golden len=%zu root=%s "
           "hint=%s\n",
           len, root_hex, hint_hex);
    free(bytes);
}

/* ---- fixture replay and ledger ----------------------------------------- */

struct smwa_ledger_row {
    char name[96];
    char line[228]; /* "name root hint\n" */
};

static int smwa_row_cmp(const void *a, const void *b)
{
    const struct smwa_ledger_row *ra = a;
    const struct smwa_ledger_row *rb = b;
    return strcmp(ra->name, rb->name);
}

static void smwa_check_fixtures(void)
{
    struct smwa_ledger_row rows[SMWF_FIXTURE_COUNT];
    size_t n = 0;
    for (size_t i = 0; i < SMWF_FIXTURE_COUNT; i++) {
        const struct smwf_fixture *fx = &smwf_fixtures[i];
        char why[256];
        uint8_t root[32], hint[32];
        char root_hex[65], hint_hex[65];
        if (!vcs_semantic_manifest_v1_validate(fx->data, fx->len, why,
                                               sizeof(why))) {
            fprintf(stderr,
                    "semantic_manifest_windows_acceptance: FAIL: fixture %s "
                    "did not validate: %s\n",
                    fx->name, why);
            g_failures++;
            continue;
        }
        if (!vcs_semantic_root_v1(fx->data, fx->len, root, why, sizeof(why)) ||
            !vcs_semantic_hint_root_v1(fx->data, fx->len, hint, why,
                                       sizeof(why))) {
            fprintf(stderr,
                    "semantic_manifest_windows_acceptance: FAIL: fixture %s "
                    "root/hint: %s\n",
                    fx->name, why);
            g_failures++;
            continue;
        }
        smwa_hex(root, 32, root_hex);
        smwa_hex(hint, 32, hint_hex);
        printf("semantic_manifest_windows_acceptance: fixture %s root=%s "
               "hint=%s\n",
               fx->name, root_hex, hint_hex);
        (void)snprintf(rows[n].name, sizeof(rows[n].name), "%s", fx->name);
        (void)snprintf(rows[n].line, sizeof(rows[n].line), "%s %s %s\n",
                       fx->name, root_hex, hint_hex);
        n++;
    }
    qsort(rows, n, sizeof(rows[0]), smwa_row_cmp);

    char *joined = malloc(n * sizeof(rows[0].line) + 1); // raw-alloc-ok:acceptance-scratch
    size_t joined_len = 0;
    if (joined == NULL) {
        smwa_fail("ledger scratch allocation");
        return;
    }
    for (size_t i = 0; i < n; i++) {
        size_t l = strlen(rows[i].line);
        memcpy(joined + joined_len, rows[i].line, l);
        joined_len += l;
    }

    static const char domain[] = "zcl.semantic_manifest_windows_ledger.v1";
    size_t dlen = strlen(domain);
    uint8_t *preimage = malloc(dlen + joined_len); // raw-alloc-ok:acceptance-scratch
    if (preimage == NULL) {
        free(joined);
        smwa_fail("ledger preimage allocation");
        return;
    }
    memcpy(preimage, domain, dlen);
    memcpy(preimage + dlen, joined, joined_len);
    uint8_t digest[32];
    zcl_sha3_256(preimage, dlen + joined_len, digest);
    free(preimage);
    free(joined);

    char digest_hex[65];
    smwa_hex(digest, 32, digest_hex);
    printf("semantic_manifest_windows_acceptance: fixtures=%zu ledger=%s\n",
           n, digest_hex);
    if (n != SMWF_FIXTURE_COUNT) {
        fprintf(stderr,
                "semantic_manifest_windows_acceptance: FAIL: %zu of %zu "
                "fixtures decoded\n",
                n, (size_t)SMWF_FIXTURE_COUNT);
        g_failures++;
    }
    if (strcmp(digest_hex, SMWA_LEDGER_DIGEST) != 0) {
        fprintf(stderr,
                "semantic_manifest_windows_acceptance: FAIL: ledger digest "
                "%s != pinned %s\n",
                digest_hex, SMWA_LEDGER_DIGEST);
        g_failures++;
    }
}

/* ---- decoder refusals (docs/work/SEMANTIC_MANIFEST.md refusal set) ----- */

static bool smwa_refused(const uint8_t *m, size_t n)
{
    char why[256];
    uint8_t root[32];
    return !vcs_semantic_root_v1(m, n, root, why, sizeof(why));
}

/* Portable byte-substring search (the glibc-specific memmem is avoided
 * repo-wide; see tests/harness/src/test_wallet_keystore.c). */
static uint8_t *smwa_find(uint8_t *hay, size_t haylen, const char *needle,
                          size_t needlelen)
{
    if (needlelen == 0 || needlelen > haylen)
        return NULL;
    for (size_t i = 0; i + needlelen <= haylen; i++) {
        if (memcmp(hay + i, needle, needlelen) == 0)
            return hay + i;
    }
    return NULL;
}

static bool smwa_refused_patch(const uint8_t *m, size_t n, const char *from,
                               const char *to)
{
    uint8_t *c = malloc(n); // raw-alloc-ok:acceptance-scratch
    bool refused;
    size_t flen = strlen(from), tlen = strlen(to);
    uint8_t *hit;
    if (c == NULL || flen != tlen)
        return false;
    memcpy(c, m, n);
    hit = smwa_find(c, n, from, flen);
    if (hit == NULL) {
        free(c);
        return false;
    }
    memcpy(hit, to, tlen);
    refused = smwa_refused(c, n);
    free(c);
    return refused;
}

static bool smwa_refused_byte(const uint8_t *m, size_t n, size_t at,
                              uint8_t v)
{
    uint8_t *c = malloc(n); // raw-alloc-ok:acceptance-scratch
    bool refused;
    if (c == NULL || at >= n)
        return false;
    memcpy(c, m, n);
    c[at] = v;
    refused = smwa_refused(c, n);
    free(c);
    return refused;
}

static void smwa_expect(bool value, const char *name)
{
    if (!value) {
        fprintf(stderr,
                "semantic_manifest_windows_acceptance: FAIL: refusal not "
                "raised: %s\n",
                name);
        g_failures++;
    }
}

static void smwa_check_refusals(void)
{
    uint8_t *m = NULL;
    size_t n = 0;
    uint8_t *c;
    size_t magic;

    if (!smwa_golden(&m, &n)) {
        smwa_fail("refusal fixture build");
        return;
    }
    magic = strlen(VCS_SEMANTIC_MANIFEST_V1_MAGIC);

    smwa_expect(smwa_refused(m, n - 1), "truncated");
    smwa_expect(smwa_refused(m, 0), "empty");
    smwa_expect(smwa_refused_byte(m, n, 0, 'Z'), "magic");
    smwa_expect(smwa_refused_byte(m, n, magic, 2), "section order");
    smwa_expect(smwa_refused_patch(m, n, "src/a.c", "/rc/a.c"),
               "absolute path");
    smwa_expect(smwa_refused_patch(m, n, "inc/a.h", "../a.hh"), "dot-dot");

    c = malloc(n + 1); // raw-alloc-ok:acceptance-scratch
    if (c == NULL) {
        smwa_fail("trailing-byte scratch allocation");
    } else {
        memcpy(c, m, n);
        c[n] = 0;
        smwa_expect(smwa_refused(c, n + 1), "trailing byte");
        free(c);
    }
    printf("semantic_manifest_windows_acceptance: refusals PASS\n");
    free(m);
}

int main(void)
{
    smwa_check_golden();
    smwa_check_fixtures();
    smwa_check_refusals();
    if (g_failures != 0) {
        fprintf(stderr,
                "semantic_manifest_windows_acceptance: FAIL (%d)\n",
                g_failures);
        return 1;
    }
    printf("semantic_manifest_windows_acceptance: PASS\n");
    return 0;
}

#else
typedef int semantic_manifest_windows_acceptance_not_built;
#endif
