/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ACCEPTANCE BAR for the semantic manifest v1 (contexts/commons/modules/vcs/
 * src/semantic_manifest*.c) and the optional libclang sensor that emits it
 * (tools/sensors/, build/bin/z23-clang-manifest).
 *
 * Two groups share one fixture tree and one table of adversarial seeds:
 *
 *   semantic_manifest  needs no libclang. It pins a hand-built golden vector
 *                      (exact bytes, exact root, hint root), proves the
 *                      builder canonicalizes and the decoder refuses every
 *                      non-canonical shape, and replays the seed table over
 *                      the manifests checked in under
 *                      tests/fixtures/semantic_manifest/ (emitted by the
 *                      sensor with ZCL_SEMANTIC_FIXTURE_OUT set).
 *   semantic_sensor    runs the real sensor. It self-skips, visibly, when
 *                      build/bin/z23-clang-manifest is absent. It proves the
 *                      same semantic inputs give the identical root before and
 *                      after `git commit` and at two different absolute roots,
 *                      and that every seed changes the root, the hint root,
 *                      and exactly the named sections. Its warm-session cases
 *                      live in semantic_sensor_session.c.
 *
 * Do not edit this file to make the implementation pass.
 */

#include "test/test_core.h"
#include "test/semantic_sensor_session.h"

#include "util/spawn.h"
#include "vcs/semantic_manifest.h"

#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>

#include "sha3/sha3.h"

#define SMT_SENSOR "build/bin/z23-clang-manifest"
#define SMT_FIXTURES "tests/fixtures/semantic_manifest"
#define SMT_FACTS_FIXTURES "tests/fixtures/semantic_facts"
#define SMT_BIT(s) (1u << VCS_SEMANTIC_SECTION_V1_##s)
#define SMT_ALL 0x3feu

/* ── the fixture tree ─────────────────────────────────────────────────── */

static const char k_smt_shape_h[] =
    "#ifndef SHAPE_H\n"
    "#define SHAPE_H\n"
    "#include <stddef.h>\n"
    "#define SHAPE_SCALE(x) ((x) * 2)\n"
    "#define SHAPE_MAX 16\n"
    "typedef struct { int w; int h; } shape_dim;\n"
    "struct shape {\n"
    "    int kind;\n"
    "    shape_dim dim;\n"
    "    union { long a; char b; };\n"
    "    unsigned flag : 3;\n"
    "};\n"
    "enum shape_kind { SHAPE_NONE = 0, SHAPE_BOX = 4 };\n"
    "static inline int shape_area(const struct shape *s) { return s->dim.w * s->dim.h; }\n"
    "#endif\n";

static const char k_smt_main_c[] =
    "#include \"shape.h\"\n"
    "#include \"other.h\"\n"
    "#if __has_include(<smt_absent_header.h>)\n"
    "#error unexpected\n"
    "#endif\n"
    "static int helper(int v) { return SHAPE_SCALE(v) + SHAPE_MAX; }\n"
    "int run(struct shape *s) {\n"
    "    s->kind = OTHER_KIND;\n"
    "    return helper(shape_area(s));\n"
    "}\n";

static const char k_smt_other_h[] = "#define OTHER_KIND 3\n";

/* ── adversarial seeds ─────────────────────────────────────────────────── */

enum smt_seed_id {
    SMT_HEADER_DECL, SMT_FLAG_DEFINE, SMT_FLAG_OPT, SMT_FLAG_REORDER,
    SMT_MACRO_BODY, SMT_LAYOUT_ADD, SMT_LAYOUT_REORDER, SMT_SHADOW,
    SMT_FN_BODY, SMT_COMMENT, SMT_SEED_COUNT
};

struct smt_seed {
    const char *name;
    uint32_t sections; /* exactly the sections that must change */
    bool hint_equal;
    uint32_t fn_changed;
    const char *fn_name; /* the one changed function, when fn_changed == 1 */
};

static const struct smt_seed k_smt_seeds[SMT_SEED_COUNT] = {
    [SMT_HEADER_DECL] = {"header_decl", SMT_BIT(FILES) | SMT_BIT(DECLS), false, 0, NULL},
    [SMT_FLAG_DEFINE] = {"flag_define", SMT_BIT(IDENTITY), false, 0, NULL},
    [SMT_FLAG_OPT] = {"flag_opt", SMT_BIT(IDENTITY), false, 0, NULL},
    [SMT_FLAG_REORDER] = {"flag_reorder", SMT_BIT(IDENTITY), false, 0, NULL},
    [SMT_MACRO_BODY] = {"macro_body", SMT_BIT(FILES) | SMT_BIT(MACROS), false, 0, NULL},
    [SMT_LAYOUT_ADD] = {"layout_add",
                        SMT_BIT(FILES) | SMT_BIT(LAYOUTS) | SMT_BIT(SPANS), false, 0, NULL},
    [SMT_LAYOUT_REORDER] = {"layout_reorder", SMT_BIT(FILES) | SMT_BIT(LAYOUTS), false, 0, NULL},
    /* A copy of shape.h in the earlier search dir moves every record that
     * names the header's path; the lookup is what explains why. */
    [SMT_SHADOW] = {"shadow_header", SMT_ALL & ~SMT_BIT(IDENTITY), false, 0, NULL},
    [SMT_FN_BODY] = {"fn_body", SMT_BIT(FILES) | SMT_BIT(FUNCTIONS), false, 1, "helper"},
    /* The structure value: only content bytes and positions move. */
    [SMT_COMMENT] = {"comment_only", SMT_BIT(FILES) | SMT_BIT(SPANS), true, 0, NULL},
};

/* ── small file helpers ─────────────────────────────────────────────────── */

static bool smt_mkdirs(const char *root, const char *rel)
{
    char path[PATH_MAX];
    int w = snprintf(path, sizeof(path), "%s/%s", root, rel);
    if (w < 0 || (size_t)w >= sizeof(path))
        return false;
    for (char *p = path + strlen(root) + 1; *p != '\0'; p++) {
        if (*p != '/')
            continue;
        *p = '\0';
        if (mkdir(path, 0700) != 0 && errno != EEXIST)
            return false;
        *p = '/';
    }
    return true;
}

static bool smt_write(const char *root, const char *rel, const char *body)
{
    char path[PATH_MAX];
    FILE *fp;
    bool ok;
    if (!smt_mkdirs(root, rel))
        return false;
    (void)snprintf(path, sizeof(path), "%s/%s", root, rel);
    fp = fopen(path, "wb");
    if (fp == NULL)
        return false;
    ok = fwrite(body, 1, strlen(body), fp) == strlen(body);
    return fclose(fp) == 0 && ok;
}

static bool smt_read(const char *path, uint8_t **out, size_t *len)
{
    FILE *fp = fopen(path, "rb");
    long size;
    bool ok = false;
    *out = NULL;
    *len = 0;
    if (fp == NULL)
        return false;
    if (fseek(fp, 0, SEEK_END) == 0 && (size = ftell(fp)) > 0 &&
        fseek(fp, 0, SEEK_SET) == 0) {
        *out = malloc((size_t)size); // raw-alloc-ok:test-fixture-read
        ok = *out != NULL && fread(*out, 1, (size_t)size, fp) == (size_t)size;
        *len = (size_t)size;
    }
    (void)fclose(fp);
    return ok;
}

static bool smt_write_tree(const char *root)
{
    return smt_write(root, "inc/b/shape.h", k_smt_shape_h) &&
           smt_write(root, "inc/a/other.h", k_smt_other_h) &&
           smt_write(root, "src/main.c", k_smt_main_c);
}

/* Replace the first occurrence of `from` with `to` in root/rel. */
static bool smt_edit(const char *root, const char *rel, const char *from,
                     const char *to)
{
    char path[PATH_MAX], out[8192];
    uint8_t *b = NULL;
    size_t n = 0;
    const char *hit;
    bool ok = false;
    (void)snprintf(path, sizeof(path), "%s/%s", root, rel);
    if (!smt_read(path, &b, &n) || n + strlen(to) >= sizeof(out))
        goto done;
    memcpy(out, b, n);
    out[n] = '\0';
    hit = strstr(out, from);
    if (hit != NULL) {
        char tail[8192];
        (void)snprintf(tail, sizeof(tail), "%s", hit + strlen(from));
        (void)snprintf(out + (hit - out), sizeof(out) - (size_t)(hit - out),
                       "%s%s", to, tail);
        ok = smt_write(root, rel, out);
    }
done:
    free(b);
    return ok;
}

/* ── the seeds, applied to a fresh copy of the base tree ─────────────────── */

struct smt_argv {
    const char *items[16];
    size_t n;
    char absolute_include[PATH_MAX + 16];
};

static void smt_base_argv(struct smt_argv *a, const char *root)
{
    (void)snprintf(a->absolute_include, sizeof(a->absolute_include),
                   "-I%s/inc/c", root);
    const char *base[] = {"-std=c23", "-O2", "-Iinc/a", "-Iinc/b",
                          a->absolute_include, "-DFOO=1", "-Wall"};
    a->n = sizeof(base) / sizeof(base[0]);
    for (size_t k = 0; k < a->n; k++)
        a->items[k] = base[k];
}

static bool smt_apply_argv(enum smt_seed_id id, struct smt_argv *a)
{
    const char *t;
    switch (id) {
    case SMT_FLAG_DEFINE:
        a->items[a->n++] = "-DEXTRA=1";
        return true;
    case SMT_FLAG_OPT:
        a->items[1] = "-O0";
        return true;
    case SMT_FLAG_REORDER:
        t = a->items[0];
        a->items[0] = a->items[1];
        a->items[1] = t;
        return true;
    default:
        return true;
    }
}

static bool smt_apply_files(enum smt_seed_id id, const char *root)
{
    switch (id) {
    case SMT_HEADER_DECL:
        return smt_edit(root, "inc/b/shape.h", "#endif\n",
                        "int shape_extra(void);\n#endif\n");
    case SMT_MACRO_BODY:
        return smt_edit(root, "inc/b/shape.h", "SHAPE_MAX 16", "SHAPE_MAX 17");
    case SMT_LAYOUT_ADD:
        return smt_edit(root, "inc/b/shape.h", "    unsigned flag : 3;\n",
                        "    unsigned flag : 3;\n    int extra;\n");
    case SMT_LAYOUT_REORDER:
        return smt_edit(root, "inc/b/shape.h",
                        "    int kind;\n    shape_dim dim;\n",
                        "    shape_dim dim;\n    int kind;\n");
    case SMT_SHADOW:
        return smt_write(root, "inc/a/shape.h", k_smt_shape_h);
    case SMT_FN_BODY:
        return smt_edit(root, "src/main.c", "+ SHAPE_MAX", "- SHAPE_MAX");
    case SMT_COMMENT:
        /* Outside AND inside function bodies: libclang's tokenizer keeps
         * comments as tokens, so only the inside edit proves they are
         * dropped from the function token hash. */
        return smt_edit(root, "src/main.c", "static int helper",
                        "/* only a comment moves */\nstatic int helper") &&
               smt_edit(root, "src/main.c", "{ return SHAPE_SCALE",
                        "{ /* inside */ return SHAPE_SCALE") &&
               smt_edit(root, "inc/b/shape.h", "SHAPE_MAX 16",
                        "SHAPE_MAX /* in a macro body */ 16");
    default:
        return true;
    }
}

/* ── expectations shared by both groups ─────────────────────────────────── */

struct smt_fn_seen {
    char name[64];
    uint32_t count;
};

static void smt_fn_cb(void *ctx, enum vcs_semantic_fn_change_v1 change,
                      const char *path, size_t path_len, const char *name,
                      size_t name_len)
{
    struct smt_fn_seen *seen = ctx;
    (void)change;
    (void)path;
    (void)path_len;
    if (seen->count++ == 0 && name_len < sizeof(seen->name)) {
        memcpy(seen->name, name, name_len);
        seen->name[name_len] = '\0';
    }
}

/* 0 when the changed-function report of a diff matches the seed's contract. */
static int smt_check_seed_functions(const struct smt_seed *s,
                                    const struct vcs_semantic_diff_v1 *d,
                                    const struct smt_fn_seen *seen)
{
    if (s->fn_name != NULL &&
        (d->functions_changed != s->fn_changed || strcmp(seen->name, s->fn_name) != 0)) {
        printf("FAIL seed %s: changed functions %u (first %s)\n", s->name,
               d->functions_changed, seen->name);
        return 1;
    }
    if (s->fn_name == NULL && (s->sections & SMT_BIT(FUNCTIONS)) == 0 &&
        seen->count != 0) {
        printf("FAIL seed %s: %u function(s) moved\n", s->name, seen->count);
        return 1;
    }
    return 0;
}

/* 0 when the base->seed pair meets the seed's contract; prints why not. */
static int smt_check_seed(const struct smt_seed *s, const uint8_t *base,
                          size_t base_len, const uint8_t *m, size_t m_len)
{
    struct vcs_semantic_diff_v1 d;
    struct smt_fn_seen seen = {0};
    uint8_t r0[32], r1[32], h0[32], h1[32];
    char why[256];
    if (!vcs_semantic_root_v1(base, base_len, r0, why, sizeof(why)) ||
        !vcs_semantic_root_v1(m, m_len, r1, why, sizeof(why)) ||
        !vcs_semantic_hint_root_v1(base, base_len, h0, why, sizeof(why)) ||
        !vcs_semantic_hint_root_v1(m, m_len, h1, why, sizeof(why)) ||
        !vcs_semantic_manifest_v1_diff(base, base_len, m, m_len, &d, smt_fn_cb, &seen)) {
        printf("FAIL seed %s: invalid manifest: %s\n", s->name, why);
        return 1;
    }
    if (memcmp(r0, r1, 32) == 0 || d.exact_equal) {
        printf("FAIL seed %s: exact root did not change\n", s->name);
        return 1;
    }
    if ((memcmp(h0, h1, 32) == 0) != s->hint_equal || d.hint_equal != s->hint_equal) {
        printf("FAIL seed %s: hint root %s\n", s->name,
               s->hint_equal ? "changed" : "did not change");
        return 1;
    }
    if (d.changed_sections != s->sections) {
        printf("FAIL seed %s: changed sections 0x%x, expected 0x%x\n", s->name,
               d.changed_sections, s->sections);
        return 1;
    }
    return smt_check_seed_functions(s, &d, &seen);
}

/* ── golden vector (hand-built; docs/work/SEMANTIC_MANIFEST.md) ────────── */

/* Pinned values of the vector below. Any byte-format change must change
 * these AND the spec together; a producer that emits these exact records
 * must emit these exact bytes. */
#define SMT_GOLDEN_LEN 775u
#define SMT_GOLDEN_ROOT \
    "7ece87deea7ec79254851b5e02eef5f01ecc49829958ef22514208d026c6bb77"
#define SMT_GOLDEN_HINT \
    "5b3caf953603b4c347bd0423e2d52a079d8b8c8b17d4fb22192a7b40a388baf6"

static void smt_rec_texts(struct vcs_semantic_record_v1 *r,
                          const char *const *items, size_t n)
{
    vcs_semantic_record_v1_u32(r, (uint32_t)n);
    for (size_t k = 0; k < n; k++)
        vcs_semantic_record_v1_cstr(r, items[k]);
}

static bool smt_golden_identity(struct vcs_semantic_builder_v1 *b,
                                struct vcs_semantic_record_v1 *r)
{
    static const char *const argv[] = {"-std=c23", "-I@root/inc"};
    static const char *const angled[] = {"inc", "@sys/usr/include"};
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "golden-cc 1.0");
    vcs_semantic_record_v1_cstr(r, "");
    vcs_semantic_record_v1_cstr(r, "x86_64-pc-linux-gnu");
    vcs_semantic_record_v1_cstr(r, "src/a.c");
    smt_rec_texts(r, argv, 2);
    smt_rec_texts(r, NULL, 0);
    smt_rec_texts(r, angled, 2);
    smt_rec_texts(r, NULL, 0);
    vcs_semantic_record_v1_u32(r, 2);
    vcs_semantic_record_v1_cstr(r, "CPATH");
    vcs_semantic_record_v1_u8(r, 0);
    vcs_semantic_record_v1_cstr(r, "");
    vcs_semantic_record_v1_cstr(r, "C_INCLUDE_PATH");
    vcs_semantic_record_v1_u8(r, 0);
    vcs_semantic_record_v1_cstr(r, "");
    return vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_IDENTITY, r);
}

static bool smt_golden_file(struct vcs_semantic_builder_v1 *b,
                            struct vcs_semantic_record_v1 *r, const char *path,
                            const char *body, uint8_t origin)
{
    uint8_t d[32];
    zcl_sha3_256((const unsigned char *)body, strlen(body), d);
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, path);
    vcs_semantic_record_v1_digest(r, d);
    vcs_semantic_record_v1_u8(r, origin);
    return vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_FILES, r);
}

static bool smt_golden_lookup_macro_decl(struct vcs_semantic_builder_v1 *b,
                                         struct vcs_semantic_record_v1 *r)
{
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "src/a.c");
    vcs_semantic_record_v1_cstr(r, "a.h");
    vcs_semantic_record_v1_u8(r, VCS_SEMANTIC_FORM_V1_QUOTED);
    vcs_semantic_record_v1_u8(r, VCS_SEMANTIC_LOOKUP_V1_INCLUDE);
    vcs_semantic_record_v1_cstr(r, "inc/a.h");
    vcs_semantic_record_v1_u32(r, 1);
    vcs_semantic_record_v1_u8(r, VCS_SEMANTIC_MISS_V1_DERIVED_STAT);
    vcs_semantic_record_v1_u32(r, 0);
    if (!vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_LOOKUPS, r))
        return false;
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "inc/a.h");
    vcs_semantic_record_v1_cstr(r, "A_MAX");
    vcs_semantic_record_v1_u8(r, 0);
    vcs_semantic_record_v1_cstr(r, "16");
    vcs_semantic_record_v1_u8(r, 1);
    if (!vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_MACROS, r))
        return false;
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "src/a.c");
    vcs_semantic_record_v1_cstr(r, "function");
    vcs_semantic_record_v1_cstr(r, "f");
    vcs_semantic_record_v1_cstr(r, "int (void)");
    vcs_semantic_record_v1_u8(r, 4);
    return vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_DECLS, r);
}

static bool smt_golden_layout_enum(struct vcs_semantic_builder_v1 *b,
                                   struct vcs_semantic_record_v1 *r)
{
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "inc/a.h");
    vcs_semantic_record_v1_cstr(r, "pair");
    vcs_semantic_record_v1_u8(r, 1);
    vcs_semantic_record_v1_u64(r, 8);
    vcs_semantic_record_v1_u64(r, 4);
    vcs_semantic_record_v1_u32(r, 2);
    vcs_semantic_record_v1_cstr(r, "x");
    vcs_semantic_record_v1_u64(r, 0);
    vcs_semantic_record_v1_u32(r, UINT32_MAX);
    vcs_semantic_record_v1_cstr(r, "int");
    vcs_semantic_record_v1_cstr(r, "y");
    vcs_semantic_record_v1_u64(r, 32);
    vcs_semantic_record_v1_u32(r, UINT32_MAX);
    vcs_semantic_record_v1_cstr(r, "int");
    if (!vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_LAYOUTS, r))
        return false;
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "inc/a.h");
    vcs_semantic_record_v1_cstr(r, "mode");
    vcs_semantic_record_v1_cstr(r, "MODE_ON");
    vcs_semantic_record_v1_i64(r, -1);
    return vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_ENUMS, r);
}

static bool smt_golden_function(struct vcs_semantic_builder_v1 *b,
                                struct vcs_semantic_record_v1 *r)
{
    static const char *const toks[] = {"int", "f", "(", "void", ")", "{",
                                       "return", "A_MAX", ";", "}"};
    static const char *const callees[] = {"g", "(indirect)"};
    static const char *const macros[] = {"A_MAX"};
    struct vcs_semantic_token_hash_v1 h;
    uint8_t d[32];
    vcs_semantic_token_hash_v1_init(&h);
    for (size_t k = 0; k < sizeof(toks) / sizeof(toks[0]); k++)
        vcs_semantic_token_hash_v1_add(&h, toks[k], strlen(toks[k]));
    vcs_semantic_token_hash_v1_final(&h, d);
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "src/a.c");
    vcs_semantic_record_v1_cstr(r, "f");
    vcs_semantic_record_v1_u8(r, 4);
    vcs_semantic_record_v1_cstr(r, "int (void)");
    vcs_semantic_record_v1_digest(r, d);
    vcs_semantic_record_v1_sorted_texts(r, callees, 2);
    vcs_semantic_record_v1_sorted_texts(r, macros, 1);
    if (!vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_FUNCTIONS, r))
        return false;
    vcs_semantic_record_v1_reset(r);
    vcs_semantic_record_v1_cstr(r, "src/a.c");
    vcs_semantic_record_v1_cstr(r, "f");
    vcs_semantic_record_v1_u32(r, 2);
    vcs_semantic_record_v1_u32(r, 2);
    vcs_semantic_record_v1_u64(r, 18);
    vcs_semantic_record_v1_u64(r, 46);
    return vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_SPANS, r);
}

/* Build the golden vector. `twice` adds every record a second time and in
 * a different order, which the builder must fold to the identical bytes. */
static bool smt_golden(bool twice, uint8_t **out, size_t *len)
{
    struct vcs_semantic_builder_v1 *b = vcs_semantic_builder_v1_new();
    struct vcs_semantic_record_v1 r = {0};
    char why[256];
    bool ok = b != NULL;
    for (int pass = 0; ok && pass < (twice ? 2 : 1); pass++) {
        ok = (pass == 1 || smt_golden_identity(b, &r)) &&
             smt_golden_function(b, &r) && smt_golden_layout_enum(b, &r) &&
             smt_golden_file(b, &r, "inc/a.h", "#define A_MAX 16\n",
                             VCS_SEMANTIC_ORIGIN_V1_REPO) &&
             smt_golden_file(b, &r, "src/a.c",
                             "#include \"a.h\"\nint f(void) { return A_MAX; }\n",
                             VCS_SEMANTIC_ORIGIN_V1_MAIN) &&
             smt_golden_lookup_macro_decl(b, &r);
    }
    ok = ok && vcs_semantic_builder_v1_finish(b, out, len, why, sizeof(why));
    if (!ok)
        printf("golden build refused: %s\n", why);
    vcs_semantic_record_v1_free(&r);
    vcs_semantic_builder_v1_free(b);
    return ok;
}

static void smt_hex(const uint8_t *d, size_t n, char *out)
{
    static const char hx[] = "0123456789abcdef";
    for (size_t k = 0; k < n; k++) {
        out[2 * k] = hx[d[k] >> 4];
        out[2 * k + 1] = hx[d[k] & 15];
    }
    out[2 * n] = '\0';
}

static void smt_print_golden(const uint8_t *a, size_t an, const uint8_t root[32],
                             const uint8_t hint[32])
{
    char hex[65];
    char *all = malloc(2 * an + 1); // raw-alloc-ok:test-print
    if (all != NULL) {
        smt_hex(a, an, all);
        printf("\ngolden len %zu bytes %s\n", an, all);
        free(all);
    }
    smt_hex(root, 32, hex);
    printf("golden root %s\n", hex);
    smt_hex(hint, 32, hex);
    printf("golden hint %s\n", hex);
}

static int smt_t_golden(void)
{
    int failures = 0;
    uint8_t *a = NULL, root[32], hint[32];
    size_t an = 0;
    char hex[65], why[256];
    TEST_CASE("semantic_manifest: golden vector bytes, root and hint root") {
        ASSERT(smt_golden(false, &a, &an));
        ASSERT(vcs_semantic_root_v1(a, an, root, why, sizeof(why)));
        ASSERT(vcs_semantic_hint_root_v1(a, an, hint, why, sizeof(why)));
        if (getenv("ZCL_SEMANTIC_FIXTURE_OUT") != NULL)
            smt_print_golden(a, an, root, hint);
        ASSERT_EQ(an, (size_t)SMT_GOLDEN_LEN);
        smt_hex(root, 32, hex);
        ASSERT_STR_EQ(hex, SMT_GOLDEN_ROOT);
        smt_hex(hint, 32, hex);
        ASSERT_STR_EQ(hex, SMT_GOLDEN_HINT);
    } TEST_END
    free(a);
    return failures;
}

static int smt_t_golden_fold(void)
{
    int failures = 0;
    uint8_t *a = NULL, *b = NULL;
    size_t an = 0, bn = 0;
    TEST_CASE("semantic_manifest: builder folds duplicates and order to the same bytes") {
        ASSERT(smt_golden(false, &a, &an));
        ASSERT(smt_golden(true, &b, &bn));
        ASSERT_EQ(an, bn);
        ASSERT(memcmp(a, b, an) == 0);
    } TEST_END
    free(a);
    free(b);
    return failures;
}

/* fuzz_semantic_manifest (tools/fuzz/fuzz_semantic_manifest.c) hit this on
 * its very first seed: a builder with the identity plus the one required
 * main file, and every other section (LOOKUPS, MACROS, DECLS, LAYOUTS,
 * ENUMS, FUNCTIONS, SPANS — every TU can genuinely have zero of some of
 * these, e.g. a header with no functions) untouched. finish() called
 * sm_dedupe() on every section including the untouched ones, whose
 * `items` array is still NULL because add() was never called for them.
 * sm_dedupe() called qsort(NULL, 0, ...) unconditionally: 0 elements is a
 * no-op for glibc's qsort, but qsort's `base` parameter carries a nonnull
 * attribute, so UBSan flagged real undefined behavior on every manifest
 * with at least one empty cappable section — which is most of them. Fixed
 * by returning before the qsort call when the list is empty. */
static int smt_t_empty_sections_finish(void)
{
    int failures = 0;
    TEST_CASE("semantic_manifest: finish() tolerates sections nobody added to") {
        struct vcs_semantic_builder_v1 *b = vcs_semantic_builder_v1_new();
        struct vcs_semantic_record_v1 r = {0};
        uint8_t *out = NULL;
        size_t out_len = 0;
        char why[256];
        ASSERT(b != NULL);
        ASSERT(smt_golden_identity(b, &r));
        ASSERT(smt_golden_file(b, &r, "src/a.c", "int f(void) { return 0; }\n",
                               VCS_SEMANTIC_ORIGIN_V1_MAIN));
        /* LOOKUPS, MACROS, DECLS, LAYOUTS, ENUMS, FUNCTIONS, SPANS: none
         * added. Before the fix, this finish() aborted under UBSan. */
        ASSERT(vcs_semantic_builder_v1_finish(b, &out, &out_len, why,
                                              sizeof(why)));
        ASSERT(vcs_semantic_manifest_v1_validate(out, out_len, why,
                                                 sizeof(why)));
        for (int t = VCS_SEMANTIC_SECTION_V1_LOOKUPS;
             t <= VCS_SEMANTIC_SECTION_V1_SPANS; t++) {
            uint32_t count = 1;
            ASSERT(vcs_semantic_section_count_v1(
                out, out_len, (enum vcs_semantic_section_v1)t, &count));
            ASSERT_EQ(count, 0u);
        }
        vcs_semantic_record_v1_free(&r);
        vcs_semantic_builder_v1_free(b);
        free(out);
    } TEST_END
    return failures;
}

/* ── the text dump of composite list elements ─────────────────────────────── */

/* The golden vector plus the facts extension and one PROBES record with two
 * UNKNOWN slots: the dump then renders all three composite element shapes
 * (env "T=b:T", layout field "T@q:u:T", probe slot "u:b"). */
static bool smt_dump_manifest(uint8_t **out, size_t *len)
{
    struct vcs_semantic_builder_v1 *b = vcs_semantic_builder_v1_new();
    struct vcs_semantic_record_v1 r = {0};
    struct vcs_semantic_facts_v1 f = {.max_records = 64,
                                      .max_section_bytes = 65536};
    char why[256];
    bool ok = b != NULL && vcs_semantic_builder_v1_enable_facts(b, &f) &&
              smt_golden_identity(b, &r) && smt_golden_function(b, &r) &&
              smt_golden_layout_enum(b, &r) &&
              smt_golden_file(b, &r, "inc/a.h", "#define A_MAX 16\n",
                              VCS_SEMANTIC_ORIGIN_V1_REPO) &&
              smt_golden_file(b, &r, "src/a.c",
                              "#include \"a.h\"\nint f(void) { return A_MAX; }\n",
                              VCS_SEMANTIC_ORIGIN_V1_MAIN) &&
              smt_golden_lookup_macro_decl(b, &r);
    if (ok) {
        vcs_semantic_record_v1_reset(&r);
        vcs_semantic_record_v1_cstr(&r, "src/a.c");
        vcs_semantic_record_v1_cstr(&r, "a.h");
        vcs_semantic_record_v1_u8(&r, VCS_SEMANTIC_FORM_V1_QUOTED);
        vcs_semantic_record_v1_u8(&r, VCS_SEMANTIC_LOOKUP_V1_INCLUDE);
        vcs_semantic_record_v1_u8(&r, 1);
        vcs_semantic_record_v1_u32(&r, 2);
        vcs_semantic_record_v1_u32(&r, 0);
        vcs_semantic_record_v1_u8(&r, VCS_SEMANTIC_PROBE_V1_NO_SNAPSHOT);
        vcs_semantic_record_v1_u32(&r, 3);
        vcs_semantic_record_v1_u8(&r, VCS_SEMANTIC_PROBE_V1_STALE);
        ok = vcs_semantic_builder_v1_add(b, VCS_SEMANTIC_SECTION_V1_PROBES, &r);
    }
    ok = ok && vcs_semantic_builder_v1_finish(b, out, len, why, sizeof(why));
    if (!ok && b != NULL)
        printf("dump manifest refused: %s\n", why);
    vcs_semantic_record_v1_free(&r);
    vcs_semantic_builder_v1_free(b);
    return ok;
}

#define SMT_ZERO64 "0000000000000000000000000000000000000000000000000000000000000000"

/* The exact dump, byte for byte: no NUL, no refusal, every separator. */
static const char k_smt_dump_text[] =
    "identity \"golden-cc 1.0\" \"\" \"x86_64-pc-linux-gnu\" \"src/a.c\" "
    "[\"-std=c23\",\"-I@root/inc\"] [] [\"inc\",\"@sys/usr/include\"] [] "
    "[\"CPATH\"=0:\"\",\"C_INCLUDE_PATH\"=0:\"\"]\n"
    "files \"inc/a.h\" "
    "ee66867d36d6568cc6df87baed5d1d11ca8fc3bedf059b377474fff50c8419b2 2\n"
    "files \"src/a.c\" "
    "a051dcdb2edfd0747256f2cd01abacab47279568195e39e163c796d927db772c 1\n"
    "lookups \"src/a.c\" \"a.h\" 1 1 \"inc/a.h\" 1 1 []\n"
    "macros \"inc/a.h\" \"A_MAX\" 0 \"16\" 1\n"
    "decls \"src/a.c\" \"function\" \"f\" \"int (void)\" 4\n"
    "layouts \"inc/a.h\" \"pair\" 1 8 4 "
    "[\"x\"@0:4294967295:\"int\",\"y\"@32:4294967295:\"int\"]\n"
    "enums \"inc/a.h\" \"mode\" \"MODE_ON\" -1\n"
    "functions \"src/a.c\" \"f\" 4 \"int (void)\" "
    "6daa7722bb3b1cda0220425a56ffed8b671753a4cc78e67cf3c468ace5aed041 "
    "[\"g\",\"(indirect)\"] [\"A_MAX\"]\n"
    "spans \"src/a.c\" \"f\" 2 2 18 46\n"
    "facts \"zcl.semantic_facts.v1\" " SMT_ZERO64 " " SMT_ZERO64 " 64 65536 1\n"
    "probes \"src/a.c\" \"a.h\" 1 1 1 [0:1,3:4]\n";

static bool smt_has_bytes(const uint8_t *m, size_t n, const char *s)
{
    size_t k = strlen(s);
    for (size_t i = 0; k <= n && i + k <= n; i++)
        if (memcmp(m + i, s, k) == 0)
            return true;
    return false;
}

/* A facts manifest under one extension revision; 0 bytes when refused. */
static bool smt_revision_manifest(uint8_t revision, uint8_t **out, size_t *len)
{
    struct vcs_semantic_builder_v1 *b = vcs_semantic_builder_v1_new();
    struct vcs_semantic_record_v1 r = {0};
    struct vcs_semantic_facts_v1 f = {.max_records = 64,
                                      .max_section_bytes = 65536,
                                      .revision = revision};
    char why[256];
    bool ok = b != NULL && vcs_semantic_builder_v1_enable_facts(b, &f) &&
              smt_golden_identity(b, &r) &&
              smt_golden_file(b, &r, "src/a.c", "int f(void);\n",
                              VCS_SEMANTIC_ORIGIN_V1_MAIN) &&
              vcs_semantic_builder_v1_finish(b, out, len, why, sizeof(why));
    vcs_semantic_record_v1_free(&r);
    vcs_semantic_builder_v1_free(b);
    return ok;
}

/* Revision 2 names zcl.semantic_facts.v2 and the reader reports it;
 * revision 0 and 1 both write v1; a revision past 2 is refused. */
static int smt_t_facts_revision(void)
{
    int failures = 0;
    TEST_CASE("semantic_manifest: facts revision 2 is named, validated and read back") {
        uint8_t revs[] = {0, 1, 2};
        uint8_t want[] = {1, 1, 2};
        uint8_t *m = NULL;
        size_t n = 0;
        for (size_t k = 0; k < sizeof(revs); k++) {
            struct vcs_semantic_facts_info_v1 info;
            ASSERT(smt_revision_manifest(revs[k], &m, &n));
            ASSERT(vcs_semantic_manifest_v1_validate(m, n, NULL, 0));
            ASSERT(vcs_semantic_facts_v1_info(m, n, &info));
            ASSERT(info.present);
            ASSERT_EQ(info.revision, want[k]);
            ASSERT(smt_has_bytes(m, n, want[k] == 2 ? VCS_SEMANTIC_FACTS_V2_NAME
                                                  : VCS_SEMANTIC_FACTS_V1_NAME));
            free(m);
            m = NULL;
        }
        ASSERT(!smt_revision_manifest(3, &m, &n));
        free(m);
    } TEST_END
    return failures;
}

/* Render the manifest through a real FILE and read every byte back. */
static bool smt_dump_bytes(const uint8_t *m, size_t n, char *out, size_t cap,
                           size_t *len)
{
    FILE *fp = tmpfile();
    bool ok;
    *len = 0;
    if (fp == NULL)
        return false;
    ok = vcs_semantic_manifest_v1_dump(m, n, fp) && fflush(fp) == 0 &&
         fseek(fp, 0, SEEK_SET) == 0;
    if (ok) {
        *len = fread(out, 1, cap - 1, fp);
        out[*len] = '\0';
        ok = ferror(fp) == 0 && *len < cap - 1;
    }
    (void)fclose(fp);
    return ok;
}

static int smt_t_dump_composites(void)
{
    int failures = 0;
    uint8_t *m = NULL;
    size_t n = 0, len = 0;
    char *text = malloc(8192); // raw-alloc-ok:test-buffer
    TEST_CASE("semantic_manifest: dump renders env, field and slot composites exactly") {
        ASSERT(text != NULL);
        ASSERT(smt_dump_manifest(&m, &n));
        ASSERT(smt_dump_bytes(m, n, text, 8192, &len));
        ASSERT(memchr(text, '\0', len) == NULL);
        ASSERT_EQ(len, sizeof(k_smt_dump_text) - 1);
        ASSERT_STR_EQ(text, k_smt_dump_text);
    } TEST_END
    free(text);
    free(m);
    return failures;
}

/* ── decoder refusals ─────────────────────────────────────────────────────── */

/* Offset of the first occurrence of needle in hay, or SIZE_MAX. */
static size_t smt_find(const uint8_t *hay, size_t n, const char *needle)
{
    size_t k = strlen(needle);
    for (size_t i = 0; i + k <= n; i++) {
        if (memcmp(hay + i, needle, k) == 0)
            return i;
    }
    return SIZE_MAX;
}

static bool smt_refused(const uint8_t *m, size_t n)
{
    char why[256];
    uint8_t root[32];
    return !vcs_semantic_manifest_v1_validate(m, n, why, sizeof(why)) &&
           !vcs_semantic_root_v1(m, n, root, why, sizeof(why)) && why[0] != '\0';
}

/* Copy `m`, overwrite `from` (first hit) with same-length `to`, and check. */
static bool smt_refused_patch(const uint8_t *m, size_t n, const char *from,
                              const char *to)
{
    uint8_t *c = malloc(n); // raw-alloc-ok:test-mutant
    size_t at = smt_find(m, n, from);
    bool refused;
    if (c == NULL || at == SIZE_MAX || strlen(from) != strlen(to)) {
        free(c);
        return false;
    }
    memcpy(c, m, n);
    memcpy(c + at, to, strlen(to));
    refused = smt_refused(c, n);
    free(c);
    return refused;
}

static bool smt_refused_byte(const uint8_t *m, size_t n, size_t at, uint8_t v)
{
    uint8_t *c = malloc(n); // raw-alloc-ok:test-mutant
    bool refused;
    if (c == NULL || at >= n)
        return false;
    memcpy(c, m, n);
    c[at] = v;
    refused = smt_refused(c, n);
    free(c);
    return refused;
}

static int smt_t_refusals(void)
{
    int failures = 0;
    uint8_t *m = NULL, *c = NULL;
    size_t n = 0, magic = strlen(VCS_SEMANTIC_MANIFEST_V1_MAGIC);
    TEST_CASE("semantic_manifest: decoder refuses non-canonical bytes") {
        ASSERT(smt_golden(false, &m, &n));
        ASSERT(vcs_semantic_manifest_v1_validate(m, n, NULL, 0));
        ASSERT(smt_refused(m, n - 1));                      /* truncated */
        ASSERT(smt_refused(m, 0));
        ASSERT(smt_refused_byte(m, n, 0, 'Z'));             /* magic */
        ASSERT(smt_refused_byte(m, n, magic, 2));           /* section order */
        ASSERT(smt_refused_patch(m, n, "src/a.c", "/rc/a.c")); /* absolute path */
        ASSERT(smt_refused_patch(m, n, "inc/a.h", "../a.hh")); /* dot-dot */
        ASSERT(smt_refused_patch(m, n, "-I@root/inc", "-I/opt/incl")); /* host path in argv */
        ASSERT(smt_refused_patch(m, n, "CPATH", "PATHX"));   /* env allowlist */
        ASSERT(smt_refused_patch(m, n, "inc/a.h", "zzz/a.h")); /* record order */
        ASSERT(smt_refused_patch(m, n, "src/a.c", "src/b.c")); /* main mismatch */
        c = malloc(n + 1); // raw-alloc-ok:test-mutant
        ASSERT(c != NULL);
        memcpy(c, m, n);
        c[n] = 0;
        ASSERT(smt_refused(c, n + 1));                      /* trailing byte */
    } TEST_END
    free(c);
    free(m);
    return failures;
}

/* ── the checked-in sensor manifests (no libclang needed) ─────────────────── */

static bool smt_load_fixture(const char *name, uint8_t **m, size_t *n)
{
    char path[PATH_MAX];
    (void)snprintf(path, sizeof(path), "%s/%s.bin", SMT_FIXTURES, name);
    if (smt_read(path, m, n))
        return true;
    printf("FAIL cannot read %s\n", path);
    return false;
}

static int smt_t_fixture_invariance(void)
{
    int failures = 0;
    uint8_t *base = NULL, *other = NULL, *committed = NULL;
    size_t bn = 0, on = 0, cn = 0;
    TEST_CASE("semantic_manifest: stored base is valid and invariant across commit and root") {
        ASSERT(smt_load_fixture("base", &base, &bn));
        ASSERT(smt_load_fixture("base_other_root", &other, &on));
        ASSERT(smt_load_fixture("base_committed", &committed, &cn));
        ASSERT(vcs_semantic_manifest_v1_validate(base, bn, NULL, 0));
        ASSERT(bn == on && memcmp(base, other, bn) == 0);
        ASSERT(bn == cn && memcmp(base, committed, bn) == 0);
    } TEST_END
    free(base);
    free(other);
    free(committed);
    return failures;
}

static int smt_t_fixture_seeds(void)
{
    int failures = 0, bad = 0;
    uint8_t *base = NULL;
    size_t bn = 0;
    TEST_CASE("semantic_manifest: every stored seed changes exactly its sections") {
        ASSERT(smt_load_fixture("base", &base, &bn));
        for (int k = 0; k < SMT_SEED_COUNT; k++) {
            uint8_t *m = NULL;
            size_t mn = 0;
            if (!smt_load_fixture(k_smt_seeds[k].name, &m, &mn))
                bad++;
            else
                bad += smt_check_seed(&k_smt_seeds[k], base, bn, m, mn);
            free(m);
        }
        ASSERT_EQ(bad, 0);
    } TEST_END
    free(base);
    return failures;
}

/* ── the Windows cross-link ledger, recomputed natively ──────────────────
 * tests/harness/src/semantic_manifest_windows_acceptance.c is the strict-C23
 * catalog program platform/modules/platform/tests/windows_acceptance.mk
 * cross-links with mingw. It embeds a byte-exact compile-time copy of every
 * fixture below and folds their (name, root, hint root) into one SHA3
 * ledger digest, pinned as SMWA_LEDGER_DIGEST there. This test computes the
 * identical ledger, over the identical files, read live from disk instead
 * of embedded, and pins the identical digest here as SMT_LEDGER_DIGEST. The
 * two readings agreeing is the evidence that the reader's output does not
 * depend on the embedding or the platform: a change to either without the
 * other is caught because the two pinned constants would then disagree. */
#define SMT_LEDGER_DIGEST \
    "410a13f3370324250f7320d10113c87c75ce15d72289aa3e39340ea6222ba231"

struct smt_ledger_row {
    char name[96];
    char line[228]; /* "name root hint\n" */
};

static int smt_ledger_row_cmp(const void *a, const void *b)
{
    const struct smt_ledger_row *ra = a;
    const struct smt_ledger_row *rb = b;
    return strcmp(ra->name, rb->name);
}

/* List every regular file directly under dir, sorted, as "<label>/<name>". */
static int smt_ledger_list(const char *dir, const char *label,
                           char names[][96], int max, int *count)
{
    DIR *d = opendir(dir);
    struct dirent *ent;
    int n = *count;
    if (d == NULL)
        return 0;
    while ((ent = readdir(d)) != NULL) {
        if (ent->d_name[0] == '.' || n >= max)
            continue;
        (void)snprintf(names[n], 96, "%s/%s", label, ent->d_name);
        n++;
    }
    (void)closedir(d);
    *count = n;
    return 1;
}

static int smt_t_ledger(void)
{
    int failures = 0;
    char names[64][96];
    int count = 0;
    struct smt_ledger_row rows[64];
    int n = 0;

    TEST_CASE("semantic_manifest: Windows-catalog ledger digest matches, computed live off disk") {
        ASSERT(smt_ledger_list(SMT_FIXTURES, "semantic_manifest", names, 64,
                               &count));
        ASSERT(smt_ledger_list(SMT_FACTS_FIXTURES, "semantic_facts", names, 64,
                               &count));
        for (int k = 0; k < count; k++) {
            char path[PATH_MAX];
            uint8_t *m = NULL;
            size_t mn = 0;
            uint8_t root[32], hint[32];
            char root_hex[65], hint_hex[65];
            (void)snprintf(path, sizeof(path), "tests/fixtures/%s", names[k]);
            ASSERT(smt_read(path, &m, &mn));
            ASSERT(vcs_semantic_manifest_v1_validate(m, mn, NULL, 0));
            ASSERT(vcs_semantic_root_v1(m, mn, root, NULL, 0));
            ASSERT(vcs_semantic_hint_root_v1(m, mn, hint, NULL, 0));
            smt_hex(root, 32, root_hex);
            smt_hex(hint, 32, hint_hex);
            (void)snprintf(rows[n].name, sizeof(rows[n].name), "%s", names[k]);
            (void)snprintf(rows[n].line, sizeof(rows[n].line), "%s %s %s\n",
                           names[k], root_hex, hint_hex);
            n++;
            free(m);
        }
        ASSERT_EQ(n, 36);
        qsort(rows, (size_t)n, sizeof(rows[0]), smt_ledger_row_cmp);

        size_t joined_len = 0;
        char *joined = malloc((size_t)n * sizeof(rows[0].line) + 1); // raw-alloc-ok:test-scratch
        ASSERT(joined != NULL);
        for (int k = 0; k < n; k++) {
            size_t l = strlen(rows[k].line);
            memcpy(joined + joined_len, rows[k].line, l);
            joined_len += l;
        }
        static const char domain[] = "zcl.semantic_manifest_windows_ledger.v1";
        size_t dlen = strlen(domain);
        uint8_t *preimage = malloc(dlen + joined_len); // raw-alloc-ok:test-scratch
        ASSERT(preimage != NULL);
        memcpy(preimage, domain, dlen);
        memcpy(preimage + dlen, joined, joined_len);
        uint8_t digest[32];
        char digest_hex[65];
        zcl_sha3_256(preimage, dlen + joined_len, digest);
        smt_hex(digest, 32, digest_hex);
        free(preimage);
        free(joined);
        printf("semantic_manifest: ledger fixtures=%d digest=%s\n", n,
               digest_hex);
        ASSERT(strcmp(digest_hex, SMT_LEDGER_DIGEST) == 0);
    } TEST_END
    return failures;
}

/* semantic_sensor_identity.c: the facts rule's argv, which needs only make. */
int semantic_sensor_argv_tests(void);

int test_semantic_manifest(void)
{
    int failures = 0;
    failures += smt_t_golden();
    failures += smt_t_golden_fold();
    failures += smt_t_empty_sections_finish();
    failures += smt_t_dump_composites();
    failures += smt_t_facts_revision();
    failures += smt_t_refusals();
    failures += smt_t_fixture_invariance();
    failures += smt_t_fixture_seeds();
    failures += smt_t_ledger();
    failures += semantic_sensor_argv_tests();
    return failures;
}

/* ── the live sensor ───────────────────────────────────────────────────────── */

struct smt_run {
    char out[1024];
    char root_a[1024];
    char root_b[1024];
    char seed_root[1100];
};

static bool smt_spawn(const char *const *argv)
{
    char buf[4096];
    bool timed_out = false;
    int rc = zcl_spawn_capture_merged_observed(argv, buf, sizeof(buf), 60000,
                                               &timed_out);
    if (rc != 0)
        printf("FAIL %s %s exited %d: %s\n", argv[0], argv[1], rc, buf);
    return rc == 0;
}

static bool smt_emit(const char *root, const struct smt_argv *a,
                     const char *out_dir, const char *name)
{
    char out[PATH_MAX];
    const char *argv[32];
    size_t k = 0;
    (void)snprintf(out, sizeof(out), "%s/%s.bin", out_dir, name);
    argv[k++] = SMT_SENSOR;
    argv[k++] = "emit";
    argv[k++] = "--root";
    argv[k++] = root;
    argv[k++] = "--source";
    argv[k++] = "src/main.c";
    argv[k++] = "--out";
    argv[k++] = out;
    argv[k++] = "--";
    for (size_t i = 0; i < a->n && k < 31; i++)
        argv[k++] = a->items[i];
    argv[k] = NULL;
    return smt_spawn(argv);
}

static bool smt_git(const char *root, const char *a1, const char *a2,
                    const char *a3, const char *a4)
{
    const char *argv[] = {"git", "-C", root, "-c", "user.name=smt",
                          "-c", "user.email=smt@example.invalid",
                          "-c", "commit.gpgsign=false",
                          "-c", "core.hooksPath=/dev/null",
                          a1, a2, a3, a4, NULL};
    return smt_spawn(argv);
}

static bool smt_same_file(const char *dir, const char *x, const char *y)
{
    char px[PATH_MAX], py[PATH_MAX];
    uint8_t *a = NULL, *b = NULL;
    size_t an = 0, bn = 0;
    bool same;
    (void)snprintf(px, sizeof(px), "%s/%s.bin", dir, x);
    (void)snprintf(py, sizeof(py), "%s/%s.bin", dir, y);
    same = smt_read(px, &a, &an) && smt_read(py, &b, &bn) && an == bn &&
           memcmp(a, b, an) == 0;
    free(a);
    free(b);
    return same;
}

/* Copy one produced manifest to ZCL_SEMANTIC_FIXTURE_OUT (fixture refresh). */
static void smt_export(const char *out_dir, const char *name)
{
    const char *dest = getenv("ZCL_SEMANTIC_FIXTURE_OUT");
    char src[PATH_MAX], dst[PATH_MAX];
    uint8_t *b = NULL;
    size_t n = 0;
    FILE *fp;
    if (dest == NULL || dest[0] == '\0')
        return;
    (void)snprintf(src, sizeof(src), "%s/%s.bin", out_dir, name);
    (void)snprintf(dst, sizeof(dst), "%s/%s.bin", dest, name);
    if (!smt_read(src, &b, &n))
        return;
    fp = fopen(dst, "wb");
    if (fp != NULL) {
        (void)fwrite(b, 1, n, fp);
        (void)fclose(fp);
    }
    free(b);
}

static bool smt_run_base(struct smt_run *r)
{
    struct smt_argv a;
    smt_base_argv(&a, r->root_a);
    if (!smt_write_tree(r->root_a) || !smt_emit(r->root_a, &a, r->out, "base"))
        return false;
    smt_base_argv(&a, r->root_b);
    if (!smt_write_tree(r->root_b) ||
        !smt_emit(r->root_b, &a, r->out, "base_other_root"))
        return false;
    smt_base_argv(&a, r->root_a);
    return smt_git(r->root_a, "init", "-q", NULL, NULL) &&
           smt_git(r->root_a, "add", "-A", NULL, NULL) &&
           smt_git(r->root_a, "commit", "-q", "-m", "fixture") &&
           smt_emit(r->root_a, &a, r->out, "base_committed");
}

static int smt_run_seed(struct smt_run *r, enum smt_seed_id id)
{
    struct smt_argv a;
    char path[PATH_MAX];
    uint8_t *base = NULL, *m = NULL;
    size_t bn = 0, mn = 0;
    int bad = 1;
    const char *name = k_smt_seeds[id].name;
    (void)test_rm_rf_recursive(r->seed_root);
    if (mkdir(r->seed_root, 0700) != 0 || !smt_write_tree(r->seed_root) ||
        !smt_apply_files(id, r->seed_root)) {
        printf("FAIL seed %s: cannot build its tree\n", name);
        return 1;
    }
    smt_base_argv(&a, r->seed_root);
    if (!smt_apply_argv(id, &a) || !smt_emit(r->seed_root, &a, r->out, name))
        return 1;
    (void)snprintf(path, sizeof(path), "%s/base.bin", r->out);
    if (smt_read(path, &base, &bn)) {
        (void)snprintf(path, sizeof(path), "%s/%s.bin", r->out, name);
        if (smt_read(path, &m, &mn))
            bad = smt_check_seed(&k_smt_seeds[id], base, bn, m, mn);
    }
    free(base);
    free(m);
    smt_export(r->out, name);
    return bad;
}

static int smt_t_sensor_invariance(struct smt_run *r)
{
    int failures = 0;
    TEST_CASE("semantic_sensor: identical root before/after git commit and at two roots") {
        ASSERT(test_mkdtemp(r->out, sizeof(r->out), "semsensor_out") != NULL);
        ASSERT(test_mkdtemp(r->root_a, sizeof(r->root_a), "semsensor_a") != NULL);
        ASSERT(test_mkdtemp(r->root_b, sizeof(r->root_b), "semsensor_b") != NULL);
        (void)snprintf(r->seed_root, sizeof(r->seed_root), "%s/seed", r->out);
        ASSERT(smt_run_base(r));
        ASSERT(smt_same_file(r->out, "base", "base_other_root"));
        ASSERT(smt_same_file(r->out, "base", "base_committed"));
        smt_export(r->out, "base");
        smt_export(r->out, "base_other_root");
        smt_export(r->out, "base_committed");
    } TEST_END
    return failures;
}

static int smt_t_sensor_seeds(struct smt_run *r)
{
    int failures = 0, bad = 0;
    TEST_CASE("semantic_sensor: every adversarial seed changes exactly its sections") {
        ASSERT(r->seed_root[0] != '\0');
        for (int k = 0; k < SMT_SEED_COUNT; k++)
            bad += smt_run_seed(r, (enum smt_seed_id)k);
        ASSERT_EQ(bad, 0);
    } TEST_END
    return failures;
}

/* The home guard (cm_spell refuses a host path under $HOME outside the
 * checkout) needs a resolved home. Run the sensor through env(1) with HOME
 * unset, relative or naming no directory: each run must refuse with the
 * guard's reason and leave no manifest behind, never spell a path under the
 * real home as @sys/<abs>. */
static bool smt_home_refuses(const char *root, const char *out,
                             const char *const *env_args)
{
    const char *argv[24];
    size_t k = 0;
    char message[4096];
    bool timed_out = false;
    struct stat sb;
    argv[k++] = "env";
    for (size_t i = 0; env_args[i] != NULL; i++)
        argv[k++] = env_args[i];
    argv[k++] = SMT_SENSOR;
    argv[k++] = "emit";
    argv[k++] = "--root";
    argv[k++] = root;
    argv[k++] = "--source";
    argv[k++] = "home.c";
    argv[k++] = "--out";
    argv[k++] = out;
    argv[k++] = "--";
    argv[k++] = "-std=c23";
    argv[k] = NULL;
    int rc = zcl_spawn_capture_merged_observed(argv, message, sizeof(message),
                                               60000, &timed_out);
    bool refused = !timed_out && rc != 0 &&
                   strstr(message, "home directory unresolved") != NULL;
    bool absent = stat(out, &sb) != 0 && errno == ENOENT;
    if (!refused || !absent)
        printf("  home guard (env %s %s): rc=%d absent=%d: %s\n", env_args[1],
               env_args[2] != NULL ? env_args[2] : "", rc,
               (int)absent, message);
    return refused && absent;
}

static int smt_t_sensor_home_guard(void)
{
    int failures = 0;
    char dir[1024] = {0}, out[PATH_MAX];
    static const char *const unset[] = {"-u", "HOME", NULL};
    static const char *const relative[] = {"-u", "HOME", "HOME=relative/home",
                                           NULL};
    static const char *const missing[] = {"-u", "HOME",
                                          "HOME=/nonexistent/smt-home", NULL};
    TEST_CASE("semantic_sensor: refuses without a resolved home and writes nothing") {
        ASSERT(test_mkdtemp(dir, sizeof(dir), "semsensor_home") != NULL);
        ASSERT(smt_write(dir, "home.c", "int home_value(void) { return 1; }\n"));
        (void)snprintf(out, sizeof(out), "%s/home.bin", dir);
        ASSERT(smt_home_refuses(dir, out, unset));
        ASSERT(smt_home_refuses(dir, out, relative));
        ASSERT(smt_home_refuses(dir, out, missing));
    } TEST_END
    if (dir[0] != '\0')
        (void)test_rm_rf_recursive(dir);
    return failures;
}

/* Driver spellings that select a non-C language (or another driver) without
 * -x. Each must refuse with the language reason and leave no manifest, on
 * every host: the AST walk would otherwise describe a C++ or Objective-C
 * parse as C, since a plain declaration reports CXLanguage_C either way. */
static bool smt_language_refuses(const char *dir, const char *const *flags)
{
    char out[PATH_MAX], message[4096];
    const char *argv[16] = {SMT_SENSOR, "emit", "--root", dir, "--source",
                            "alias.c", "--out", out, "--"};
    bool timed_out = false;
    struct stat sb;
    size_t n = 9;
    (void)snprintf(out, sizeof(out), "%s/alias.bin", dir);
    for (size_t k = 0; flags[k] != NULL && n < 15; k++)
        argv[n++] = flags[k];
    argv[n] = NULL;
    int rc = zcl_spawn_capture_merged_observed(argv, message, sizeof(message),
                                               60000, &timed_out);
    bool refused = !timed_out && rc != 0 &&
                   strstr(message, "unsupported translation-unit language") != NULL;
    bool absent = stat(out, &sb) != 0 && errno == ENOENT;
    if (!refused || !absent)
        printf("  language alias %s: rc=%d absent=%d: %s\n", flags[0], rc,
               (int)absent, message);
    (void)unlink(out);
    return refused && absent;
}

static int smt_t_sensor_language_aliases(void)
{
    int failures = 0;
    char dir[1024] = {0};
    static const char *const cases[][3] = {
        {"--language", "c++", NULL}, {"--language=c++", NULL, NULL},
        {"-ObjC", NULL, NULL},       {"-ObjC++", NULL, NULL},
        {"--driver-mode=g++", NULL, NULL}, {"--std=c11", NULL, NULL},
        {"--std", "c11", NULL},
    };
    TEST_CASE("semantic_sensor: refuses driver spellings of a non-C language") {
        ASSERT(test_mkdtemp(dir, sizeof(dir), "semsensor_alias") != NULL);
        ASSERT(smt_write(dir, "alias.c", "int alias_value(int x) { return x; }\n"));
        for (size_t k = 0; k < sizeof(cases) / sizeof(cases[0]); k++)
            ASSERT(smt_language_refuses(dir, cases[k]));
    } TEST_END
    if (dir[0] != '\0')
        (void)test_rm_rf_recursive(dir);
    return failures;
}

/* A file-scope static assertion is C11/C23. libclang tags its cursor as C++
 * by declaration kind alone, so it must not decide the TU language: a C TU
 * that asserts at file scope, in the source or in a repo header it includes,
 * under either spelling, is sensed. The same assertion in a C++ TU still
 * refuses with the language reason and leaves no manifest. */
static const char k_smt_assert_h[] =
    "#ifndef ASSERTS_H\n"
    "#define ASSERTS_H\n"
    "_Static_assert(sizeof(int) >= 2, \"int width\");\n"
    "#endif\n";

static bool smt_assert_emit(const char *dir, const char *source,
                            const char *const *flags, bool accepted)
{
    char out[PATH_MAX], message[4096];
    const char *argv[16] = {SMT_SENSOR, "emit", "--root", dir, "--source",
                            source, "--out", out, "--"};
    uint8_t *m = NULL, section[32];
    size_t n = 9, mn = 0;
    bool timed_out = false, ok;
    struct stat sb;
    (void)snprintf(out, sizeof(out), "%s/%s.bin", dir, source);
    for (size_t k = 0; flags[k] != NULL && n < 15; k++)
        argv[n++] = flags[k];
    argv[n] = NULL;
    int rc = zcl_spawn_capture_merged_observed(argv, message, sizeof(message),
                                               60000, &timed_out);
    if (accepted)
        ok = !timed_out && rc == 0 && smt_read(out, &m, &mn) &&
             vcs_semantic_section_root_v1(m, mn,
                     VCS_SEMANTIC_SECTION_V1_FUNCTIONS, section);
    else
        ok = !timed_out && rc != 0 &&
             strstr(message, "unsupported translation-unit language") != NULL &&
             stat(out, &sb) != 0 && errno == ENOENT;
    if (!ok)
        printf("  static assert %s %s: rc=%d: %s\n", source, flags[0], rc,
               message);
    free(m);
    return ok;
}

static int smt_t_sensor_static_assert(void)
{
    int failures = 0;
    char dir[1024] = {0};
    static const char *const c11[] = {"-std=c11", NULL};
    static const char *const c23[] = {"-std=c23", NULL};
    static const char *const cxx[] = {"-x", "c++", "-std=c++17", NULL};
    TEST_CASE("semantic_sensor: file-scope static_assert is C, not a C++ signal") {
        ASSERT(test_mkdtemp(dir, sizeof(dir), "semsensor_assert") != NULL);
        ASSERT(smt_write(dir, "asserts.h", k_smt_assert_h));
        ASSERT(smt_write(dir, "c11.c",
                         "#include \"asserts.h\"\n"
                         "_Static_assert(sizeof(long) >= 4, \"long width\");\n"
                         "int c11_value(void) { return 11; }\n"));
        ASSERT(smt_write(dir, "c23.c",
                         "#include \"asserts.h\"\n"
                         "static_assert(sizeof(long) >= 4, \"long width\");\n"
                         "static_assert(sizeof(char) == 1);\n"
                         "_Static_assert(1, \"keyword\");\n"
                         "int c23_value(void) { return 23; }\n"));
        ASSERT(smt_write(dir, "cxx.c",
                         "static_assert(sizeof(long) >= 4, \"long width\");\n"
                         "int cxx_value() { return 17; }\n"));
        ASSERT(smt_write(dir, "cxxdecl.c",
                         "static_assert(sizeof(long) >= 4, \"long width\");\n"
                         "class Widget {\n"
                         "public:\n"
                         "    int value() { return 42; }\n"
                         "};\n"));
        ASSERT(smt_assert_emit(dir, "c11.c", c11, true));
        ASSERT(smt_assert_emit(dir, "c23.c", c23, true));
        ASSERT(smt_assert_emit(dir, "cxx.c", cxx, false));
        /* A genuine C++ declaration alongside the same static_assert must
         * still refuse: the guard is narrow to CXCursor_StaticAssert, not a
         * blanket pass for the whole translation unit. */
        ASSERT(smt_assert_emit(dir, "cxxdecl.c", cxx, false));
    } TEST_END
    if (dir[0] != '\0')
        (void)test_rm_rf_recursive(dir);
    return failures;
}

/* A static assertion emits no bytes, but its condition reads sizes, offsets,
 * enumerators and macros: when one of those changes, the assertion can stop
 * holding and the TU stops compiling. The sensor records each entity the
 * condition names as a ref from the pseudo-site "@assert:<file>" of the file
 * the assertion is written in, at file scope and inside a struct alike; a
 * block-scope assertion is part of its function's own refs. */
static const char k_smt_sa_shape_h[] =
    "#ifndef SHAPE_H\n"
    "#define SHAPE_H\n"
    "struct shape { int a; int b; };\n"
    "enum shape_kind { SHAPE_KIND = 3 };\n"
    "#define SHAPE_MAX 16\n"
    "int shape_unrelated(int x);\n"
    "#endif\n";
static const char k_smt_sa_guard_h[] =
    "#ifndef GUARD_H\n"
    "#define GUARD_H\n"
    "#include \"shape.h\"\n"
    "static_assert(sizeof(struct shape) >= 8, \"shape size\");\n"
    "static_assert(SHAPE_MAX <= 64, \"shape max\");\n"
    "#endif\n";
static const char k_smt_sa_use_c[] =
    "#include \"guard.h\"\n"
    "struct holder {\n"
    "    int v;\n"
    "    static_assert(SHAPE_KIND == 3, \"kind\");\n"
    "};\n"
    "static_assert(__builtin_offsetof(struct shape, b) == sizeof(int), \"b\");\n"
    "int use_value(void)\n"
    "{\n"
    "    static_assert(_Alignof(struct shape) >= 1, \"block\");\n"
    "    return shape_unrelated(1);\n"
    "}\n";

struct smt_ref_q {
    const char *from, *to;
    uint64_t kind;
    size_t hits;
};

static bool smt_span_eq(const char *t, size_t n, const char *s)
{
    return n == strlen(s) && memcmp(t, s, n) == 0;
}

static bool smt_ref_cb(void *ctx, const struct vcs_semantic_fields_v1 *f)
{
    struct smt_ref_q *q = ctx;
    if (f->ntext >= 2 && f->nnum >= 1 && f->num[0] == q->kind &&
        smt_span_eq(f->text[0], f->text_len[0], q->from) &&
        smt_span_eq(f->text[1], f->text_len[1], q->to))
        q->hits++;
    return true;
}

static size_t smt_refs(const uint8_t *m, size_t n, const char *from,
                       uint64_t kind, const char *to)
{
    struct smt_ref_q q = {.from = from, .to = to, .kind = kind};
    if (!vcs_semantic_section_v1_each(m, n, VCS_SEMANTIC_SECTION_V1_REFS,
                                      smt_ref_cb, &q))
        return SIZE_MAX;
    return q.hits;
}

static bool smt_sa_emit(const char *dir, uint8_t **m, size_t *mn)
{
    char out[PATH_MAX], message[4096];
    const char *argv[] = {SMT_SENSOR, "emit", "--root", dir, "--source",
                          "use.c", "--out", out, "--facts", "--",
                          "-std=c23", NULL};
    bool timed_out = false;
    (void)snprintf(out, sizeof(out), "%s/use.zsm", dir);
    int rc = zcl_spawn_capture_merged_observed(argv, message, sizeof(message),
                                               60000, &timed_out);
    if (timed_out || rc != 0 || !smt_read(out, m, mn)) {
        printf("  static assert facts: rc=%d: %s\n", rc, message);
        return false;
    }
    return true;
}

static int smt_t_sensor_static_assert_facts(void)
{
    int failures = 0;
    char dir[1024] = {0};
    uint8_t *m = NULL;
    size_t n = 0;
    TEST_CASE("semantic_sensor: a static_assert's condition is an @assert ref") {
        ASSERT(test_mkdtemp(dir, sizeof(dir), "semsensor_safacts") != NULL);
        ASSERT(smt_write(dir, "shape.h", k_smt_sa_shape_h));
        ASSERT(smt_write(dir, "guard.h", k_smt_sa_guard_h));
        ASSERT(smt_write(dir, "use.c", k_smt_sa_use_c));
        ASSERT(smt_sa_emit(dir, &m, &n));
        /* a header's file-scope assertion: sizeof names the struct, and the
         * macro its condition expands is attributed to it too */
        ASSERT_EQ(smt_refs(m, n, "@assert:guard.h",
                           VCS_SEMANTIC_REF_V1_TYPE, "s:shape"), 1);
        ASSERT_EQ(smt_refs(m, n, "@assert:guard.h",
                           VCS_SEMANTIC_REF_V1_MACRO, "m:shape.h:SHAPE_MAX"), 1);
        /* the main file's: offsetof at file scope, an enumerator in a
         * struct's member list */
        ASSERT_EQ(smt_refs(m, n, "@assert:use.c",
                           VCS_SEMANTIC_REF_V1_TYPE, "s:shape"), 1);
        ASSERT_EQ(smt_refs(m, n, "@assert:use.c",
                           VCS_SEMANTIC_REF_V1_ENUMERATOR,
                           "k:shape.h:SHAPE_KIND"), 1);
        /* a block-scope assertion is its function's */
        ASSERT_EQ(smt_refs(m, n, "f:use_value", VCS_SEMANTIC_REF_V1_TYPE,
                           "s:shape"), 1);
        /* nothing an assertion does not name */
        ASSERT_EQ(smt_refs(m, n, "@assert:guard.h",
                           VCS_SEMANTIC_REF_V1_ADDRESS, "f:shape_unrelated"), 0);
        ASSERT_EQ(smt_refs(m, n, "@assert:use.c",
                           VCS_SEMANTIC_REF_V1_CALL, "f:shape_unrelated"), 0);
    } TEST_END
    free(m);
    if (dir[0] != '\0')
        (void)test_rm_rf_recursive(dir);
    return failures;
}

#if defined(__APPLE__)
/* Exercise the Apple libclang type-spelling adapter with facts enabled, so
 * these assertions also require a verified, nonzero producer identity. */
static const char k_smt_darwin_types[] =
    "typedef int item_t;\n"
    "struct pair { item_t count; const int *pointer; int values[3]; "
    "int (*callback)(int); };\n"
    "int twice(int value) { return value * 2; }\n"
    "int apply(struct pair *p) { return p->callback(p->count); }\n";

static bool smt_darwin_emit(const char *root, const char *source,
                             const char *out)
{
    const char *argv[] = {SMT_SENSOR, "emit", "--root", root, "--source",
                          source, "--out", out, "--facts", "--",
                          "-std=c23", "-O2", NULL};
    return smt_spawn(argv);
}

static bool smt_darwin_refuses(const char *root, const char *source,
                                const char *out, const char *reason)
{
    const char *argv[] = {SMT_SENSOR, "emit", "--root", root, "--source",
                          source, "--out", out, "--facts", "--",
                          "-std=c23", NULL};
    char message[4096];
    bool timed_out = false;
    struct stat sb;
    int rc = zcl_spawn_capture_merged_observed(argv, message,
                                                sizeof(message), 60000,
                                                &timed_out);
    return !timed_out && rc != 0 && strstr(message, reason) != NULL &&
           stat(out, &sb) != 0 && errno == ENOENT;
}

static bool smt_darwin_has(const uint8_t *b, size_t n, const char *word)
{
    size_t wn = strlen(word);
    if (wn > n)
        return false;
    for (size_t i = 0; i <= n - wn; i++)
        if (memcmp(b + i, word, wn) == 0)
            return true;
    return false;
}

static int smt_t_darwin_types(void)
{
    int failures = 0;
    char dir[1024] = {0}, path[PATH_MAX], changed[PATH_MAX];
    uint8_t *base = NULL, *other = NULL;
    size_t bn = 0, on = 0;
    uint8_t a[32], b[32];
    struct vcs_semantic_facts_info_v1 facts;
    TEST_CASE("semantic_sensor: Darwin canonical types and trustworthy producer") {
        ASSERT(test_mkdtemp(dir, sizeof(dir), "semsensor_darwin") != NULL);
        ASSERT(smt_write(dir, "types.c", k_smt_darwin_types));
        (void)snprintf(path, sizeof(path), "%s/types.bin", dir);
        (void)snprintf(changed, sizeof(changed), "%s/changed.bin", dir);
        ASSERT(smt_darwin_emit(dir, "types.c", path));
        ASSERT(smt_read(path, &base, &bn));
        ASSERT(vcs_semantic_facts_v1_info(base, bn, &facts));
        ASSERT(facts.present && facts.complete);
        ASSERT(memcmp(facts.producer, (uint8_t[32]){0}, 32) != 0);
        ASSERT(smt_darwin_has(base, bn, "const int *"));
        ASSERT(smt_darwin_has(base, bn, "int[3]"));
        ASSERT(smt_darwin_has(base, bn, "int (*)(int)"));
        ASSERT(smt_darwin_has(base, bn, "int (struct pair *)"));
        ASSERT(smt_darwin_has(base, bn, "int (int)"));
        ASSERT(!smt_darwin_has(base, bn, "item_t *"));
        ASSERT(smt_write(dir, "types.c",
                         "typedef long item_t;\n"
                         "struct pair { item_t count; const int *pointer; "
                         "int values[3]; int (*callback)(int); };\n"
                         "int twice(int value) { return value * 2; }\n"
                         "int apply(struct pair *p) { return p->callback(p->count); }\n"));
        ASSERT(smt_darwin_emit(dir, "types.c", changed));
        ASSERT(smt_read(changed, &other, &on));
        ASSERT(vcs_semantic_section_root_v1(base, bn,
                    VCS_SEMANTIC_SECTION_V1_DECLS, a));
        ASSERT(vcs_semantic_section_root_v1(other, on,
                    VCS_SEMANTIC_SECTION_V1_DECLS, b));
        ASSERT(memcmp(a, b, 32) != 0);
        ASSERT(vcs_semantic_facts_v1_info(other, on, &facts));
        ASSERT(facts.present && facts.complete);
    } TEST_END
    free(base);
    free(other);
    if (dir[0] != '\0')
        (void)test_rm_rf_recursive(dir);
    return failures;
}

static int smt_t_darwin_refusals(void)
{
    int failures = 0;
    char dir[1024] = {0}, out[PATH_MAX];
    TEST_CASE("semantic_sensor: Darwin refuses malformed AST without an artifact") {
        ASSERT(test_mkdtemp(dir, sizeof(dir), "semsensor_refuse") != NULL);
        (void)snprintf(out, sizeof(out), "%s/refused.bin", dir);
        ASSERT(smt_write(dir, "malformed.c", "int broken( { return 0; }\n"));
        ASSERT(smt_darwin_refuses(dir, "malformed.c", out,
                                  "no manifest for a TU that does not parse"));
    } TEST_END
    if (dir[0] != '\0')
        (void)test_rm_rf_recursive(dir);
    return failures;
}

static int smt_t_darwin_unsupported(void)
{
    int failures = 0;
    char dir[1024] = {0}, out[PATH_MAX];
    TEST_CASE("semantic_sensor: Darwin refuses unsupported C++ AST without an artifact") {
        const char *argv[] = {SMT_SENSOR, "emit", "--root", dir, "--source",
                              "template.c", "--out", out, "--facts", "--",
                              "-x", "c++", "-std=c++17", NULL};
        char message[4096];
        bool timed_out = false;
        struct stat sb;
        ASSERT(test_mkdtemp(dir, sizeof(dir), "semsensor_unsupported") != NULL);
        (void)snprintf(out, sizeof(out), "%s/unsupported.bin", dir);
        ASSERT(smt_write(dir, "template.c",
                         "template <typename T> T twice(T x) { return x + x; }\n"
                         "int answer() { return twice(21); }\n"));
        int rc = zcl_spawn_capture_merged_observed(argv, message,
                                                    sizeof(message), 60000,
                                                    &timed_out);
        ASSERT(!timed_out && rc != 0);
        ASSERT(strstr(message, "unsupported translation-unit language") != NULL);
        ASSERT(stat(out, &sb) != 0 && errno == ENOENT);
    } TEST_END
    if (dir[0] != '\0')
        (void)test_rm_rf_recursive(dir);
    return failures;
}

static bool smt_darwin_mode_case(const char *dir, const char *source,
                                 const char *body, const char *const flags[4],
                                 bool accepted)
{
    char out[PATH_MAX], message[4096];
    const char *argv[16] = {SMT_SENSOR, "emit", "--root", dir, "--source",
                            source, "--out", out, "--facts", "--"};
    bool timed_out = false, ok;
    struct stat sb;
    int rc;
    size_t n = 10;
    (void)snprintf(out, sizeof(out), "%s/%s.bin", dir, source);
    if (!smt_write(dir, source, body))
        return false;
    for (size_t k = 0; k < 4 && flags[k] != NULL; k++)
        argv[n++] = flags[k];
    argv[n] = NULL;
    rc = zcl_spawn_capture_merged_observed(argv, message, sizeof(message),
                                            60000, &timed_out);
    ok = !timed_out && (accepted ? rc == 0 :
                        rc != 0 && strstr(message,
                            "unsupported translation-unit language") != NULL);
    ok = ok && (accepted ? stat(out, &sb) == 0 :
                stat(out, &sb) != 0 && errno == ENOENT);
    if (!ok)
        printf("FAIL language mode %s: rc=%d message=%s\n", source, rc,
               message);
    return ok;
}

static int smt_t_darwin_language_modes(void)
{
    int failures = 0;
    char dir[1024] = {0}, rsp[PATH_MAX];
    static const struct {
        const char *source;
        const char *flags[4];
        bool accepted;
    } cases[] = {
        {"implicit.c", {NULL}, true},
        {"explicit.c", {"-x", "c"}, true},
        {"header.h", {"-x", "c"}, true},
        {"header_implicit.h", {NULL}, false},
        {"suffix.cpp", {NULL}, false},
        {"suffix_forced.cpp", {"-x", "c"}, true},
        {"macro_cpp.c", {"-x", "c++"}, false},
        {"macro_objc.c", {"-x", "objective-c"}, false},
        {"inline_cpp.c", {"-xc++"}, false},
        {"unknown.c", {"-x", "unknown-language"}, false},
        {"reordered_c.c", {"-x", "c++", "-x", "c"}, true},
        {"reordered_cpp.c", {"-x", "c", "-x", "c++"}, false},
        {"duplicate_c.c", {"-x", "c", "-x", "c"}, true},
        {"reset_c.c", {"-x", "c", "-x", "none"}, true},
    };
    TEST_CASE("semantic_sensor: Darwin admits only proven C invocation modes") {
        ASSERT(test_mkdtemp(dir, sizeof(dir), "semsensor_language") != NULL);
        for (size_t k = 0; k < sizeof(cases) / sizeof(cases[0]); k++)
            ASSERT(smt_darwin_mode_case(dir, cases[k].source,
                                        cases[k].accepted ?
                                        "#define MEANING 42\n"
                                        "int twice(int x) { return x + x; }\n" :
                                        "#define MEANING 42\n",
                                        cases[k].flags,
                                        cases[k].accepted));
        ASSERT(smt_darwin_mode_case(dir, "joined_c.c",
                                    "int f(void) { return 1; }\n",
                                    (const char *const[4]){"-xc"}, true));
        ASSERT(smt_darwin_mode_case(dir, "header_macro.h",
                                    "#define MEANING 42\n",
                                    (const char *const[4]){"-x", "c"}, true));
        ASSERT(smt_darwin_mode_case(dir, "empty.cpp", "",
                                    (const char *const[4]){NULL}, false));
        ASSERT(smt_write(dir, "mode.rsp", "-x c++\n"));
        (void)snprintf(rsp, sizeof(rsp), "@%s/mode.rsp", dir);
        ASSERT(smt_darwin_mode_case(dir, "response.c", "#define X 1\n",
                                    (const char *const[4]){rsp}, false));
        ASSERT(smt_darwin_mode_case(dir, "xclang.c", "#define X 1\n",
                                    (const char *const[4]){
                                        "-Xclang", "-x", "-Xclang", "c++"},
                                    false));
        ASSERT(setenv("CCC_OVERRIDE_OPTIONS", "+-x c++", 1) == 0);
        bool refused = smt_darwin_mode_case(dir, "environment.c",
                                             "#define X 1\n",
                                             (const char *const[4]){NULL},
                                             false);
        (void)unsetenv("CCC_OVERRIDE_OPTIONS");
        ASSERT(refused);
        ASSERT(setenv("CLANG_CONFIG_FILE", "mode.rsp", 1) == 0);
        refused = smt_darwin_mode_case(dir, "driver_config.c",
                                        "#define X 1\n",
                                        (const char *const[4]){NULL}, false);
        (void)unsetenv("CLANG_CONFIG_FILE");
        ASSERT(refused);
    } TEST_END
    (void)unsetenv("CCC_OVERRIDE_OPTIONS");
    (void)unsetenv("CLANG_CONFIG_FILE");
    if (dir[0] != '\0')
        (void)test_rm_rf_recursive(dir);
    return failures;
}

static int smt_t_darwin_mode_identity(void)
{
    int failures = 0;
    char dir[1024] = {0}, out[5][PATH_MAX];
    uint8_t *m[5] = {NULL, NULL, NULL, NULL, NULL}, section[5][32];
    size_t n[5] = {0, 0, 0, 0, 0};
    struct vcs_semantic_facts_info_v1 facts[5];
    const char *standards[5][2] = {
        {"-std=c11", NULL}, {"-std=c23", NULL},
        {"-std=c11", "-std=c23"}, {"-ansi", NULL},
        {"-std=c89", NULL},
    };
    TEST_CASE("semantic_sensor: admitted C dialect changes producer identity") {
        ASSERT(test_mkdtemp(dir, sizeof(dir), "semsensor_modes") != NULL);
        ASSERT(smt_write(dir, "mode.c",
                         "#define SCALE 2\n"
                         "typedef int item_t;\n"
                         "item_t twice(item_t x) { return x * SCALE; }\n"));
        for (size_t k = 0; k < 5; k++) {
            const char *argv[] = {SMT_SENSOR, "emit", "--root", dir,
                                  "--source", "mode.c", "--out", out[k],
                                  "--facts", "--", standards[k][0],
                                  standards[k][1], NULL};
            (void)snprintf(out[k], sizeof(out[k]), "%s/mode_%zu.bin", dir, k);
            ASSERT(smt_spawn(argv));
            ASSERT(smt_read(out[k], &m[k], &n[k]));
            ASSERT(vcs_semantic_facts_v1_info(m[k], n[k], &facts[k]));
            ASSERT(facts[k].present && facts[k].complete);
            ASSERT(vcs_semantic_section_root_v1(m[k], n[k],
                        VCS_SEMANTIC_SECTION_V1_FUNCTIONS, section[k]));
        }
        ASSERT(memcmp(facts[0].producer, facts[1].producer, 32) != 0);
        ASSERT(memcmp(facts[1].producer, facts[2].producer, 32) == 0);
        ASSERT(memcmp(facts[3].producer, facts[4].producer, 32) == 0);
        ASSERT(memcmp(facts[1].producer, facts[3].producer, 32) != 0);
        for (size_t k = 1; k < 5; k++)
            ASSERT(memcmp(section[0], section[k], 32) == 0);
    } TEST_END
    for (size_t k = 0; k < 5; k++)
        free(m[k]);
    if (dir[0] != '\0')
        (void)test_rm_rf_recursive(dir);
    return failures;
}

static int smt_t_darwin_anonymous(void)
{
    int failures = 0;
    char first[1024] = {0}, second[1024] = {0};
    char a_path[PATH_MAX], b_path[PATH_MAX];
    uint8_t *a = NULL, *b = NULL;
    size_t an = 0, bn = 0;
    const char *source = "struct { int member; } anonymous_value;\n";
    TEST_CASE("semantic_sensor: anonymous type spelling is path independent") {
        ASSERT(test_mkdtemp(first, sizeof(first), "semsensor_anon_a") != NULL);
        ASSERT(test_mkdtemp(second, sizeof(second), "semsensor_anon_b") != NULL);
        ASSERT(smt_write(first, "anonymous.c", source));
        ASSERT(smt_write(second, "anonymous.c", source));
        (void)snprintf(a_path, sizeof(a_path), "%s/anon.bin", first);
        (void)snprintf(b_path, sizeof(b_path), "%s/anon.bin", second);
        ASSERT(smt_darwin_emit(first, "anonymous.c", a_path));
        ASSERT(smt_darwin_emit(second, "anonymous.c", b_path));
        ASSERT(smt_read(a_path, &a, &an));
        ASSERT(smt_read(b_path, &b, &bn));
        ASSERT(an == bn && memcmp(a, b, an) == 0);
        ASSERT(!smt_darwin_has(a, an, "(anonymous at "));
        ASSERT(!smt_darwin_has(a, an, "(unnamed at "));
    } TEST_END
    free(a);
    free(b);
    if (first[0] != '\0')
        (void)test_rm_rf_recursive(first);
    if (second[0] != '\0')
        (void)test_rm_rf_recursive(second);
    return failures;
}

static int smt_t_darwin_injected_image(void)
{
    int failures = 0;
    char dir[1024] = {0}, source[PATH_MAX], dylib[2][PATH_MAX];
    char out[2][PATH_MAX];
    uint8_t *manifest[2] = {NULL, NULL};
    size_t length[2] = {0, 0};
    struct vcs_semantic_facts_info_v1 facts[2];
    uint8_t section[2][32];
    TEST_CASE("semantic_sensor: unrelated injected Mach-O bytes bind the producer") {
        ASSERT(test_mkdtemp(dir, sizeof(dir), "semsensor_inject") != NULL);
        ASSERT(smt_write(dir, "types.c", "int twice(int x) { return x * 2; }\n"));
        for (int k = 0; k < 2; k++) {
            char rel[32];
            const char *cc[6];
            (void)snprintf(rel, sizeof(rel), "%c/inject.c", 'a' + k);
            ASSERT(smt_write(dir, rel, k == 0 ?
                             "int injected_marker(void) { return 1; }\n" :
                             "int injected_marker(void) { return 2; }\n"));
            (void)snprintf(source, sizeof(source), "%s/%s", dir, rel);
            (void)snprintf(dylib[k], sizeof(dylib[k]),
                           "%s/%c/libunrelated.dylib", dir, 'a' + k);
            (void)snprintf(out[k], sizeof(out[k]), "%s/%c.bin", dir,
                           'a' + k);
            cc[0] = "/usr/bin/clang";
            cc[1] = "-dynamiclib";
            cc[2] = "-o";
            cc[3] = dylib[k];
            cc[4] = source;
            cc[5] = NULL;
            ASSERT(smt_spawn(cc));
            ASSERT(setenv("DYLD_INSERT_LIBRARIES", dylib[k], 1) == 0);
            bool emitted = smt_darwin_emit(dir, "types.c", out[k]);
            (void)unsetenv("DYLD_INSERT_LIBRARIES");
            ASSERT(emitted);
            ASSERT(smt_read(out[k], &manifest[k], &length[k]));
            ASSERT(vcs_semantic_facts_v1_info(manifest[k], length[k],
                                               &facts[k]));
            ASSERT(facts[k].present && facts[k].complete);
        }
        ASSERT(memcmp(facts[0].producer, facts[1].producer, 32) != 0);
        ASSERT(vcs_semantic_section_root_v1(manifest[0], length[0],
                    VCS_SEMANTIC_SECTION_V1_FUNCTIONS, section[0]));
        ASSERT(vcs_semantic_section_root_v1(manifest[1], length[1],
                    VCS_SEMANTIC_SECTION_V1_FUNCTIONS, section[1]));
        ASSERT(memcmp(section[0], section[1], 32) == 0);
    } TEST_END
    (void)unsetenv("DYLD_INSERT_LIBRARIES");
    free(manifest[0]);
    free(manifest[1]);
    if (dir[0] != '\0')
        (void)test_rm_rf_recursive(dir);
    return failures;
}
#endif

/* semantic_sensor_identity.c: the facts rule's argv and the object compiler. */
int semantic_sensor_identity_tests(void);

int test_semantic_sensor(void)
{
    int failures = 0;
    struct smt_run r = {0};
    struct stat sb;
    if (stat(SMT_SENSOR, &sb) != 0) {
        printf("semantic_sensor: SKIP (%s absent; `make clang-manifest` builds it "
               "where libclang's C API is installed)\n", SMT_SENSOR);
        return 0;
    }
    failures += smt_t_sensor_invariance(&r);
    failures += smt_t_sensor_seeds(&r);
    failures += smt_t_sensor_home_guard();
    failures += smt_t_sensor_language_aliases();
    failures += semantic_sensor_session_cases();
    failures += semantic_sensor_identity_tests();
    failures += smt_t_sensor_static_assert();
    failures += smt_t_sensor_static_assert_facts();
#if defined(__APPLE__)
    failures += smt_t_darwin_types();
    failures += smt_t_darwin_refusals();
    failures += smt_t_darwin_unsupported();
    failures += smt_t_darwin_language_modes();
    failures += smt_t_darwin_mode_identity();
    failures += smt_t_darwin_anonymous();
    failures += smt_t_darwin_injected_image();
#endif
    if (r.out[0] != '\0')
        (void)test_rm_rf_recursive(r.out);
    if (r.root_a[0] != '\0')
        (void)test_rm_rf_recursive(r.root_a);
    if (r.root_b[0] != '\0')
        (void)test_rm_rf_recursive(r.root_b);
    return failures;
}
