/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ACCEPTANCE BAR for the declaration-identity consumer
 * (tools/dev/devloop_facts_consumer.c and its tu/obligations/index/graph
 * parts). Needs no clang: it reads the manifests the semantic_consumer_live
 * group emits, checked in under tests/fixtures/semantic_consumer/, for the
 * five-TU tree in tests/harness/src/semantic_consumer_fixture.c.
 *
 *   table       every edit yields exactly the affected TUs, reasons and
 *               obligation verdict the edit table names: a layout or macro
 *               change reaches only the TU using the struct it sizes, a
 *               macro tested in #if only the TU testing it, a macro used only in another
 *               macro's body only the TU expanding that one, a typedef only
 *               the TU naming it, a comment after every declaration no TU, one
 *               before them every TU whose debug positions move, a signature
 *               the definer and its callers, a static body only its TU (not
 *               the TU with a same-name static), a shadowing header and
 *               flag drift every reader, a seed whose address is taken
 *               the file-seeded obligations, and a struct named only inside
 *               a function body the TU defining that function. The seeds
 *               hold every function the compile may re-emit: a caller that
 *               may inline a changed static is one. A makefile no compile
 *               records reading, or a flag every compile gains, affects
 *               every TU and puts the whole catalog in scope.
 *   mutants     dropping the type closure, the macro closure, the header
 *               position rule, the bare-tag alias, the code-generation
 *               closure or the outsider scan leaves a table-affected TU
 *               unaffected, a required seed out or the whole catalog out
 *               of scope, so each rule is load-bearing.
 *   model       -O0, -O1 and -Og bound the re-emitted code; -O2 and above,
 *               LTO, IPA clone or merge flags and profile feedback do not.
 *   debug       the last -g option sets the debug level; an unknown one
 *               or an unreadable identity is the highest.
 *   fallback    a reader without facts is affected ("facts-missing"); with
 *               no depfile graph the universe is incomplete and the
 *               obligations are exactly the file-seeded plan; a .c-only
 *               change whose seed a header declares falls back too.
 *   identities  every TU with facts carries source, fact, interface and
 *               implementation roots; action and artifact are null with a
 *               reason when their evidence is absent.
 *   command     dev.change.plan with facts names the consumer, the universe
 *               and one page of TU entries, and pages by facts_offset.
 *
 * Do not edit this file to make the implementation pass.
 */

#include "test/test_core.h"

#include "base/safe_alloc.h"
#include "command/native_command.h"
#include "config/command_catalog.h"
#include "json/json.h"
#include "kernel/command_registry.h"
#include "test/semantic_consumer_fixture.h"
#include "test/semantic_facts_fixture.h"

#include "devloop.h"
#include "devloop_facts_index.h"
#include "vcs/semantic_manifest.h"

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#if !defined(_WIN32)
#include <sys/wait.h>
#include <unistd.h>
#endif

struct sct_fixtures {
    uint8_t *m[SCX_VARIANT_COUNT][SCX_TU_COUNT];
    size_t n[SCX_VARIANT_COUNT][SCX_TU_COUNT];
};

static bool sct_load(struct sct_fixtures *f)
{
    for (int v = 0; v < SCX_VARIANT_COUNT; v++) {
        for (size_t tu = 0; tu < SCX_TU_COUNT; tu++) {
            char path[PATH_MAX];
            (void)snprintf(path, sizeof(path), "%s/%s/%s.zsm", SCX_FIXTURES,
                           k_scx_edits[v].name,
                           strrchr(k_scx_tus[tu], '/') + 1);
            if (!sft_read(path, &f->m[v][tu], &f->n[v][tu])) {
                printf("[missing fixture %s] ", path);
                return false;
            }
        }
    }
    return true;
}

static struct scx_evidence sct_evidence(const struct sct_fixtures *f,
                                        enum scx_variant v)
{
    struct scx_evidence ev = {0};
    for (size_t tu = 0; tu < SCX_TU_COUNT; tu++) {
        ev.before[tu] = f->m[k_scx_edits[v].before][tu];
        ev.before_len[tu] = f->n[k_scx_edits[v].before][tu];
        ev.after[tu] = f->m[v][tu];
        ev.after_len[tu] = f->n[v][tu];
    }
    return ev;
}

/* Run variant v in a fresh root; disagreements with the table, or SIZE_MAX
 * when the consumer could not run. */
static size_t sct_run(const struct sct_fixtures *f, enum scx_variant v,
                      const struct scx_evidence *override, size_t *unsafe,
                      FILE *why, struct scx_result *res)
{
    char root[PATH_MAX] = {0};
    struct scx_evidence ev = override ? *override : sct_evidence(f, v);
    size_t bad = SIZE_MAX;
    if (test_mkdtemp(root, sizeof(root), "semconsumer") != NULL &&
        scx_consume(root, v, &ev, res))
        bad = scx_compare(v, res, unsafe, why);
    if (root[0] != '\0')
        (void)test_rm_rf_recursive(root);
    return bad;
}

static int sct_t_table(const struct sct_fixtures *f, struct scx_result *res)
{
    int failures = 0;
    TEST_CASE("semantic_consumer: every edit affects exactly the TUs its declaration identities reach") {
        for (int v = 1; v < SCX_VARIANT_COUNT; v++) {
            if (k_scx_edits[v].pre)
                continue;
            size_t unsafe = 0;
            size_t bad = sct_run(f, (enum scx_variant)v, NULL, &unsafe, stdout,
                                 res);
            scx_result_free(res);
            ASSERT_EQ(bad, (size_t)0);
        }
    } TEST_END
    return failures;
}

/* The table-affected TUs a mutant leaves unaffected, over every variant. */
static size_t sct_mutant_unsafe(const struct sct_fixtures *f,
                                enum zcl_devloop_consumer_mutant m,
                                struct scx_result *res)
{
    size_t total = 0;
    zcl_devloop_test_consumer_mutant = m;
    for (int v = 1; v < SCX_VARIANT_COUNT; v++) {
        if (k_scx_edits[v].pre)
            continue;
        size_t unsafe = 0;
        (void)sct_run(f, (enum scx_variant)v, NULL, &unsafe, NULL, res);
        scx_result_free(res);
        total += unsafe;
    }
    zcl_devloop_test_consumer_mutant = ZCL_DEVLOOP_MUTANT_NONE;
    printf("[mutant %d: %zu table-affected TU(s) missed] ", (int)m, total);
    return total;
}

static int sct_t_mutants(const struct sct_fixtures *f, struct scx_result *res)
{
    int failures = 0;
    TEST_CASE("semantic_consumer: dropping the type, macro, position, tag-alias, code-generation or outsider rule misses an affected TU or seed") {
        ASSERT(sct_mutant_unsafe(f, ZCL_DEVLOOP_MUTANT_NO_TYPE_CLOSURE, res) > 0);
        ASSERT(sct_mutant_unsafe(f, ZCL_DEVLOOP_MUTANT_NO_MACRO_CLOSURE, res) > 0);
        ASSERT(sct_mutant_unsafe(f, ZCL_DEVLOOP_MUTANT_NO_POSITION, res) > 0);
        ASSERT(sct_mutant_unsafe(f, ZCL_DEVLOOP_MUTANT_NO_TAG_ALIAS, res) > 0);
        ASSERT(sct_mutant_unsafe(f, ZCL_DEVLOOP_MUTANT_NO_CODEGEN_CLOSURE, res) > 0);
        ASSERT(sct_mutant_unsafe(f, ZCL_DEVLOOP_MUTANT_NO_OUTSIDER, res) > 0);
        ASSERT_EQ(sct_mutant_unsafe(f, ZCL_DEVLOOP_MUTANT_NONE, res), (size_t)0);
    } TEST_END
    zcl_devloop_test_consumer_mutant = ZCL_DEVLOOP_MUTANT_NONE;
    return failures;
}

static int sct_t_missing(const struct sct_fixtures *f, struct scx_result *res)
{
    int failures = 0;
    struct scx_evidence ev = sct_evidence(f, SCX_LAYOUT);
    const struct zcl_devloop_facts_tu_verdict *t;
    size_t unsafe = 0;
    ev.after[4] = NULL; /* cx_e.c reads the header and has no after facts */
    TEST_CASE("semantic_consumer: a reader without facts is affected and broadened") {
        ASSERT(sct_run(f, SCX_LAYOUT, &ev, &unsafe, NULL, res) != SIZE_MAX);
        ASSERT(res->report.complete);
        t = scx_tu_of(res, SCX_E);
        ASSERT(t != NULL);
        ASSERT(t->affected && t->broadened);
        ASSERT(strcmp(t->reason, "facts-missing") == 0);
        /* another reader keeps its own verdict: at -g1 the compile set
         * only, never broadened by cx_e.c's missing facts */
        t = scx_tu_of(res, SCX_B);
        ASSERT(t != NULL && t->compile_only && !t->broadened);
        ASSERT(strcmp(t->reason, "debug-position") == 0);
    } TEST_END
    scx_result_free(res);
    return failures;
}

static int sct_t_nograph(const struct sct_fixtures *f, struct scx_result *res)
{
    int failures = 0;
    struct scx_evidence ev = sct_evidence(f, SCX_LAYOUT);
    size_t unsafe = 0;
    ev.no_depfiles = true;
    TEST_CASE("semantic_consumer: without the depfile graph the universe is incomplete and the obligations file-seeded") {
        ASSERT(sct_run(f, SCX_LAYOUT, &ev, &unsafe, NULL, res) != SIZE_MAX);
        ASSERT(!res->report.complete);
        ASSERT(res->report.reason != NULL && res->report.reason[0] != '\0');
        ASSERT(!res->verdict.narrowed);
        ASSERT(strcmp(res->verdict.reason, res->report.reason) == 0);
        ASSERT_EQ(res->report.plain_groups,
                  res->plan.path_groups_len + res->plan.closure_groups_len);
    } TEST_END
    scx_result_free(res);
    return failures;
}

/* The .c path: a seed its header declares has readers only the include
 * graph names. Without the graph, and with the reader that takes nothing
 * here (cx_d.c) out of the facts, the plan must not narrow. */
static int sct_t_c_nograph(const struct sct_fixtures *f, struct scx_result *res)
{
    int failures = 0;
    struct scx_evidence ev = sct_evidence(f, SCX_BODY);
    size_t unsafe = 0;
    const char *why;
    ev.no_depfiles = true;
    ev.before[3] = ev.after[3] = NULL;
    TEST_CASE("semantic_consumer: a .c-only change whose seed a header declares falls back without the include graph") {
        ASSERT(sct_run(f, SCX_BODY, &ev, &unsafe, NULL, res) != SIZE_MAX);
        ASSERT(!res->verdict.narrowed);
        why = res->verdict.reason != NULL ? res->verdict.reason : "";
        printf("[fallback: %s] ", why);
        ASSERT(strcmp(why, "indirect-unknown") == 0 ||
               strncmp(why, "include-graph-", 14) == 0 ||
               strcmp(why, "no-code-index") == 0);
    } TEST_END
    scx_result_free(res);
    return failures;
}

static int sct_t_identities(const struct sct_fixtures *f,
                            struct scx_result *res)
{
    int failures = 0;
    static const uint8_t zero[32] = {0};
    size_t unsafe = 0;
    TEST_CASE("semantic_consumer: each TU carries its roots; absent action and artifact evidence is named") {
        ASSERT(sct_run(f, SCX_LAYOUT, NULL, &unsafe, NULL, res) == 0);
        ASSERT_EQ(res->report.ntus, (size_t)SCX_TU_COUNT);
        for (size_t k = 0; k < res->report.ntus; k++) {
            const struct zcl_devloop_facts_tu_verdict *t = &res->report.tus[k];
            ASSERT(t->has_roots);
            ASSERT(memcmp(t->source, zero, 32) != 0);
            ASSERT(memcmp(t->fact, zero, 32) != 0);
            ASSERT(memcmp(t->interface, zero, 32) != 0);
            ASSERT(memcmp(t->implementation, zero, 32) != 0);
            ASSERT(memcmp(t->interface, t->implementation, 32) != 0);
            ASSERT(!t->has_action && !t->has_artifact);
            ASSERT(strcmp(t->action_reason, "action-evidence-absent") == 0);
        }
    } TEST_END
    scx_result_free(res);
    return failures;
}

static bool sct_is_str(const struct json_value *v, const char *s)
{
    return v != NULL && v->type == JSON_STR && strcmp(json_get_str(v), s) == 0;
}

static bool sct_is_int(const struct json_value *v, int64_t n)
{
    return v != NULL && v->type == JSON_INT && json_get_int(v) == n;
}

static bool sct_facts_ok(const struct json_value *facts,
                         const struct json_value *u, int64_t total,
                         int64_t listed)
{
    const struct json_value *complete = u ? json_get(u, "complete") : NULL;
    return u != NULL &&
           sct_is_str(json_get(facts, "consumer"), "zcl.semantic_consumer.v1") &&
           complete != NULL && complete->type == JSON_BOOL &&
           json_get_bool(complete) && sct_is_int(json_get(u, "total"), total) &&
           sct_is_int(json_get(u, "listed"), listed) &&
           json_get(facts, "obligations") != NULL && json_get(facts, "tus") != NULL;
}

#if !defined(_WIN32)
/* dev.change.plan through the real handler in a child that moved to root;
 * 0 when the facts object names the consumer, a complete universe of
 * `total` TUs, and lists `listed` entries from `offset`. */
static int sct_cmd(const char *root, size_t offset, int64_t total,
                   int64_t listed)
{
    int st = 0;
    pid_t pid = fork();
    if (pid == 0) {
        char input[512];
        struct json_value in;
        struct zcl_command_request req;
        struct zcl_command_reply r;
        const struct json_value *facts, *u;
        int rc = 1;
        (void)snprintf(input, sizeof(input),
                       "{\"files\":[\"" SCX_HEADER "\"],\"facts\":\"facts\","
                       "\"facts_offset\":%zu}", offset);
        json_init(&in);
        zcl_command_reply_init(&r, "zcl.dev_plan.v1");
        if (chdir(root) == 0 && json_read(&in, input, strlen(input))) {
            memset(&req, 0, sizeof(req));
            req.input = &in;
            req.spec = zcl_command_registry_find(zcl_command_catalog(),
                                                 "dev.change.plan", NULL);
            zcl_native_handle_dev_change_plan(&req, &r);
            facts = json_get(&r.data, "facts");
            u = facts ? json_get(facts, "universe") : NULL;
            rc = r.status == ZCL_COMMAND_STATUS_PASSED &&
                         sct_facts_ok(facts, u, total, listed)
                     ? 0
                     : 1;
        }
        zcl_command_reply_free(&r);
        json_free(&in);
        _exit(rc);
    }
    if (pid < 0 || waitpid(pid, &st, 0) != pid || !WIFEXITED(st))
        return -1;
    return WEXITSTATUS(st);
}
#endif

static int sct_t_command(const struct sct_fixtures *f, struct scx_result *res)
{
    int failures = 0;
    char root[PATH_MAX] = {0};
    struct scx_evidence ev = sct_evidence(f, SCX_LAYOUT);
    TEST_CASE("semantic_consumer: dev.change.plan names the consumer and pages its universe") {
        ASSERT(test_mkdtemp(root, sizeof(root), "semconsumer_cmd") != NULL);
        ASSERT(scx_consume(root, SCX_LAYOUT, &ev, res));
#if !defined(_WIN32)
        ASSERT_EQ(sct_cmd(root, 0, SCX_TU_COUNT, SCX_TU_COUNT), 0);
        ASSERT_EQ(sct_cmd(root, 3, SCX_TU_COUNT, 2), 0);
        ASSERT_EQ(sct_cmd(root, SCX_TU_COUNT, SCX_TU_COUNT, 0), 0);
#endif
    } TEST_END
    scx_result_free(res);
    if (root[0] != '\0')
        (void)test_rm_rf_recursive(root);
    return failures;
}

/* Builds the exact IDENTITY-record encoding cm_emit_identity in
 * tools/sensors/clang_manifest_core.c writes -- the schema
 * k_sm_schema[VCS_SEMANTIC_SECTION_V1_IDENTITY] == "TQTP[A[D[D[D[e" in
 * contexts/commons/modules/vcs/src/semantic_manifest.c: compiler,
 * resource-dir, triple and main-path texts, a u32 argc and that many argv
 * texts, then three empty directory lists and an empty env list -- from
 * `flags`, a space-separated convenience notation for the argv list (a
 * real command line never glues two flags into one argument, so splitting
 * on spaces here is just test input syntax; each split piece becomes its
 * own length-prefixed argv element, exactly as the real encoder would
 * write it). Calls fxi_codegen_model_of on the built record and frees it,
 * so the model tests below exercise the real wire format -- not a bare,
 * un-length-prefixed string -- including whether "-O"/"--optimize" text
 * glued inside another flag's own argv element (as in -DMODE=-O0,
 * -I/opt/x-O0dir or -Wl,-O1) is correctly ignored as that flag's own text,
 * never as a second, later optimizer flag. */
static enum fxi_codegen sct_codegen_model_of_flags(const char *flags,
                                                   const char **token)
{
    struct vcs_semantic_record_v1 rec = {0};
    char buf[256];
    char *toks[8];
    size_t ntok = 0, n = strlen(flags);
    char *save = NULL, *t;
    enum fxi_codegen got;
    if (n >= sizeof(buf))
        abort(); /* every fixture string below is well under this */
    memcpy(buf, flags, n + 1);
    for (t = strtok_r(buf, " ", &save); t != NULL && ntok < 8;
         t = strtok_r(NULL, " ", &save))
        toks[ntok++] = t;
    vcs_semantic_record_v1_cstr(&rec, "cc");                 /* T: compiler */
    vcs_semantic_record_v1_cstr(&rec, "");                   /* Q: resource_dir */
    vcs_semantic_record_v1_cstr(&rec, "x86_64-pc-linux-gnu"); /* T: triple */
    vcs_semantic_record_v1_cstr(&rec, "a.c");                /* P: main_path */
    vcs_semantic_record_v1_u32(&rec, (uint32_t)ntok);         /* [A: argv */
    for (size_t i = 0; i < ntok; i++)
        vcs_semantic_record_v1_cstr(&rec, toks[i]);
    vcs_semantic_record_v1_u32(&rec, 0); /* [D: quote dirs, empty */
    vcs_semantic_record_v1_u32(&rec, 0); /* [D: angled dirs, empty */
    vcs_semantic_record_v1_u32(&rec, 0); /* [D: ignored dirs, empty */
    vcs_semantic_record_v1_u32(&rec, 0); /* [e: env entries, empty */
    got = fxi_codegen_model_of(rec.bytes, rec.len, token);
    vcs_semantic_record_v1_free(&rec);
    return got;
}

static int sct_t_codegen_model(void)
{
    static const struct {
        const char *flags;
        enum fxi_codegen want;
    } k[] = {
        {"-std=c23 -Wall", FXI_CODEGEN_CALLERS},
        {"-O0 -g", FXI_CODEGEN_CALLERS},
        {"-Og -g", FXI_CODEGEN_COMPONENT},
        {"-O1", FXI_CODEGEN_COMPONENT},
        {"-O", FXI_CODEGEN_COMPONENT},
        {"-O0 -O2", FXI_CODEGEN_UNBOUNDED},
        {"-O3", FXI_CODEGEN_UNBOUNDED},
        {"-Os", FXI_CODEGEN_UNBOUNDED},
        {"-Og -flto", FXI_CODEGEN_UNBOUNDED},
        {"-O1 -fipa-cp", FXI_CODEGEN_UNBOUNDED},
        {"-O1 -fipa-icf", FXI_CODEGEN_UNBOUNDED},
        {"-Og -fprofile-use", FXI_CODEGEN_UNBOUNDED},
    };
    int failures = 0;
    TEST_CASE("semantic_consumer: the optimizer model bounds -O0, -O1 and -Og and refuses -O2 and above, LTO, IPA clones and profile feedback") {
        for (size_t i = 0; i < sizeof(k) / sizeof(k[0]); i++) {
            const char *token = NULL;
            enum fxi_codegen got = sct_codegen_model_of_flags(k[i].flags, &token);
            if (got != k[i].want)
                printf("[%s: model %d, want %d] ", k[i].flags, (int)got,
                       (int)k[i].want);
            ASSERT_EQ((int)got, (int)k[i].want);
            ASSERT(token != NULL);
        }
    } TEST_END
    return failures;
}

/* An IDENTITY record body: four empty texts, then argv (space-separated). */
static size_t sct_identity(const char *argv, uint8_t *out, size_t cap)
{
    size_t at, argc = 0;
    char copy[256];
    memset(out, 0, 20);
    (void)snprintf(copy, sizeof(copy), "%s", argv);
    at = 20;
    for (char *save = NULL, *t = strtok_r(copy, " ", &save); t != NULL;
         t = strtok_r(NULL, " ", &save)) {
        size_t n = strlen(t);
        if (at + 4 + n > cap)
            return 0;
        out[at] = (uint8_t)n;
        out[at + 1] = out[at + 2] = out[at + 3] = 0;
        memcpy(out + at + 4, t, n);
        at += 4 + n;
        argc++;
    }
    out[16] = (uint8_t)argc;
    return at;
}

static int sct_t_debug_level(void)
{
    static const struct {
        const char *argv;
        int want;
    } k[] = {
        {"-std=c23 -O1", 0},
        {"-O1 -g0", 0},
        {"-g -g0", 0},
        {"-g1", 1},
        {"-gline-tables-only", 1},
        {"-g", 2},
        {"-O1 -g -gno-record-gcc-switches", 2},
        {"-gdwarf-4", 2},
        {"-g0 -g", 2},
        {"-g3", 3},
        {"-g3 -g", 3},
        {"-ggdb3 -ggdb", 3},
        {"-g1 -g", 2},
        {"-g3 -g -g2", 2},
        {"-g -fdebug-macro", 3},
        {"-g -gembed-source", 4},
        {"-gembed-source -g1", 4},
        {"-g -gembed-source -gno-embed-source", 2},
        {"-gembed-source -g0", 0},
        {"-gweird-future-flag", 4},
    };
    uint8_t buf[512];
    int failures = 0;
    TEST_CASE("semantic_consumer: the debug level is the last -g option's, 4 with -gembed-source or for one it does not know") {
        for (size_t i = 0; i < sizeof(k) / sizeof(k[0]); i++) {
            size_t n = sct_identity(k[i].argv, buf, sizeof(buf));
            int got = fxi_debug_level_of(buf, n);
            if (got != k[i].want)
                printf("[%s: level %d, want %d] ", k[i].argv, got, k[i].want);
            ASSERT(n > 0);
            ASSERT_EQ(got, k[i].want);
        }
        ASSERT_EQ(fxi_debug_level_of(buf, 7), 4); /* cut: unreadable */
    } TEST_END
    return failures;
}

/* F10: fxg_optimizes read "-O" as a prefix (any non-'0' following char
 * counted, so "-O02" modeled as -O0) and k_fxg_unbounded only named -O2
 * through -O4 literally (so "-O5" fell through to the -O1 model, and
 * "--optimize=N" was never recognized as an -O flag at all). A first fix
 * for that (digits read numerically, --optimize recognized, an
 * unrecognized spelling widening) still applied "last -O/--optimize wins"
 * to the raw identity bytes at any position, not to whole argv tokens, so
 * an "-O0"/"-O1" spelled inside another flag's own text -- -DMODE=-O0,
 * -I/opt/x-O0dir, -Wl,-O1 -- could be mistaken for a later, real optimizer
 * flag and narrow the model when the actual last -O flag was higher. The
 * parser must read digits numerically (leading zeros included), recognize
 * "--optimize"/"--optimize=N", apply the LAST-spelling-wins rule only to
 * whole argv tokens (never to a raw byte position), and widen an
 * unrecognized "-O..." or "--optimize..." spelling instead of narrowing
 * it. */
static int sct_t_codegen_model_optparse(void)
{
    static const struct {
        const char *flags;
        enum fxi_codegen want;
    } k[] = {
        /* Every plain -O<digits> spelling, old model -> new model:
         *   -O0  CALLERS  -> CALLERS  (unchanged)
         *   -O   COMPONENT-> COMPONENT (unchanged: bare -O is -O1)
         *   -O1  COMPONENT-> COMPONENT (unchanged)
         *   -O2  UNBOUNDED-> UNBOUNDED (unchanged: literal in old list)
         *   -O3  UNBOUNDED-> UNBOUNDED (unchanged: literal in old list)
         *   -O4  UNBOUNDED-> UNBOUNDED (unchanged: literal in old list)
         *   -O5  COMPONENT-> UNBOUNDED (F10: old list stopped at -O4, so
         *        -O5 fell through to "-O not followed by 0" == COMPONENT)
         *   -O02 CALLERS  -> UNBOUNDED (F10: old code read "-O" as a
         *        prefix and only inspected the single next byte, so
         *        "-O02"'s '0' made it look like -O0)
         */
        {"-O0", FXI_CODEGEN_CALLERS},
        {"-O", FXI_CODEGEN_COMPONENT},
        {"-O1", FXI_CODEGEN_COMPONENT},
        {"-O2", FXI_CODEGEN_UNBOUNDED},
        {"-O3", FXI_CODEGEN_UNBOUNDED},
        {"-O4", FXI_CODEGEN_UNBOUNDED},
        {"-O5", FXI_CODEGEN_UNBOUNDED},
        {"-O10", FXI_CODEGEN_UNBOUNDED},
        {"-O02", FXI_CODEGEN_UNBOUNDED},
        {"-O00", FXI_CODEGEN_CALLERS},
        /* -Og/-Os/-Oz/-Ofast keep their existing models (old and new
         * agree: all four were named literally in the old unbounded
         * list except -Og, which -O-not-'0' already put at COMPONENT). */
        {"-Og", FXI_CODEGEN_COMPONENT},
        {"-Os", FXI_CODEGEN_UNBOUNDED},
        {"-Oz", FXI_CODEGEN_UNBOUNDED},
        {"-Ofast", FXI_CODEGEN_UNBOUNDED},
        /* --optimize spellings mirror -O; the old parser never recognized
         * any of them (F10), so every one of these was COMPONENT/CALLERS
         * (never optimizes) under the old code regardless of level. */
        {"--optimize", FXI_CODEGEN_COMPONENT},
        {"--optimize=0", FXI_CODEGEN_CALLERS},
        {"--optimize=1", FXI_CODEGEN_COMPONENT},
        {"--optimize=2", FXI_CODEGEN_UNBOUNDED},
        /* The LAST -O/--optimize spelling wins, as in gcc and clang. */
        {"-O2 -O0", FXI_CODEGEN_CALLERS},
        {"-O0 -O2", FXI_CODEGEN_UNBOUNDED},
        {"-O0 -O1", FXI_CODEGEN_COMPONENT},
        {"-Os -O1", FXI_CODEGEN_COMPONENT},
        {"--optimize=2 -O1", FXI_CODEGEN_COMPONENT},
        /* An unrecognized -O/--optimize spelling widens, it never narrows. */
        {"-Ofunky", FXI_CODEGEN_UNBOUNDED},
        {"--optimize-plan", FXI_CODEGEN_UNBOUNDED},
        {"--optimize=x", FXI_CODEGEN_UNBOUNDED},
        /* The unbounded -f flags: unconditional, unbeaten by a later
         * plain -O (order does not matter), and -fipa-cp-clone joins the
         * other IPA clone spellings via the "-fipa-" prefix match. */
        {"-flto", FXI_CODEGEN_UNBOUNDED},
        {"-fwhole-program", FXI_CODEGEN_UNBOUNDED},
        {"-fprofile-use", FXI_CODEGEN_UNBOUNDED},
        {"-fauto-profile", FXI_CODEGEN_UNBOUNDED},
        {"-fipa-cp-clone -O0", FXI_CODEGEN_UNBOUNDED},
        {"-O1 -fipa-cp-clone", FXI_CODEGEN_UNBOUNDED},
        /* A false positive for "last -O wins": text that merely spells an
         * -O flag inside another argv element's OWN value must not be
         * mistaken for a later, real -O flag. The real last flag in each
         * of these three is not an optimizer flag at all, so the model
         * must still reflect the earlier real "-O2" (UNBOUNDED), not the
         * "-O0"/"-O1" glued inside a -D/-I/-Wl value. Each row is built as
         * two separate argv elements (see sct_codegen_model_of_flags): a
         * whole-token match cannot confuse the second element's own text
         * for a spelling, where a raw byte scan across the whole record
         * could. */
        {"-O2 -DMODE=-O0", FXI_CODEGEN_UNBOUNDED},
        {"-O2 -I/opt/x-O0dir", FXI_CODEGEN_UNBOUNDED},
        {"-O2 -Wl,-O1", FXI_CODEGEN_UNBOUNDED},
    };
    int failures = 0;
    TEST_CASE("semantic_consumer: F10 optimizer parsing reads -O/--optimize "
              "digits numerically, applies the last-spelling-wins rule to "
              "whole argv tokens, and widens an unrecognized spelling") {
        for (size_t i = 0; i < sizeof(k) / sizeof(k[0]); i++) {
            const char *token = NULL;
            enum fxi_codegen got = sct_codegen_model_of_flags(k[i].flags, &token);
            if (got != k[i].want)
                printf("[%s: model %d, want %d] ", k[i].flags, (int)got,
                       (int)k[i].want);
            ASSERT_EQ((int)got, (int)k[i].want);
            ASSERT(token != NULL);
        }
    } TEST_END
    return failures;
}

int test_semantic_consumer(void)
{
    int failures = 0;
    struct sct_fixtures *f = zcl_calloc(1, sizeof(*f), "sct.fixtures");
    struct scx_result *res = zcl_calloc(1, sizeof(*res), "sct.result");
    TEST_CASE("semantic_consumer: checked-in fixtures") {
        ASSERT(f != NULL && res != NULL);
        ASSERT(sct_load(f));
    } TEST_END
    if (failures == 0) {
        failures += sct_t_table(f, res);
        failures += sct_t_mutants(f, res);
        failures += sct_t_missing(f, res);
        failures += sct_t_nograph(f, res);
        failures += sct_t_c_nograph(f, res);
        failures += sct_t_identities(f, res);
        failures += sct_t_command(f, res);
        failures += sct_t_codegen_model();
        failures += sct_t_debug_level();
        failures += sct_t_codegen_model_optparse();
    }
    for (int v = 0; f != NULL && v < SCX_VARIANT_COUNT; v++)
        for (size_t tu = 0; tu < SCX_TU_COUNT; tu++)
            free(f->m[v][tu]);
    free(f);
    free(res);
    return failures;
}
