/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ACCEPTANCE BAR for the semantic facts producer: the libclang sensor
 * (build/bin/z23-clang-manifest emit --facts, tools/sensors/) run live on
 * the fixture tree and every edit in tests/harness/src/semantic_facts_fixture.c.
 * The sensor is the only producer of facts manifests.
 *
 *   producers   for every edit the sensor writes a manifest that names its
 *               producer (a nonzero FACTS digest), and a second run over the
 *               same tree writes the same bytes.
 *   verdicts    the narrowing verdict on the live manifests is the one the
 *               edit table names, so the checked-in fixtures the
 *               semantic_facts group reads are representative.
 *   producer    a sensor with one byte appended writes a different producer
 *               digest, and a pair two sensor builds wrote never narrows
 *               ("producer-changed"); the sensor run through a wrapper that
 *               sets argv[0] to another executable still names its own image.
 *   invariance  the same inputs give the same bytes before and after
 *               `git commit` and at two absolute roots.
 *   snapshot    with a ZVCS tree hash the manifest binds that namespace and
 *               its probes carry proved absences; without one, every probe
 *               is UNKNOWN (no snapshot).
 *
 * Self-skips, visibly, where the sensor has not been built
 * (`make clang-manifest`). ZCL_SEMANTIC_FACTS_FIXTURE_OUT=<dir> copies each
 * live manifest there (fixture refresh). Do not edit this file to make the
 * implementation pass.
 */

/* realpath() is declared only under _DEFAULT_SOURCE on glibc without the
 * fortify inline; set it before the first header pulls in <features.h>. */
#if !defined(_WIN32) && !defined(_DEFAULT_SOURCE)
#define _DEFAULT_SOURCE
#endif

#include "test/test_core.h"

#include "base/safe_alloc.h"
#include "sha3/sha3.h"
#include "test/semantic_facts_fixture.h"
#include "vcs/semantic_manifest.h"
#include "vcs/vcs_manifest.h"

#include "devloop.h"

#include <fcntl.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>

#define SFL_SENSOR "build/bin/z23-clang-manifest"
#define SFL_ARGV_MAX 40

struct sfl_run {
    char out[PATH_MAX];    /* manifests and logs */
    char root[PATH_MAX];   /* the tree of the variant being produced */
    char tree_hex[65];     /* "" for no snapshot evidence */
    const char *extra;     /* the variant's extra flag, NULL for none */
    const char *sensor;    /* the sensor to run, NULL for SFL_SENSOR */
};

/* Run argv with the harness cwd, stdout and stderr to `log`. */
static int sfl_spawn(const char *const *argv, const char *log)
{
    pid_t pid = fork();
    int status = 0;
    if (pid < 0) {
        fprintf(stderr, "sfl_spawn: fork failed for %s\n", argv[0]);
        return -1;
    }
    if (pid == 0) {
        int fd = open(log, O_WRONLY | O_CREAT | O_TRUNC, 0600);
        if (fd >= 0) {
            (void)dup2(fd, STDOUT_FILENO);
            (void)dup2(fd, STDERR_FILENO);
            (void)close(fd);
        }
        execvp(argv[0], (char *const *)argv);
        _exit(127);
    }
    if (waitpid(pid, &status, 0) != pid || !WIFEXITED(status)) {
        fprintf(stderr, "sfl_spawn: %s did not exit normally\n", argv[0]);
        return -1;
    }
    return WEXITSTATUS(status);
}

static bool sfl_same(const char *x, const char *y)
{
    uint8_t *a = NULL, *b = NULL;
    size_t an = 0, bn = 0;
    bool same = sft_read(x, &a, &an) && sft_read(y, &b, &bn) && an == bn &&
                memcmp(a, b, an) == 0;
    free(a);
    free(b);
    return same;
}

static void sfl_path(char *buf, size_t n, const struct sfl_run *r,
                     const char *name, const char *ext)
{
    (void)snprintf(buf, n, "%s/%s.%s", r->out, name, ext);
}

/* The sensor: z23-clang-manifest emit ... --facts [caps] [tree] -- flags,
 * writing <out>/<name>.zsm. */
static bool sfl_sensor(const struct sfl_run *r, const char *name,
                       uint32_t max_records)
{
    char out[PATH_MAX], log[PATH_MAX], cap[16];
    const char *argv[SFL_ARGV_MAX];
    size_t k = 0;
    sfl_path(out, sizeof(out), r, name, "zsm");
    sfl_path(log, sizeof(log), r, name, "log");
    (void)snprintf(cap, sizeof(cap), "%u", max_records);
    argv[k++] = r->sensor != NULL ? r->sensor : SFL_SENSOR;
    argv[k++] = "emit";
    argv[k++] = "--root";
    argv[k++] = r->root;
    argv[k++] = "--source";
    argv[k++] = SFT_CORE;
    argv[k++] = "--out";
    argv[k++] = out;
    argv[k++] = "--facts";
    if (max_records > 0) {
        argv[k++] = "--max-records";
        argv[k++] = cap;
    }
    if (r->tree_hex[0]) {
        argv[k++] = "--tree";
        argv[k++] = r->tree_hex;
    }
    argv[k++] = "--";
    if (r->extra != NULL)
        argv[k++] = r->extra;
    for (size_t i = 0; i < k_sft_nflags; i++)
        argv[k++] = k_sft_flags[i];
    argv[k] = NULL;
    return sfl_spawn(argv, log) == 0;
}

/* The manifest at <out>/<name>.zsm names a producer: its FACTS digest is
 * present and nonzero. Copies the digest to `digest` when it is not NULL. */
static bool sfl_named_producer(const struct sfl_run *r, const char *name,
                               uint8_t digest[32])
{
    static const uint8_t zero[32] = {0};
    char path[PATH_MAX];
    uint8_t *m = NULL, *p;
    size_t n = 0;
    bool ok;
    sfl_path(path, sizeof(path), r, name, "zsm");
    ok = sft_read(path, &m, &n);
    p = ok ? sft_producer_at(m, n) : NULL;
    ok = p != NULL && memcmp(p, zero, 32) != 0;
    if (ok && digest != NULL)
        memcpy(digest, p, 32);
    free(m);
    return ok;
}

static void sfl_export(const struct sfl_run *r, const char *name)
{
    const char *dest = getenv("ZCL_SEMANTIC_FACTS_FIXTURE_OUT");
    char src[PATH_MAX], dst[PATH_MAX];
    uint8_t *b = NULL;
    size_t n = 0;
    FILE *fp;
    if (dest == NULL || dest[0] == '\0')
        return;
    sfl_path(src, sizeof(src), r, name, "zsm");
    (void)snprintf(dst, sizeof(dst), "%s/%s.zsm", dest, name);
    if (!sft_read(src, &b, &n))
        return;
    fp = fopen(dst, "wb");
    if (fp == NULL || fwrite(b, 1, n, fp) != n)
        fprintf(stderr, "sfl_export: cannot write %s\n", dst);
    if (fp != NULL && fclose(fp) != 0)
        fprintf(stderr, "sfl_export: cannot close %s\n", dst);
    free(b);
}

/* Produce one variant twice. 0 when both runs succeed, name a producer and
 * write the same bytes. */
static int sfl_produce(struct sfl_run *r, enum sft_variant v)
{
    const struct sft_edit *e = &k_sft_edits[v];
    char first[PATH_MAX], again[PATH_MAX], again_name[128];
    bool ok;
    (void)snprintf(r->root, sizeof(r->root), "%s/tree_%s", r->out, e->name);
    (void)snprintf(again_name, sizeof(again_name), "%s.again", e->name);
    r->extra = e->extra_flag;
    ok = mkdir(r->root, 0700) == 0 &&
         sft_write_tree(r->root, v == SFT_TRUNCATED ? SFT_BASE : v) &&
         sfl_sensor(r, e->name, e->max_records) &&
         sfl_sensor(r, again_name, e->max_records);
    r->extra = NULL;
    if (!ok) {
        printf("FAIL %s: the sensor refused (logs in %s)\n", e->name, r->out);
        return 1;
    }
    sfl_path(first, sizeof(first), r, e->name, "zsm");
    sfl_path(again, sizeof(again), r, again_name, "zsm");
    if (!sfl_named_producer(r, e->name, NULL)) {
        printf("FAIL %s: the manifest names no producer\n", e->name);
        return 1;
    }
    if (!sfl_same(first, again)) {
        printf("FAIL %s: two sensor runs wrote different bytes\n", e->name);
        return 1;
    }
    sfl_export(r, e->name);
    return 0;
}

/* The narrowing verdict for (<before>.zsm, <after>.zsm) where the after side
 * is variant v's edit, planned over base_root; 0 when it is `want`. */
static int sfl_verdict_as(const struct sfl_run *r, const char *base_root,
                          const char *before, enum sft_variant v,
                          const char *after, const char *want)
{
    const struct sft_edit *e = &k_sft_edits[v];
    const char *files[] = {SFT_CORE};
    char bp[PATH_MAX], ap[PATH_MAX];
    struct zcl_devloop_plan *plan = zcl_calloc(1, sizeof(*plan), "sfl.plan");
    struct zcl_devloop_facts_verdict verdict = {.reason = ""};
    struct zcl_devloop_facts_tu tu = {.source = SFT_CORE};
    uint8_t *b = NULL, *a = NULL;
    char *bs = NULL, *as = NULL;
    int bad = 1;
    sfl_path(bp, sizeof(bp), r, before, "zsm");
    sfl_path(ap, sizeof(ap), r, after, "zsm");
    bs = sft_text(SFT_BASE, SFT_CORE, &tu.before_src_len);
    as = sft_text(v == SFT_TRUNCATED ? SFT_BASE : v, SFT_CORE,
                  &tu.after_src_len);
    if (plan != NULL && bs != NULL && as != NULL &&
        sft_read(bp, &b, &tu.before_len) && sft_read(ap, &a, &tu.after_len)) {
        tu.before = b;
        tu.after = a;
        tu.before_src = (const uint8_t *)bs;
        tu.after_src = (const uint8_t *)as;
        bad = !zcl_devloop_plan_files(files, 1, plan) ||
              !zcl_devloop_plan_add_closure_facts(base_root, files, 1, &tu, 1,
                                                  plan, &verdict) ||
              strcmp(verdict.reason, want) != 0;
    }
    if (bad)
        printf("FAIL %s (%s vs %s): live verdict %s (%s), want %s\n", e->name,
               before, after, verdict.reason ? verdict.reason : "(none)",
               verdict.detail, want[0] ? want : "narrowed");
    free(plan);
    free(b);
    free(a);
    free(bs);
    free(as);
    return bad;
}

static int sfl_verdict(const struct sfl_run *r, const char *base_root,
                       enum sft_variant v)
{
    return sfl_verdict_as(r, base_root, "base", v, k_sft_edits[v].name,
                          k_sft_edits[v].reason);
}

static int sfl_t_producers(struct sfl_run *r)
{
    int failures = 0, bad = 0;
    TEST_CASE("semantic_facts_live: the sensor names its producer and writes the same bytes twice") {
        for (int k = 0; k < SFT_VARIANT_COUNT; k++)
            bad += sfl_produce(r, (enum sft_variant)k);
        ASSERT_EQ(bad, 0);
    } TEST_END
    return failures;
}

static int sfl_t_verdicts(struct sfl_run *r)
{
    int failures = 0, bad = 0;
    char base_root[PATH_MAX];
    (void)snprintf(base_root, sizeof(base_root), "%s/tree_base", r->out);
    TEST_CASE("semantic_facts_live: live manifests give the edit table's verdicts") {
        for (int k = SFT_BODY; k < SFT_VARIANT_COUNT; k++)
            bad += sfl_verdict(r, base_root, (enum sft_variant)k);
        ASSERT_EQ(bad, 0);
    } TEST_END
    return failures;
}

/* A copy of the sensor with one byte appended, under the same file name in
 * its own directory: the same code, run the same way, but not the same
 * bytes. */
static bool sfl_sensor_variant(const struct sfl_run *r, char *out, size_t n)
{
    char dir[PATH_MAX];
    uint8_t *b = NULL;
    size_t len = 0;
    FILE *fp;
    bool ok;
    (void)snprintf(dir, sizeof(dir), "%s/variant", r->out);
    (void)snprintf(out, n, "%s/z23-clang-manifest", dir);
    if (mkdir(dir, 0700) != 0 || !sft_read(SFL_SENSOR, &b, &len))
        return false;
    fp = fopen(out, "wb");
    ok = fp != NULL && fwrite(b, 1, len, fp) == len && fputc(0, fp) != EOF;
    if (fp != NULL && fclose(fp) != 0)
        ok = false;
    free(b);
    return ok && chmod(out, 0700) == 0;
}

/* The sensor run through a wrapper script that execs it with argv[0] set
 * to another executable: the producer digest names the image that runs,
 * which argv[0] does not choose. */
static bool sfl_wrapper_names_sensor(struct sfl_run *r)
{
    char wrap[PATH_MAX], sensor[PATH_MAX];
    uint8_t base[32], wrapped[32];
    FILE *fp;
    bool ok;
    if (realpath(SFL_SENSOR, sensor) == NULL)
        return false;
    (void)snprintf(wrap, sizeof(wrap), "%s/wrap.sh", r->out);
    fp = fopen(wrap, "wb");
    if (fp == NULL)
        return false;
    ok = fprintf(fp, "#!/bin/bash\nexec -a /bin/true %s \"$@\"\n", sensor) >
         0;
    ok = fclose(fp) == 0 && ok && chmod(wrap, 0700) == 0;
    (void)snprintf(r->root, sizeof(r->root), "%s/tree_base", r->out);
    r->sensor = wrap;
    ok = ok && sfl_sensor(r, "wrapped", 0);
    r->sensor = NULL;
    return ok && sfl_named_producer(r, "base", base) &&
           sfl_named_producer(r, "wrapped", wrapped) &&
           memcmp(base, wrapped, 32) == 0;
}

static int sfl_t_producer(struct sfl_run *r)
{
    int failures = 0;
    char variant[PATH_MAX], base_root[PATH_MAX];
    uint8_t d0[32], d1[32];
    (void)snprintf(base_root, sizeof(base_root), "%s/tree_base", r->out);
    TEST_CASE("semantic_facts_live: the producer digest names the running image; a pair two sensor builds wrote falls back") {
        /* one sensor on both sides narrows */
        ASSERT_EQ(sfl_verdict_as(r, base_root, "base", SFT_BODY, "body", ""),
                  0);
        /* a sensor with one more byte */
        ASSERT(sfl_sensor_variant(r, variant, sizeof(variant)));
        r->sensor = variant;
        (void)snprintf(r->root, sizeof(r->root), "%s/tree_base", r->out);
        ASSERT(sfl_sensor(r, "variant_base", 0));
        (void)snprintf(r->root, sizeof(r->root), "%s/tree_body", r->out);
        ASSERT(sfl_sensor(r, "variant_body", 0));
        r->sensor = NULL;
        ASSERT(sfl_named_producer(r, "base", d0));
        ASSERT(sfl_named_producer(r, "variant_base", d1));
        ASSERT(memcmp(d0, d1, 32) != 0);
        ASSERT_EQ(sfl_verdict_as(r, base_root, "variant_base", SFT_BODY,
                                 "variant_body", ""),
                  0);
        ASSERT_EQ(sfl_verdict_as(r, base_root, "base", SFT_BODY,
                                 "variant_body", "producer-changed"),
                  0);
        ASSERT_EQ(sfl_verdict_as(r, base_root, "variant_base", SFT_BODY,
                                 "body", "producer-changed"),
                  0);
        /* argv[0] cannot pick the digest */
        ASSERT(sfl_wrapper_names_sensor(r));
    } TEST_END
    r->sensor = NULL;
    return failures;
}

static bool sfl_git(const struct sfl_run *r, const char *a1, const char *a2,
                    const char *a3, const char *a4)
{
    char log[PATH_MAX];
    const char *argv[] = {"git", "-C", r->root, "-c", "user.name=sfl",
                          "-c", "user.email=sfl@example.invalid",
                          "-c", "commit.gpgsign=false",
                          "-c", "core.hooksPath=/dev/null",
                          a1, a2, a3, a4, NULL};
    sfl_path(log, sizeof(log), r, "git", "log");
    return sfl_spawn(argv, log) == 0;
}

static int sfl_t_invariance(struct sfl_run *r)
{
    int failures = 0;
    char a[PATH_MAX], b[PATH_MAX], c[PATH_MAX];
    TEST_CASE("semantic_facts_live: identical manifest at two roots and across git commit") {
        (void)snprintf(r->root, sizeof(r->root), "%s/tree_other", r->out);
        ASSERT(mkdir(r->root, 0700) == 0);
        ASSERT(sft_write_tree(r->root, SFT_BASE));
        ASSERT(sfl_sensor(r, "other_root", 0));
        (void)snprintf(r->root, sizeof(r->root), "%s/tree_base", r->out);
        ASSERT(sfl_git(r, "init", "-q", NULL, NULL));
        ASSERT(sfl_git(r, "add", "-A", NULL, NULL));
        ASSERT(sfl_git(r, "commit", "-q", "-m", "fixture"));
        ASSERT(sfl_sensor(r, "committed", 0));
        sfl_path(a, sizeof(a), r, "base", "zsm");
        sfl_path(b, sizeof(b), r, "other_root", "zsm");
        sfl_path(c, sizeof(c), r, "committed", "zsm");
        ASSERT(sfl_same(a, b));
        ASSERT(sfl_same(a, c));
    } TEST_END
    return failures;
}

/* Add every base fixture file to vm with its ZVCS blob id. */
static bool sfl_add_base_files(struct vcs_manifest *vm)
{
    bool ok = true;
    for (size_t k = 0; ok && k < SFT_FILE_COUNT; k++) {
        size_t n = 0;
        uint8_t blob[32];
        struct sha3_256_ctx h;
        static const uint8_t tag = 0x20;
        char *body = sft_text(SFT_BASE, k_sft_paths[k], &n);
        ok = body != NULL;
        if (ok) {
            sha3_256_init(&h);
            sha3_256_write(&h, &tag, 1);
            sha3_256_write(&h, (const unsigned char *)body, n);
            sha3_256_finalize(&h, blob);
            ok = vcs_manifest_add(vm, k_sft_paths[k], 0100644, n, blob);
        }
        free(body);
    }
    return ok;
}

static bool sfl_mkdir(const char *dir)
{
    return mkdir(dir, 0700) == 0 || access(dir, F_OK) == 0;
}

/* Write wire to <root>/.zvcs/objects/<hex[0:2]>/<hex[2:]>. */
static bool sfl_write_object(const struct sfl_run *r, const uint8_t *wire,
                             size_t len)
{
    char dir[PATH_MAX], obj[PATH_MAX + 80];
    bool ok;
    FILE *fp;
    (void)snprintf(dir, sizeof(dir), "%s/.zvcs", r->root);
    ok = sfl_mkdir(dir);
    (void)snprintf(dir, sizeof(dir), "%s/.zvcs/objects", r->root);
    ok = ok && sfl_mkdir(dir);
    (void)snprintf(dir, sizeof(dir), "%s/.zvcs/objects/%.2s", r->root,
                   r->tree_hex);
    ok = ok && sfl_mkdir(dir);
    (void)snprintf(obj, sizeof(obj), "%s/%s", dir, r->tree_hex + 2);
    fp = ok ? fopen(obj, "wb") : NULL;
    ok = fp != NULL && fwrite(wire, 1, len, fp) == len;
    if (fp != NULL && fclose(fp) != 0)
        ok = false;
    return ok;
}

/* Store the base tree's ZVCS manifest object under <root>/.zvcs/objects. */
static bool sfl_store_snapshot(struct sfl_run *r, uint8_t tree[32])
{
    struct vcs_manifest vm;
    uint8_t *wire = NULL;
    size_t len = 0;
    bool ok;
    vcs_manifest_init(&vm);
    ok = sfl_add_base_files(&vm) && vcs_manifest_serialize(&vm, &wire, &len) &&
         vcs_manifest_tree_hash(&vm, tree);
    vcs_manifest_free(&vm);
    for (int k = 0; ok && k < 32; k++)
        (void)snprintf(r->tree_hex + 2 * k, 3, "%02x", tree[k]);
    ok = ok && sfl_write_object(r, wire, len);
    free(wire);
    return ok;
}

static int sfl_t_snapshot(struct sfl_run *r)
{
    int failures = 0;
    char s[PATH_MAX], plain[PATH_MAX];
    uint8_t tree[32], *m = NULL, *n0 = NULL;
    size_t mn = 0, nn = 0;
    struct vcs_semantic_facts_info_v1 info;
    struct vcs_semantic_diff_v1 d;
    TEST_CASE("semantic_facts_live: snapshot evidence binds the namespace and proves absences") {
        (void)snprintf(r->root, sizeof(r->root), "%s/tree_base", r->out);
        ASSERT(sfl_store_snapshot(r, tree));
        ASSERT(sfl_sensor(r, "snapshot", 0));
        sfl_path(s, sizeof(s), r, "snapshot", "zsm");
        sfl_path(plain, sizeof(plain), r, "base", "zsm");
        ASSERT(sft_read(s, &m, &mn));
        ASSERT(sft_read(plain, &n0, &nn));
        ASSERT(vcs_semantic_facts_v1_info(m, mn, &info));
        ASSERT(memcmp(info.namespace_root, tree, 32) == 0);
        ASSERT(vcs_semantic_manifest_v1_diff(n0, nn, m, mn, &d, NULL, NULL));
        ASSERT((d.changed_sections & (1u << VCS_SEMANTIC_SECTION_V1_PROBES)) != 0);
        ASSERT((d.changed_sections & (1u << VCS_SEMANTIC_SECTION_V1_FACTS)) != 0);
        ASSERT((d.changed_sections & (1u << VCS_SEMANTIC_SECTION_V1_FUNCTIONS)) == 0);
    } TEST_END
    r->tree_hex[0] = '\0';
    free(m);
    free(n0);
    return failures;
}

int test_semantic_facts_live(void)
{
    int failures = 0;
    struct sfl_run r = {0};
    struct stat sb;
    if (stat(SFL_SENSOR, &sb) != 0) {
        printf("semantic_facts_live: SKIP (needs %s from `make clang-manifest`)\n",
               SFL_SENSOR);
        return 0;
    }
    TEST_CASE("semantic_facts_live: scratch") {
        ASSERT(test_mkdtemp(r.out, sizeof(r.out), "semfacts_live") != NULL);
    } TEST_END
    if (failures != 0)
        return failures;
    failures += sfl_t_producers(&r);
    failures += sfl_t_verdicts(&r);
    failures += sfl_t_producer(&r);
    failures += sfl_t_invariance(&r);
    failures += sfl_t_snapshot(&r);
    if (failures == 0)
        (void)test_rm_rf_recursive(r.out);
    return failures;
}
