/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ACCEPTANCE BAR for the semantic facts extension (zcl.semantic_facts.v1),
 * its snapshot namespace evidence, and the facts-narrowed change closure
 * (tools/dev/devloop_facts*.c). Needs no clang: it reads the manifests the
 * live group emits, checked in under tests/fixtures/semantic_facts/, for the
 * fixture tree in tests/harness/src/semantic_facts_fixture.c.
 *
 *   facts        the base manifest carries symbols, direct references, an
 *                address escape, and an UNKNOWN record for the indirect call
 *                and for the inline asm; a two-record producer cap leaves a
 *                valid, non-authoritative manifest with TRUNCATED records.
 *   namespace    absence proved from an immutable ZVCS tree whose hash the
 *                reader re-derives (cross-checked against
 *                vcs_manifest_tree_hash); every case without that evidence
 *                is UNKNOWN with its reason.
 *   narrowing    a body-only edit seeds only its function and reaches fewer
 *                files than the file-seeded closure; every layout, macro,
 *                declaration, file-scope, unknown-effect, address-taken and
 *                truncated pair falls back and names why; a narrowed plan is
 *                never proof-admissible.
 *   fallback     every fallback is exactly the FULL file-seeded plan, never
 *                narrower: header field types, include form, a shadowing
 *                header, a prepended search directory, a constructor, weak,
 *                visibility or C23 attribute on a definition, an unresolved
 *                seed, a forged, zeroed or different FACTS producer digest,
 *                the producer's own source, and stale, foreign, fact-less
 *                or cut-short evidence.
 *   falsify      the edits a narrowing could get wrong: (a) a header struct
 *                layout, (b) a macro body a function expands, (c) a
 *                typedef, (d) a header shadowing another earlier in the
 *                search, before or after the compile, (e) a header among the
 *                changed files in any position, each change the facts or are
 *                refused, and every fallback is exactly the planner's own
 *                plan; (f) comment and whitespace edits change no fact, and
 *                an after manifest whose header or claimed-absent slot
 *                changed on disk is refused as stale.
 *   command      dev.change.plan without "facts" plans exactly as before; a
 *                facts value that is not a confined relative path string is
 *                refused before anything is planned.
 *
 * Do not edit this file to make the implementation pass.
 */

#include "test/test_core.h"

#include "base/safe_alloc.h"
#include "codeindex/codeindex.h"
#include "command/native_command.h"
#include "config/command_catalog.h"
#include "json/json.h"
#include "kernel/command_registry.h"
#include "sha3/sha3.h"
#include "test/semantic_facts_fixture.h"
#include "vcs/semantic_manifest.h"
#include "vcs/semantic_namespace.h"
#include "vcs/vcs_manifest.h"

#include "devloop.h"

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#if !defined(_WIN32)
#include <sys/wait.h>
#include <unistd.h>
#endif

static bool sft_load(enum sft_variant v, uint8_t **m, size_t *n)
{
    char path[PATH_MAX];
    (void)snprintf(path, sizeof(path), "%s/%s.zsm", SFT_FIXTURES,
                   k_sft_edits[v].name);
    return sft_read(path, m, n);
}

/* ── facts ─────────────────────────────────────────────────────────────── */

struct sft_find {
    const char *a, *b;
    uint64_t kind;
    size_t hits;
};

static bool sft_eq(const char *t, size_t n, const char *s)
{
    return n == strlen(s) && memcmp(t, s, n) == 0;
}

/* A REFS or UNKNOWNS record with text[0] == a, num[0] == kind and, when b
 * is set, text[1] == b. */
static bool sft_find_cb(void *ctx, const struct vcs_semantic_fields_v1 *f)
{
    struct sft_find *q = ctx;
    if (f->ntext >= 2 && f->nnum >= 1 && sft_eq(f->text[0], f->text_len[0], q->a) &&
        f->num[0] == q->kind &&
        (q->b == NULL || sft_eq(f->text[1], f->text_len[1], q->b)))
        q->hits++;
    return true;
}

static size_t sft_count(const uint8_t *m, size_t n,
                        enum vcs_semantic_section_v1 s, const char *a,
                        uint64_t kind, const char *b)
{
    struct sft_find q = {.a = a, .b = b, .kind = kind};
    if (!vcs_semantic_section_v1_each(m, n, s, sft_find_cb, &q))
        return SIZE_MAX;
    return q.hits;
}

static int sft_t_facts(void)
{
    int failures = 0;
    uint8_t *m = NULL;
    size_t n = 0;
    struct vcs_semantic_facts_info_v1 info;
    uint32_t count = 0;
    TEST_CASE("semantic_facts: symbols, references and explicit unknown effects") {
        ASSERT(sft_load(SFT_BASE, &m, &n));
        ASSERT(vcs_semantic_manifest_v1_validate(m, n, NULL, 0));
        ASSERT(vcs_semantic_facts_v1_info(m, n, &info));
        ASSERT(info.present);
        ASSERT(info.complete);
        ASSERT(vcs_semantic_section_count_v1(m, n, VCS_SEMANTIC_SECTION_V1_SYMBOLS,
                                             &count));
        ASSERT(count > 0);
        ASSERT_EQ(sft_count(m, n, VCS_SEMANTIC_SECTION_V1_REFS, "f:fx_use",
                            VCS_SEMANTIC_REF_V1_CALL, "f:fx_run"), 1);
        ASSERT_EQ(sft_count(m, n, VCS_SEMANTIC_SECTION_V1_REFS, "f:fx_use",
                            VCS_SEMANTIC_REF_V1_ADDRESS,
                            "f:" SFT_CORE ":fx_cb"), 1);
        ASSERT_EQ(sft_count(m, n, VCS_SEMANTIC_SECTION_V1_REFS, "f:fx_other",
                            VCS_SEMANTIC_REF_V1_VARIABLE,
                            "v:" SFT_CORE ":fx_table"), 1);
        ASSERT_EQ(sft_count(m, n, VCS_SEMANTIC_SECTION_V1_UNKNOWNS, "f:fx_run",
                            VCS_SEMANTIC_UNKNOWN_V1_INDIRECT_CALL, NULL), 1);
        ASSERT_EQ(sft_count(m, n, VCS_SEMANTIC_SECTION_V1_UNKNOWNS, "f:fx_spin",
                            VCS_SEMANTIC_UNKNOWN_V1_INLINE_ASM, NULL), 1);
        ASSERT_EQ(sft_count(m, n, VCS_SEMANTIC_SECTION_V1_UNKNOWNS,
                            "f:fx_helper", VCS_SEMANTIC_UNKNOWN_V1_INDIRECT_CALL,
                            NULL), 0);
    } TEST_END
    free(m);
    return failures;
}

static int sft_t_truncated(void)
{
    int failures = 0;
    uint8_t *m = NULL;
    size_t n = 0;
    uint32_t count = 0;
    struct vcs_semantic_facts_info_v1 info;
    static const enum vcs_semantic_section_v1 capped[] = {
        VCS_SEMANTIC_SECTION_V1_SYMBOLS, VCS_SEMANTIC_SECTION_V1_REFS,
        VCS_SEMANTIC_SECTION_V1_UNKNOWNS, VCS_SEMANTIC_SECTION_V1_PROBES};
    TEST_CASE("semantic_facts: a capped manifest is valid, bounded and non-authoritative") {
        ASSERT(sft_load(SFT_TRUNCATED, &m, &n));
        ASSERT(vcs_semantic_manifest_v1_validate(m, n, NULL, 0));
        ASSERT(vcs_semantic_facts_v1_info(m, n, &info));
        ASSERT(info.present);
        ASSERT(!info.complete);
        ASSERT_EQ(info.max_records, 2u);
        ASSERT(vcs_semantic_section_count_v1(
            m, n, VCS_SEMANTIC_SECTION_V1_TRUNCATED, &count));
        ASSERT(count > 0);
        for (size_t k = 0; k < sizeof(capped) / sizeof(capped[0]); k++) {
            ASSERT(vcs_semantic_section_count_v1(m, n, capped[k], &count));
            ASSERT(count <= 2);
        }
    } TEST_END
    free(m);
    return failures;
}

/* ── namespace ─────────────────────────────────────────────────────────── */

static void sft_blob(const char *body, size_t n, uint8_t out[32])
{
    struct sha3_256_ctx h;
    static const uint8_t tag = 0x20;
    sha3_256_init(&h);
    sha3_256_write(&h, &tag, 1);
    sha3_256_write(&h, (const unsigned char *)body, n);
    sha3_256_finalize(&h, out);
}

static bool sft_snapshot(struct vcs_manifest *vm)
{
    vcs_manifest_init(vm);
    for (size_t k = 0; k < SFT_FILE_COUNT; k++) {
        size_t n = 0;
        uint8_t blob[32];
        char *body = sft_text(SFT_BASE, k_sft_paths[k], &n);
        bool ok = body != NULL;
        if (ok)
            sft_blob(body, n, blob);
        ok = ok && vcs_manifest_add(vm, k_sft_paths[k], 0100644, n, blob);
        free(body);
        if (!ok)
            return false;
    }
    vcs_manifest_sort(vm);
    return true;
}

static int sft_t_namespace(void)
{
    int failures = 0;
    struct vcs_manifest vm;
    struct vcs_semantic_namespace_v1 *ns = NULL, *bad = NULL;
    uint8_t *wire = NULL, tree[32], wrong[32];
    size_t len = 0, n = 0;
    char why[256];
    char *core = NULL;
    TEST_CASE("semantic_facts: absence proved from the snapshot tree, UNKNOWN without it") {
        ASSERT(sft_snapshot(&vm));
        ASSERT(vcs_manifest_serialize(&vm, &wire, &len));
        ASSERT(vcs_manifest_tree_hash(&vm, tree));
        ASSERT(vcs_semantic_namespace_v1_from_wire(wire, len, tree, &ns, why,
                                                   sizeof(why)));
        ASSERT(memcmp(vcs_semantic_namespace_v1_root(ns), tree, 32) == 0);
        ASSERT_EQ(vcs_semantic_namespace_v1_count(ns), (size_t)SFT_FILE_COUNT);
        memcpy(wrong, tree, 32);
        wrong[0] ^= 1;
        ASSERT(!vcs_semantic_namespace_v1_from_wire(wire, len, wrong, &bad, why,
                                                    sizeof(why)));
        /* proved: the includer's own dir holds no fx.h in the snapshot */
        ASSERT_EQ(vcs_semantic_namespace_v1_absent(ns, "engine/modules/fxn/src",
                                                   "fx.h"), 0);
        ASSERT_EQ(vcs_semantic_namespace_v1_absent(NULL, "engine/modules/fxn/src",
                                                   "fx.h"),
                  VCS_SEMANTIC_PROBE_V1_NO_SNAPSHOT);
        ASSERT_EQ(vcs_semantic_namespace_v1_absent(ns, "@sys/usr/include", "fx.h"),
                  VCS_SEMANTIC_PROBE_V1_OUTSIDE);
        ASSERT_EQ(vcs_semantic_namespace_v1_absent(
                      ns, "engine/modules/fxn/include", "fx.h"),
                  VCS_SEMANTIC_PROBE_V1_STALE);
        ASSERT_EQ(vcs_semantic_namespace_v1_absent(ns, SFT_CORE, "x.h"),
                  VCS_SEMANTIC_PROBE_V1_NOT_DIRECTORY);
        ASSERT_EQ(vcs_semantic_namespace_v1_absent(ns, ".", "../x.h"),
                  VCS_SEMANTIC_PROBE_V1_UNRESOLVED);
        core = sft_text(SFT_BASE, SFT_CORE, &n);
        ASSERT(core != NULL);
        ASSERT(vcs_semantic_namespace_v1_binds(ns, SFT_CORE, (const uint8_t *)core,
                                               n));
        core[0] ^= 1;
        ASSERT(!vcs_semantic_namespace_v1_binds(ns, SFT_CORE,
                                                (const uint8_t *)core, n));
    } TEST_END
    free(core);
    free(wire);
    vcs_semantic_namespace_v1_free(ns);
    vcs_semantic_namespace_v1_free(bad);
    vcs_manifest_free(&vm);
    return failures;
}

/* ── narrowing ─────────────────────────────────────────────────────────── */

struct sft_pair {
    uint8_t *before, *after;
    size_t before_len, after_len;
    char *before_src, *after_src;
    size_t before_src_len, after_src_len;
};

static void sft_pair_free(struct sft_pair *p)
{
    free(p->before);
    free(p->after);
    free(p->before_src);
    free(p->after_src);
    memset(p, 0, sizeof(*p));
}

static bool sft_pair_load(enum sft_variant v, struct sft_pair *p)
{
    memset(p, 0, sizeof(*p));
    p->before_src = sft_text(SFT_BASE, SFT_CORE, &p->before_src_len);
    p->after_src = sft_text(v == SFT_TRUNCATED ? SFT_BASE : v, SFT_CORE,
                            &p->after_src_len);
    return p->before_src != NULL && p->after_src != NULL &&
           sft_load(SFT_BASE, &p->before, &p->before_len) &&
           sft_load(v, &p->after, &p->after_len);
}

static struct zcl_devloop_facts_tu sft_tu(const struct sft_pair *p)
{
    return (struct zcl_devloop_facts_tu){
        .source = SFT_CORE,
        .before = p->before,
        .before_len = p->before_len,
        .after = p->after,
        .after_len = p->after_len,
        .before_src = (const uint8_t *)p->before_src,
        .before_src_len = p->before_src_len,
        .after_src = (const uint8_t *)p->after_src,
        .after_src_len = p->after_src_len,
    };
}

/* Put variant v's tree under root, as a real edit leaves the working tree
 * when its after manifest is compiled (restore=false), or put the base tree
 * back and drop any file the variant added (restore=true). */
static bool sft_tree_at(const char *root, enum sft_variant v, bool restore)
{
    const char *added = k_sft_edits[v].add_path;
    char full[PATH_MAX];
    if (!restore)
        return sft_write_tree(root, v == SFT_TRUNCATED ? SFT_BASE : v);
    if (added != NULL) {
        (void)snprintf(full, sizeof(full), "%s/%s", root, added);
        if (remove(full) != 0)
            return false;
    }
    return sft_write_tree(root, SFT_BASE);
}

/* Plan `files` over the fixture root with the given evidence. */
static bool sft_plan(const char *root, const char *file,
                     const struct zcl_devloop_facts_tu *tu, size_t ntu,
                     struct zcl_devloop_plan *plan,
                     struct zcl_devloop_facts_verdict *v)
{
    const char *files[] = {file};
    return zcl_devloop_plan_files(files, 1, plan) &&
           zcl_devloop_plan_add_closure_facts(root, files, 1, tu, ntu, plan, v);
}

static int sft_file_seeded(const char *root)
{
    char changed[1][256] = {SFT_CORE};
    char out[16][256];
    bool truncated = true;
    struct codeindex *ci = codeindex_open(root);
    int n = ci != NULL ? codeindex_impact_closure(ci, changed, 1, 0, out, 16,
                                                  &truncated)
                       : -1;
    if (ci != NULL)
        codeindex_close(ci);
    return truncated ? -1 : n;
}

/* The FULL (file-seeded) plan for `files` over the fixture root: what every
 * fallback must equal exactly, never narrower. */
static bool sft_full_plan(const char *root, const char *const *files,
                          size_t nfiles, struct zcl_devloop_plan *ref)
{
    return zcl_devloop_plan_files(files, nfiles, ref) &&
           zcl_devloop_plan_add_closure(root, files, nfiles, ref);
}

static bool sft_groups_eq(const char (*a)[ZCL_DEVLOOP_GROUP_MAX],
                          const char (*b)[ZCL_DEVLOOP_GROUP_MAX], size_t n)
{
    for (size_t k = 0; k < n; k++)
        if (strcmp(a[k], b[k]) != 0)
            return false;
    return true;
}

static bool sft_same_plan(const struct zcl_devloop_plan *a,
                          const struct zcl_devloop_plan *b)
{
    if (a->path_groups_len != b->path_groups_len ||
        a->closure_groups_len != b->closure_groups_len ||
        a->closure_truncated != b->closure_truncated ||
        a->closure_universal != b->closure_universal ||
        !sft_groups_eq(a->path_groups, b->path_groups, a->path_groups_len) ||
        !sft_groups_eq(a->closure_groups, b->closure_groups,
                       a->closure_groups_len))
        return false;
    for (int d = 0; d < ZCL_DEVLOOP_DIM__COUNT; d++)
        if (a->dims[d].status != b->dims[d].status ||
            strcmp(a->dims[d].reason ? a->dims[d].reason : "",
                   b->dims[d].reason ? b->dims[d].reason : "") != 0)
            return false;
    return true;
}

/* The two plans render the same dev.change.plan document. */
static bool sft_same_json(const struct zcl_devloop_plan *a,
                          const struct zcl_devloop_plan *b,
                          const char *const *files, size_t nfiles)
{
    enum { SFT_JSON_MAX = 1u << 16 };
    char *x = zcl_malloc(SFT_JSON_MAX, "sft.json");
    char *y = zcl_malloc(SFT_JSON_MAX, "sft.json");
    bool same = x != NULL && y != NULL &&
                zcl_devloop_plan_json_render(a, files, nfiles, x,
                                             SFT_JSON_MAX) > 0 &&
                zcl_devloop_plan_json_render(b, files, nfiles, y,
                                             SFT_JSON_MAX) > 0 &&
                strcmp(x, y) == 0;
    free(x);
    free(y);
    return same;
}

/* 0 when a fallback plan for `files` is exactly their FULL plan: the same
 * groups, dimensions and rendered document. */
static int sft_check_full_files(const char *root, const char *const *files,
                                size_t nfiles, const char *name,
                                const struct zcl_devloop_plan *plan)
{
    struct zcl_devloop_plan *ref = zcl_calloc(1, sizeof(*ref), "sft.ref");
    int bad = ref == NULL || !sft_full_plan(root, files, nfiles, ref) ||
              !sft_same_plan(plan, ref) ||
              !sft_same_json(plan, ref, files, nfiles);
    if (bad)
        printf("FAIL %s: the fallback is not the full file-seeded plan\n",
               name);
    free(ref);
    return bad;
}

static int sft_check_full(const char *root, const char *file,
                          const char *name,
                          const struct zcl_devloop_plan *plan)
{
    const char *files[] = {file};
    return sft_check_full_files(root, files, 1, name, plan);
}

/* 0 when a narrowed verdict has the edit's seed and a plan that stays out of
 * proof admission with the SEMANTIC reason "facts-narrowed". */
static int sft_check_narrowed(const struct sft_edit *e,
                              const struct zcl_devloop_facts_verdict *verdict,
                              const struct zcl_devloop_plan *plan)
{
    const char *why = NULL;
    bool one = e->seed != NULL;
    const struct zcl_devloop_dim_state *sem = &plan->dims[ZCL_DEVLOOP_DIM_SEMANTIC];
    int bad = verdict->seeds_len != (one ? 1u : 0u) ||
              (one && strcmp(verdict->seeds[0], e->seed) != 0) ||
              zcl_devloop_plan_proof_admissible(plan, &why) ||
              sem->status != ZCL_DEVLOOP_DIM_INCOMPLETE ||
              strcmp(sem->reason, "facts-narrowed") != 0;
    if (bad)
        printf("FAIL %s: seeds=%zu semantic=%s refusal=%s\n", e->name,
               verdict->seeds_len, sem->reason, why ? why : "(none)");
    return bad;
}

static int sft_check_variant(const char *root, enum sft_variant v,
                             struct zcl_devloop_plan *plan)
{
    const struct sft_edit *e = &k_sft_edits[v];
    struct sft_pair p;
    struct zcl_devloop_facts_verdict verdict;
    struct zcl_devloop_facts_tu tu;
    bool narrow = e->reason[0] == '\0';
    int bad = 0;
    if (!sft_pair_load(v, &p)) {
        printf("FAIL %s: fixture manifests missing\n", e->name);
        return 1;
    }
    tu = sft_tu(&p);
    if (!sft_tree_at(root, v, false)) {
        printf("FAIL %s: cannot write its tree\n", e->name);
        bad = 1;
    } else if (!sft_plan(root, SFT_CORE, &tu, 1, plan, &verdict) ||
        verdict.narrowed != narrow || strcmp(verdict.reason, e->reason) != 0) {
        printf("FAIL %s: narrowed=%d reason=%s (%s), want %s\n", e->name,
               verdict.narrowed, verdict.reason, verdict.detail,
               narrow ? "narrowed" : e->reason);
        bad = 1;
    } else if (narrow) {
        bad = sft_check_narrowed(e, &verdict, plan);
    } else if (strcmp(plan->dims[ZCL_DEVLOOP_DIM_SEMANTIC].reason,
                      "facts-narrowed") == 0) {
        printf("FAIL %s: a fallback kept the narrowed closure\n", e->name);
        bad = 1;
    } else {
        bad = sft_check_full(root, SFT_CORE, e->name, plan);
    }
    if (!sft_tree_at(root, v, true)) {
        printf("FAIL %s: cannot restore the base tree\n", e->name);
        bad = 1;
    }
    sft_pair_free(&p);
    return bad;
}

static int sft_t_narrowing_table(const char *root,
                                 struct zcl_devloop_plan *plan)
{
    int failures = 0, bad = 0;
    TEST_CASE("semantic_facts: every edit narrows or falls back as its evidence says") {
        for (int k = SFT_BODY; k < SFT_VARIANT_COUNT; k++)
            bad += sft_check_variant(root, (enum sft_variant)k, plan);
        ASSERT_EQ(bad, 0);
    } TEST_END
    return failures;
}

static int sft_t_narrowing_fewer(const char *root,
                                 struct zcl_devloop_plan *plan)
{
    int failures = 0;
    struct sft_pair p = {0};
    struct zcl_devloop_facts_verdict v;
    struct zcl_devloop_facts_tu tu;
    int seeded;
    TEST_CASE("semantic_facts: a body-only edit reaches fewer files than the file-seeded closure") {
        seeded = sft_file_seeded(root);
        ASSERT_EQ(seeded, 3); /* fx_core.c, fx_a.c, fx_b.c */
        ASSERT(sft_pair_load(SFT_BODY, &p));
        tu = sft_tu(&p);
        ASSERT(sft_plan(root, SFT_CORE, &tu, 1, plan, &v));
        ASSERT(v.narrowed);
        ASSERT_EQ(v.reached_files, 2u); /* fx_core.c, fx_a.c */
        sft_pair_free(&p);
        ASSERT(sft_pair_load(SFT_COMMENT, &p));
        tu = sft_tu(&p);
        ASSERT(sft_plan(root, SFT_CORE, &tu, 1, plan, &v));
        ASSERT(v.narrowed);
        ASSERT_EQ(v.reached_files, 1u); /* the changed file alone */
    } TEST_END
    sft_pair_free(&p);
    return failures;
}

static int sft_t_narrowing_refusals(const char *root,
                                    struct zcl_devloop_plan *plan)
{
    int failures = 0;
    struct sft_pair p = {0};
    struct zcl_devloop_facts_verdict v;
    struct zcl_devloop_facts_tu tu;
    TEST_CASE("semantic_facts: headers, missing evidence and unbound sources fall back") {
        ASSERT(sft_pair_load(SFT_BODY, &p));
        tu = sft_tu(&p);
        ASSERT(sft_plan(root, SFT_HEADER, &tu, 1, plan, &v));
        ASSERT(!v.narrowed);
        ASSERT_STR_EQ(v.reason, "not-c-source");
        ASSERT(sft_plan(root, SFT_CORE, NULL, 0, plan, &v));
        ASSERT_STR_EQ(v.reason, "no-manifest");
        /* the after manifest describes the edit; the bytes given do not */
        tu.after_src = (const uint8_t *)p.before_src;
        tu.after_src_len = p.before_src_len;
        ASSERT(sft_plan(root, SFT_CORE, &tu, 1, plan, &v));
        ASSERT_STR_EQ(v.reason, "source-mismatch");
        /* an empty manifest is refused before anything is compared */
        tu = sft_tu(&p);
        tu.before_len = 0;
        ASSERT(sft_plan(root, SFT_CORE, &tu, 1, plan, &v));
        ASSERT_STR_EQ(v.reason, "invalid-manifest");
    } TEST_END
    sft_pair_free(&p);
    return failures;
}

/* Plan the body edit with `tu` (a mutated copy of its evidence) for `file`:
 * 0 when it falls back with `want` to exactly the FULL plan. */
static int sft_expect_full(const char *root, const char *file,
                           const struct zcl_devloop_facts_tu *tu,
                           const char *want, struct zcl_devloop_plan *plan)
{
    struct zcl_devloop_facts_verdict v = {.reason = ""};
    if (!sft_plan(root, file, tu, 1, plan, &v) || v.narrowed ||
        strcmp(v.reason, want) != 0) {
        printf("FAIL %s: narrowed=%d reason=%s (%s)\n", want, v.narrowed,
               v.reason, v.detail);
        return 1;
    }
    return sft_check_full(root, file, want, plan);
}

/* The body pair with its FACTS producer digests forged: the first byte of
 * each side xor-ed with before_xor / after_xor, or both zeroed first. */
static int sft_producer_case(const char *root, struct zcl_devloop_plan *plan,
                             int before_xor, int after_xor, bool zero,
                             const char *want)
{
    struct sft_pair p = {0};
    struct zcl_devloop_facts_verdict v = {.reason = ""};
    struct zcl_devloop_facts_tu tu;
    uint8_t *bp, *ap;
    int bad = 1;
    if (!sft_pair_load(SFT_BODY, &p))
        return 1;
    bp = sft_producer_at(p.before, p.before_len);
    ap = sft_producer_at(p.after, p.after_len);
    if (bp != NULL && ap != NULL) {
        if (zero) {
            memset(bp, 0, 32);
            memset(ap, 0, 32);
        }
        bp[0] ^= (uint8_t)before_xor;
        ap[0] ^= (uint8_t)after_xor;
        tu = sft_tu(&p);
        if (want[0] != '\0')
            bad = sft_expect_full(root, SFT_CORE, &tu, want, plan);
        else
            bad = !sft_plan(root, SFT_CORE, &tu, 1, plan, &v) || !v.narrowed;
    }
    if (bad)
        printf("FAIL producer %d/%d/%d: want %s, got %s\n", before_xor,
               after_xor, zero, want[0] ? want : "narrowed", v.reason);
    sft_pair_free(&p);
    return bad;
}

static int sft_t_producer(const char *root, struct zcl_devloop_plan *plan)
{
    int failures = 0;
    struct sft_pair p = {0};
    struct zcl_devloop_facts_tu tu;
    TEST_CASE("semantic_facts: a changed or unnamed producer, or the producer's own source, falls back to the full plan") {
        /* one producer on both sides: the body edit narrows */
        ASSERT_EQ(sft_producer_case(root, plan, 0, 0, false, ""), 0);
        /* one byte of the sensor or of its front end differs */
        ASSERT_EQ(sft_producer_case(root, plan, 0, 1, false,
                                    "producer-changed"),
                  0);
        ASSERT_EQ(sft_producer_case(root, plan, 1, 0, false,
                                    "producer-changed"),
                  0);
        /* the digest is compared, not trusted as a value */
        ASSERT_EQ(sft_producer_case(root, plan, 1, 1, false, ""), 0);
        /* a producer that could not name itself, on either side */
        ASSERT_EQ(sft_producer_case(root, plan, 0, 0, true,
                                    "producer-unknown"),
                  0);
        ASSERT_EQ(sft_producer_case(root, plan, 1, 0, true,
                                    "producer-unknown"),
                  0);
        ASSERT_EQ(sft_producer_case(root, plan, 0, 1, true,
                                    "producer-unknown"),
                  0);
        /* evidence that would narrow, offered for a producer source */
        ASSERT(sft_pair_load(SFT_BODY, &p));
        tu = sft_tu(&p);
        tu.source = "tools/sensors/clang_manifest_producer.c";
        ASSERT_EQ(sft_expect_full(root, tu.source, &tu,
                                  "producer-source-changed", plan),
                  0);
        tu.source = "platform/modules/platform/src/os_proc.c";
        ASSERT_EQ(sft_expect_full(root, tu.source, &tu,
                                  "producer-source-changed", plan),
                  0);
    } TEST_END
    sft_pair_free(&p);
    return failures;
}

/* ── falsification ─────────────────────────────────────────────────────────
 * Each case below is an edit a narrowing could get wrong. It must either
 * show up in the facts (and fall back to the planner's own closure) or be
 * refused outright; only comment and whitespace edits inside the main file
 * may narrow, and they must leave every fact unchanged. */

#define SFT_BIT(s) (1u << VCS_SEMANTIC_SECTION_V1_##s)

/* Sections that differ between the base manifest and variant v. */
static uint32_t sft_changed(enum sft_variant v)
{
    uint8_t *b = NULL, *a = NULL;
    size_t bn = 0, an = 0;
    struct vcs_semantic_diff_v1 d = {0};
    bool ok = sft_load(SFT_BASE, &b, &bn) && sft_load(v, &a, &an) &&
              vcs_semantic_manifest_v1_diff(b, bn, a, an, &d, NULL, NULL);
    free(b);
    free(a);
    return ok ? d.changed_sections : UINT32_MAX;
}

static int sft_t_falsify_facts(void)
{
    int failures = 0;
    uint8_t *m = NULL;
    size_t n = 0;
    uint32_t space = sft_changed(SFT_SPACE), comment = sft_changed(SFT_COMMENT);
    TEST_CASE("semantic_facts: header, macro, typedef and lookup edits change the facts; comments and whitespace do not") {
        /* (a) a public struct gains a field: its layout record changes */
        ASSERT((sft_changed(SFT_LAYOUT) & SFT_BIT(LAYOUTS)) != 0);
        /* (b) a macro body used by fx_helper: the macro record changes, and
         * fx_helper's facts name that exact definition */
        ASSERT((sft_changed(SFT_MACRO) & SFT_BIT(MACROS)) != 0);
        ASSERT(sft_load(SFT_BASE, &m, &n));
        ASSERT_EQ(sft_count(m, n, VCS_SEMANTIC_SECTION_V1_REFS, "f:fx_helper",
                            VCS_SEMANTIC_REF_V1_MACRO,
                            "m:" SFT_HEADER ":FX_SCALE"), 1);
        /* (c) a typedef's type: its declaration record changes */
        ASSERT((sft_changed(SFT_TYPEDEF) & SFT_BIT(DECLS)) != 0);
        /* (d) a header in an earlier search slot: the lookup changes */
        ASSERT((sft_changed(SFT_SHADOW) & SFT_BIT(LOOKUPS)) != 0);
        /* (f) comments, blank lines and whitespace move bytes and positions
         * only: no symbol, reference, declaration or token hash changes */
        ASSERT(comment != UINT32_MAX && space != UINT32_MAX);
        ASSERT_EQ(comment & ~(SFT_BIT(FILES) | SFT_BIT(SPANS)), 0u);
        ASSERT_EQ(space & ~(SFT_BIT(FILES) | SFT_BIT(SPANS)), 0u);
        ASSERT_EQ(sft_changed(SFT_HDRCOMMENT), SFT_BIT(FILES));
    } TEST_END
    free(m);
    return failures;
}

/* 0 when planning `files` with tu falls back as `want` to their FULL plan. */
static int sft_expect_full_files(const char *root, const char *const *files,
                                 size_t nfiles,
                                 const struct zcl_devloop_facts_tu *tu,
                                 const char *want,
                                 struct zcl_devloop_plan *plan)
{
    struct zcl_devloop_facts_verdict v = {.reason = ""};
    if (!zcl_devloop_plan_files(files, nfiles, plan) ||
        !zcl_devloop_plan_add_closure_facts(root, files, nfiles, tu, 1, plan,
                                            &v) ||
        v.narrowed || strcmp(v.reason, want) != 0) {
        printf("FAIL %s: narrowed=%d reason=%s (%s)\n", want, v.narrowed,
               v.reason, v.detail);
        return 1;
    }
    return sft_check_full_files(root, files, nfiles, want, plan);
}

static int sft_t_falsify_header(const char *root,
                                struct zcl_devloop_plan *plan)
{
    int failures = 0;
    struct sft_pair p = {0};
    struct zcl_devloop_facts_tu tu;
    const char *first[] = {SFT_HEADER, SFT_CORE};
    const char *last[] = {SFT_CORE, SFT_HEADER};
    TEST_CASE("semantic_facts: a header among the changed files, first or last, never narrows") {
        /* the header ahead of the source it changes */
        ASSERT(sft_pair_load(SFT_LAYOUT, &p));
        tu = sft_tu(&p);
        ASSERT(sft_tree_at(root, SFT_LAYOUT, false));
        ASSERT_EQ(sft_expect_full_files(root, first, 2, &tu, "not-c-source",
                                        plan),
                  0);
        ASSERT(sft_tree_at(root, SFT_LAYOUT, true));
        /* after a .c whose own pair would narrow */
        sft_pair_free(&p);
        ASSERT(sft_pair_load(SFT_BODY, &p));
        tu = sft_tu(&p);
        ASSERT(sft_tree_at(root, SFT_BODY, false));
        ASSERT_EQ(sft_expect_full_files(root, last, 2, &tu, "not-c-source",
                                        plan),
                  0);
        ASSERT(sft_tree_at(root, SFT_BODY, true));
    } TEST_END
    sft_pair_free(&p);
    return failures;
}

/* The body pair against the tree under root as it is now: "narrowed", or
 * the fallback reason once the plan equals the full plan, or a failure. */
static const char *sft_body_verdict(const char *root,
                                    struct zcl_devloop_plan *plan)
{
    static char reason[64];
    struct sft_pair p = {0};
    struct zcl_devloop_facts_verdict v = {.reason = ""};
    struct zcl_devloop_facts_tu tu;
    (void)snprintf(reason, sizeof(reason), "(no pair)");
    if (sft_pair_load(SFT_BODY, &p)) {
        tu = sft_tu(&p);
        if (!sft_plan(root, SFT_CORE, &tu, 1, plan, &v))
            (void)snprintf(reason, sizeof(reason), "(plan failed)");
        else if (v.narrowed)
            (void)snprintf(reason, sizeof(reason), "narrowed");
        else if (sft_check_full(root, SFT_CORE, v.reason, plan) != 0)
            (void)snprintf(reason, sizeof(reason), "(not the full plan)");
        else
            (void)snprintf(reason, sizeof(reason), "%s", v.reason);
    }
    sft_pair_free(&p);
    return reason;
}

static bool sft_put(const char *root, const char *rel, const char *body)
{
    char full[PATH_MAX];
    FILE *fp;
    bool ok;
    (void)snprintf(full, sizeof(full), "%s/%s", root, rel);
    fp = fopen(full, "wb");
    ok = fp != NULL && fwrite(body, 1, strlen(body), fp) == strlen(body);
    if (fp != NULL && fclose(fp) != 0)
        ok = false;
    return ok;
}

static int sft_t_falsify_stale(const char *root, struct zcl_devloop_plan *plan)
{
    int failures = 0;
    char shadow[PATH_MAX];
    size_t n = 0;
    char *hdr = NULL, *layout = NULL;
    (void)snprintf(shadow, sizeof(shadow), "%s/%s", root, SFT_SHADOW_PATH);
    TEST_CASE("semantic_facts: an after manifest the tree no longer matches never narrows") {
        ASSERT_STR_EQ(sft_body_verdict(root, plan), "narrowed");
        /* (d) a header created after the compile in a slot it saw absent:
         * the manifests are unchanged, the namespace is not */
        hdr = sft_text(SFT_BASE, SFT_HEADER, &n);
        ASSERT(hdr != NULL);
        ASSERT(sft_put(root, SFT_SHADOW_PATH, hdr));
        ASSERT_STR_EQ(sft_body_verdict(root, plan), "after-stale");
        ASSERT(remove(shadow) == 0);
        ASSERT_STR_EQ(sft_body_verdict(root, plan), "narrowed");
        /* (a) an included header edited after the compile */
        layout = sft_text(SFT_LAYOUT, SFT_HEADER, &n);
        ASSERT(layout != NULL);
        ASSERT(sft_put(root, SFT_HEADER, layout));
        ASSERT_STR_EQ(sft_body_verdict(root, plan), "after-stale");
        ASSERT(sft_put(root, SFT_HEADER, hdr));
        ASSERT_STR_EQ(sft_body_verdict(root, plan), "narrowed");
    } TEST_END
    (void)remove(shadow);
    if (hdr != NULL)
        (void)sft_put(root, SFT_HEADER, hdr);
    free(hdr);
    free(layout);
    return failures;
}

static int sft_t_stale(const char *root, struct zcl_devloop_plan *plan)
{
    int failures = 0;
    struct sft_pair p = {0};
    uint8_t *plain = NULL;
    size_t plain_len = 0;
    struct zcl_devloop_facts_tu tu;
    TEST_CASE("semantic_facts: stale, foreign, fact-less or cut-short evidence falls back to the full plan") {
        ASSERT(sft_pair_load(SFT_BODY, &p));
        /* stale: the before bytes moved on after its manifest was written */
        tu = sft_tu(&p);
        tu.before_src = tu.after_src;
        tu.before_src_len = tu.after_src_len;
        ASSERT_EQ(sft_expect_full(root, SFT_CORE, &tu, "source-mismatch",
                                  plan),
                  0);
        /* cut short: the after manifest lost its tail */
        tu = sft_tu(&p);
        tu.after_len = p.after_len / 2;
        ASSERT_EQ(sft_expect_full(root, SFT_CORE, &tu, "invalid-manifest",
                                  plan),
                  0);
        /* foreign: fx_core.c's evidence offered for fx_a.c */
        tu = sft_tu(&p);
        tu.source = SFT_CALLER_A;
        ASSERT_EQ(sft_expect_full(root, SFT_CALLER_A, &tu,
                                  "seed-outside-source", plan),
                  0);
        /* fact-less: a valid manifest written without the facts extension */
        ASSERT(sft_read("tests/fixtures/semantic_manifest/base.bin", &plain,
                        &plain_len));
        tu = sft_tu(&p);
        tu.after = plain;
        tu.after_len = plain_len;
        ASSERT_EQ(sft_expect_full(root, SFT_CORE, &tu, "no-facts", plan), 0);
    } TEST_END
    free(plain);
    sft_pair_free(&p);
    return failures;
}

/* fx_b.c with a second caller of fx_helper, written after the index was. */
static const char k_sft_b_calls_helper[] =
    "#include \"fx.h\"\n"
    "int fx_top_b(void);\n"
    "int fx_top_b(void) { return fx_other(2) + fx_helper(3); }\n";

static int sft_t_resolution(const char *root, struct zcl_devloop_plan *plan)
{
    int failures = 0, bad;
    struct sft_pair p = {0};
    struct zcl_devloop_facts_verdict v = {.reason = ""};
    struct zcl_devloop_facts_tu tu;
    TEST_CASE("semantic_facts: an unresolved seed falls back, and the narrowed walk reads the current callers") {
        ASSERT(sft_pair_load(SFT_BODY, &p));
        tu = sft_tu(&p);
        zcl_devloop_test_facts_unresolved = true;
        bad = sft_expect_full(root, SFT_CORE, &tu, "seed-unresolved", plan);
        zcl_devloop_test_facts_unresolved = false;
        ASSERT_EQ(bad, 0);
        ASSERT(sft_plan(root, SFT_CORE, &tu, 1, plan, &v));
        ASSERT(v.narrowed);
        ASSERT_EQ(v.reached_files, 2u); /* fx_core.c, fx_a.c */
        /* a caller the index has not seen: the walk must not miss it */
        ASSERT(sft_put(root, SFT_CALLER_B, k_sft_b_calls_helper));
        ASSERT(sft_plan(root, SFT_CORE, &tu, 1, plan, &v));
        ASSERT(v.narrowed);
        ASSERT_EQ(v.reached_files, 3u); /* ... and fx_b.c */
    } TEST_END
    zcl_devloop_test_facts_unresolved = false;
    if (!sft_write_tree(root, SFT_BASE))
        failures++;
    sft_pair_free(&p);
    return failures;
}

/* One dev.change.plan call through the real handler. reply is always
 * initialised, so the caller frees it on every path. */
static bool sft_cmd(const char *input, struct zcl_command_reply *reply)
{
    struct json_value in;
    struct zcl_command_request req;
    zcl_command_reply_init(reply, "zcl.dev_plan.v1");
    json_init(&in);
    if (!json_read(&in, input, strlen(input))) {
        json_free(&in);
        return false;
    }
    memset(&req, 0, sizeof(req));
    req.input = &in;
    req.spec = zcl_command_registry_find(zcl_command_catalog(),
                                         "dev.change.plan", NULL);
    zcl_native_handle_dev_change_plan(&req, reply);
    json_free(&in);
    return true;
}

/* A facts value that is not a confined relative path string is refused
 * before anything is planned. */
static bool sft_cmd_refused(const char *input)
{
    struct zcl_command_reply r;
    bool refused = sft_cmd(input, &r) &&
                   r.status == ZCL_COMMAND_STATUS_FAILED &&
                   strcmp(r.error.code, "INVALID_FACTS_DIR") == 0;
    zcl_command_reply_free(&r);
    if (!refused)
        printf("[not refused: %s] ", input);
    return refused;
}

#if !defined(_WIN32)
/* The handler plans in the process cwd, so a call that plans runs in a
 * child that moved to the fixture root. 0 when it passes and carries a
 * "facts" verdict exactly when want_facts. */
static int sft_cmd_plans(const char *root, const char *input, bool want_facts)
{
    int st = 0;
    pid_t pid = fork();
    if (pid == 0) {
        struct zcl_command_reply r;
        int rc = 1;
        if (chdir(root) == 0) {
            rc = sft_cmd(input, &r) && r.status == ZCL_COMMAND_STATUS_PASSED &&
                         (json_get(&r.data, "facts") != NULL) == want_facts
                     ? 0
                     : 1;
            zcl_command_reply_free(&r);
        }
        _exit(rc);
    }
    if (pid < 0 || waitpid(pid, &st, 0) != pid || !WIFEXITED(st))
        return -1;
    return WEXITSTATUS(st);
}
#endif

static int sft_t_plan_command(const char *root)
{
    int failures = 0;
    TEST_CASE("semantic_facts: dev.change.plan plans without facts and refuses an unconfined facts value") {
        ASSERT(sft_cmd_refused("{\"files\":[\"" SFT_CORE "\"],\"facts\":7}"));
        ASSERT(sft_cmd_refused("{\"files\":[\"" SFT_CORE "\"],\"facts\":\"\"}"));
        ASSERT(sft_cmd_refused("{\"files\":[\"" SFT_CORE "\"],\"facts\":\"/facts\"}"));
        ASSERT(sft_cmd_refused("{\"files\":[\"" SFT_CORE "\"],\"facts\":\"a/../b\"}"));
#if !defined(_WIN32)
        ASSERT_EQ(sft_cmd_plans(root, "{\"files\":[\"" SFT_CORE "\"]}", false), 0);
        ASSERT_EQ(sft_cmd_plans(root, "{\"files\":[\"" SFT_CORE "\"],\"facts\":\"nofacts\"}", true), 0);
#else
        (void)root;
#endif
    } TEST_END
    return failures;
}

int test_semantic_facts(void)
{
    int failures = 0;
    char root[PATH_MAX];
    struct zcl_devloop_plan *plan = zcl_calloc(1, sizeof(*plan), "sft.plan");
    failures += sft_t_facts();
    failures += sft_t_truncated();
    failures += sft_t_namespace();
    failures += sft_t_falsify_facts();
    TEST_CASE("semantic_facts: fixture tree") {
        ASSERT(plan != NULL);
        ASSERT(test_mkdtemp(root, sizeof(root), "semfacts") != NULL);
        ASSERT(sft_write_tree(root, SFT_BASE));
    } TEST_END
    if (failures == 0) {
        failures += sft_t_narrowing_table(root, plan);
        failures += sft_t_narrowing_fewer(root, plan);
        failures += sft_t_narrowing_refusals(root, plan);
        failures += sft_t_producer(root, plan);
        failures += sft_t_stale(root, plan);
        failures += sft_t_falsify_header(root, plan);
        failures += sft_t_falsify_stale(root, plan);
        failures += sft_t_resolution(root, plan);
        failures += sft_t_plan_command(root);
        (void)test_rm_rf_recursive(root);
    }
    free(plan);
    return failures;
}
