/* Copyright 2026 Rhett Creighton - Apache License 2.0
 * purpose: Acceptance bar for the early feedback stage of the resident restart proof (tools/dev/devloop_early.c): facts groups run first on the new candidate, as feedback only, and the full plan is unchanged.
 *
 *   skip       no facts directory, a directory outside the checkout, a
 *              missing one and one without evidence each skip the stage
 *              and name why; a skipped stage runs nothing.
 *   receipt    the early_feedback object always says feedback_only, stage
 *              early, and proof_admissible false.
 *   order      on a real compiled and linked candidate the facts groups run
 *              first (--no-cache), then the full plan, whose selected
 *              groups, digests and counts are byte-identical to a run
 *              without the stage.
 *   red        a failing early stage is reported red and the full plan
 *              still runs and completes exactly as before.
 *   missing    a missing facts directory skips the stage in the restart
 *              proof too, with the same full plan.
 *   closure    a group whose input closure is unchanged since its last
 *              early PASS is skipped and counted, with its key; editing a
 *              file in its closure reruns it; a group whose test file reads
 *              the environment always runs; ZCL_DEVLOOP_EARLY_SKIP=off runs
 *              everything; verify mode reruns a skipped group and counts a
 *              failure the skip hid as a false narrow; and the full proof
 *              receipt is byte-identical to a run without the stage every
 *              time, skip or no skip.
 *   holes      every restart source linked into the candidate keys every
 *              group, so editing one the facts never attributed reruns
 *              it; a closure helper (not only the test file) that reads
 *              the environment or opens a computed path, an include flag
 *              the resolver does not model, and #include_next each leave
 *              the group unvouched.
 *
 * Do not edit this file to make the implementation pass. */

#include "test/test_core.h"

#include "devloop.h"
#include "devloop_early.h"
#include "json/json.h"
#include "platform/directory_compat.h"
#include "platform/environment_compat.h"
#include "platform/time_compat.h"
#include "util/safe_alloc.h"

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#ifndef PATH_MAX
#define PATH_MAX 4096
#endif

#define DE_CHANGED "tools/dev/early_fixture.c"
#define DE_LOG_ENV "ZCL_DEVLOOP_EARLY_TEST_LOG"
#define DE_FAIL_ENV "ZCL_DEVLOOP_EARLY_TEST_FAIL"

static bool de_write(const char *root, const char *rel, const char *body)
{
    char full[PATH_MAX];
    if (snprintf(full, sizeof(full), "%s/%s", root, rel) >= (int)sizeof(full))
        return false;
    for (char *p = full + 1; *p; p++) {
        if (*p != '/')
            continue;
        *p = '\0';
        (void)platform_directory_create(full, 0755);
        *p = '/';
    }
    FILE *f = fopen(full, "wb");
    if (!f)
        return false;
    size_t n = strlen(body);
    bool ok = fwrite(body, 1, n, f) == n;
    return fclose(f) == 0 && ok;
}

static char *de_read(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f)
        return NULL;
    char *buf = zcl_calloc(1, 65536, "de.read");
    size_t n = buf ? fread(buf, 1, 65535, f) : 0;
    (void)n;
    fclose(f);
    return buf;
}

static const char *de_json_str(const struct json_value *o, const char *key)
{
    const struct json_value *v = o ? json_get(o, key) : NULL;
    return v ? json_get_str(v) : "";
}

static bool de_json_bool(const struct json_value *o, const char *key,
                         bool want)
{
    const struct json_value *v = o ? json_get(o, key) : NULL;
    return v && v->type == JSON_BOOL && json_get_bool(v) == want;
}

/* The early_feedback object of `r` says feedback, stage early, never
 * admissible, never authority, and names `status` and `reason`. */
static bool de_receipt_is_feedback(const struct zcl_devloop_early_receipt *r,
                                   const char *status, const char *reason)
{
    struct json_value doc;
    json_init(&doc);
    json_set_object(&doc);
    zcl_devloop_early_json(r, &doc);
    const struct json_value *e = json_get(&doc, "early_feedback");
    bool ok = e && strcmp(de_json_str(e, "schema"),
                          ZCL_DEVLOOP_EARLY_SCHEMA) == 0 &&
              strcmp(de_json_str(e, "stage"), "early") == 0 &&
              strcmp(de_json_str(e, "role"), "feedback") == 0 &&
              de_json_bool(e, "feedback_only", true) &&
              de_json_bool(e, "proof_admissible", false) &&
              de_json_bool(e, "receipt_authority", false) &&
              strcmp(de_json_str(e, "status"), status) == 0 &&
              strcmp(de_json_str(e, "reason"), reason) == 0 &&
              json_get(e, "selection") && json_get(e, "result") &&
              json_get(json_get(e, "timing"), "time_to_first_exec_us") &&
              json_get(json_get(e, "timing"), "full_plan_wall_us");
    json_free(&doc);
    return ok;
}

static bool de_skips(const char *root, const char *facts_dir,
                     const char *reason)
{
    const char *changed[] = { DE_CHANGED };
    struct zcl_devloop_early_plan *plan = zcl_calloc(1, sizeof(*plan),
                                                     "de.plan");
    struct zcl_devloop_early_receipt *r = zcl_calloc(1, sizeof(*r), "de.r");
    bool ok = plan && r &&
        zcl_devloop_early_plan_facts(root, changed, 1, facts_dir, 0, plan) &&
        !plan->ready && strcmp(plan->skip_reason, reason) == 0;
    if (ok) {
        zcl_devloop_early_run(root, "/nonexistent/candidate", "", plan, "",
                              platform_time_monotonic_us(), r);
        ok = strcmp(r->status, "skipped") == 0 &&
             strcmp(r->reason, reason) == 0 && r->group_count == 0 &&
             r->first_exec_us == 0 && r->wall_us == 0 &&
             de_receipt_is_feedback(r, "skipped", reason);
    }
    if (!ok)
        printf("[skip %s: got %s] ", reason,
               plan && plan->skip_reason ? plan->skip_reason : "(none)");
    free(plan);
    free(r);
    return ok;
}

static int de_test_skips(void)
{
    int failures = 0;
    TEST("devloop_early: missing, outside, absent or empty facts skip the "
         "stage and name why") {
        char root[PATH_MAX], empty[PATH_MAX], rel[PATH_MAX];
        ASSERT(getcwd(root, sizeof(root)) != NULL);
        test_make_tmpdir(empty, sizeof(empty), "devloop_early", "nofacts");
        ASSERT(strncmp(empty, root, strlen(root)) == 0);
        (void)snprintf(rel, sizeof(rel), "%s", empty + strlen(root) + 1);
        ASSERT(de_skips(root, NULL, "facts_dir_unset"));
        ASSERT(de_skips(root, "", "facts_dir_unset"));
        ASSERT(de_skips(root, "/etc", "facts_dir_invalid"));
        ASSERT(de_skips(root, "build/../..", "facts_dir_invalid"));
        ASSERT(de_skips(root, "test-tmp/devloop_early_never_made",
                        "facts_dir_missing"));
        ASSERT(de_skips(root, rel, "facts_evidence_missing"));
        test_rm_rf_recursive(empty);
        PASS();
    } _test_next:;
    return failures;
}

#if defined(__linux__)
/* ── the restart proof fixture: a real cc compiles and links the changed
 * TU into a candidate whose frozen base logs how it was invoked and prints
 * the suite summary the proof reads. The runner lives in the base, not in
 * the changed TU: every restart source is in every early group's closure,
 * and a runner that reads the environment would leave each unvouched. ── */

static const char k_de_runner[] =
    "#include <stdio.h>\n"
    "#include <stdlib.h>\n"
    "#include <string.h>\n"
    "int main(int argc, char **argv)\n"
    "{\n"
    "    const char *groups = \"\";\n"
    "    int early = 0;\n"
    "    for (int i = 1; i < argc; i++) {\n"
    "        if (strncmp(argv[i], \"--exact=\", 8) == 0) groups = argv[i] + 8;\n"
    "        if (strcmp(argv[i], \"--no-cache\") == 0) early = 1;\n"
    "    }\n"
    "    unsigned count = groups[0] != 0;\n"
    "    for (const char *p = groups; *p; p++) count += *p == ',';\n"
    "    const char *log = getenv(\"" DE_LOG_ENV "\");\n"
    "    FILE *f = log ? fopen(log, \"a\") : NULL;\n"
    "    if (f) { fprintf(f, \"%s %s\\n\", early ? \"early\" : \"proof\", groups); fclose(f); }\n"
    "    const char *fail = getenv(\"" DE_FAIL_ENV "\");\n"
    "    unsigned failed = early && fail && strcmp(fail, \"1\") == 0;\n"
    "    printf(\"SUITE VERDICT mode=cold groups_total=%u groups_ran=%u \"\n"
    "           \"groups_cached=0 groups_gated=0 groups_failed=%u \"\n"
    "           \"self_skips=0\\n\", count, count, failed);\n"
    "    return failed ? 1 : 0;\n"
    "}\n";

struct de_fixture {
    char root[PATH_MAX];
    char log[PATH_MAX];
    char cache[PATH_MAX];
};

static bool de_fixture_files(const struct de_fixture *fx)
{
    static const char hex_b[] =
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
    static const char hex_c[] =
        "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc";
    char env[4096];
    (void)snprintf(env, sizeof(env),
        "CC=cc\nCOMPILER_ID=%s\nBASE_GENERATION=%s\n"
        "DEV_CFLAGS=-DZCL_DEV_BUILD\nDEV_LDFLAGS=-pthread\nDEV_LIBS=-lm\n"
        "DEV_OBJ_DIR=build/dev-obj/fixture\n"
        "DEV_LINK_RSP=build/dev-obj/fixture/link-inputs.rsp\n"
        "DEV_BASE_RELOC=build/dev-obj/fixture/restart-base.o\n"
        "TEST_CFLAGS=-DZCL_TESTING -O0\nTEST_LDFLAGS=-pthread\nTEST_LIBS=-lm\n"
        "TEST_OBJ_DIR=build/test-obj/fixture\n"
        "TEST_LINK_RSP=build/test-obj/fixture/link-inputs.rsp\n"
        "TEST_BASE_RELOC=build/test-obj/fixture/restart-base.o\n",
        hex_b, hex_c);
    return de_write(fx->root, "Makefile", "# fixture\n") &&
        de_write(fx->root, DE_CHANGED,
                 "int early_fixture_changed(void) { return 1; }\n") &&
        de_write(fx->root, "platform/modules/util/src/clientversion.c",
                 "const char *early_identity(void) "
                 "{ return ZCL_BUILD_SOURCE_ID; }\n") &&
        de_write(fx->root, "build/dev-obj/fixture/link-inputs.rsp",
                 "build/dev-obj/fixture/tools/dev/early_fixture.o\n") &&
        de_write(fx->root, "build/dev-obj/fixture/restart-base.o", "dev\n") &&
        de_write(fx->root, "build/test-obj/fixture/link-inputs.rsp",
                 "build/test-obj/fixture/tools/dev/early_fixture.o "
                 "build/test-obj/fixture/platform/modules/util/src/"
                 "clientversion.o\n") &&
        de_write(fx->root, "build/test-obj/fixture/base.c",
                 k_de_runner) &&
        de_write(fx->root, "build/dev-loop/restart.env", env);
}

/* The frozen base is a real relocatable object, as the link expects. */
static bool de_fixture_base(const struct de_fixture *fx)
{
    const char *argv[] = {
        "cc", "-c", "-o", "build/test-obj/fixture/restart-base.o",
        "build/test-obj/fixture/base.c", NULL,
    };
    struct zcl_devloop_process_result *p = zcl_calloc(1, sizeof(*p),
                                                      "de.cc");
    bool ok = p && zcl_devloop_process_run(fx->root, argv, 60000, p) &&
              p->exit_code == 0 && !p->timed_out && !p->term_signal;
    free(p);
    return ok;
}

static bool de_fixture_open(struct de_fixture *fx)
{
    char cwd[PATH_MAX];
    long pid = (long)getpid();
    if (!getcwd(cwd, sizeof(cwd)) ||
        snprintf(fx->root, sizeof(fx->root), "test-tmp/devloop_early_%ld",
                 pid) >= (int)sizeof(fx->root) ||
        snprintf(fx->log, sizeof(fx->log), "%s/test-tmp/devloop_early_%ld.log",
                 cwd, pid) >= (int)sizeof(fx->log) ||
        snprintf(fx->cache, sizeof(fx->cache),
                 "%s/test-tmp/devloop_early_cache_%ld", cwd, pid) >=
            (int)sizeof(fx->cache))
        return false;
    test_rm_rf_recursive(fx->root);
    test_rm_rf_recursive(fx->cache);
    (void)unlink(fx->log);
    return platform_environment_set("ZCL_DEVLOOP_TEST_PROCESS", "1", 1) == 0 &&
           platform_environment_set("ZCL_DEV_ARTIFACT_CACHE", fx->cache, 1) ==
               0 &&
           platform_environment_set(DE_LOG_ENV, fx->log, 1) == 0 &&
           platform_environment_set(DE_FAIL_ENV, "0", 1) == 0 &&
           de_fixture_files(fx) && de_fixture_base(fx);
}

static void de_fixture_close(const struct de_fixture *fx)
{
    test_rm_rf_recursive(fx->root);
    test_rm_rf_recursive(fx->cache);
    (void)unlink(fx->log);
    (void)unsetenv("ZCL_DEVLOOP_TEST_PROCESS");
    (void)unsetenv("ZCL_DEV_ARTIFACT_CACHE");
    (void)unsetenv(DE_LOG_ENV);
    (void)unsetenv(DE_FAIL_ENV);
}

/* The complete, admissible plan the proof runs for DE_CHANGED. */
static bool de_proof_plan(struct zcl_devloop_plan *plan)
{
    const char *changed[] = { DE_CHANGED };
    if (!zcl_devloop_plan_files(changed, 1, plan) || plan->path_groups_len < 2)
        return false;
    for (size_t d = 0; d < ZCL_DEVLOOP_DIM__COUNT; d++)
        plan->dims[d].status = ZCL_DEVLOOP_DIM_NOT_APPLICABLE;
    return zcl_devloop_plan_proof_admissible(plan, NULL);
}

/* A facts-narrowed plan: the dev_platform path group only, SEMANTIC
 * incomplete as the facts walk leaves it, so it is never admissible. */
static bool de_facts_plan(const struct zcl_devloop_plan *proof,
                          struct zcl_devloop_early_plan *early)
{
    size_t at = 0;
    while (at < proof->path_groups_len &&
           strcmp(proof->path_groups[at], "dev_platform") != 0)
        at++;
    if (at == proof->path_groups_len)
        return false;
    memset(early, 0, sizeof(*early));
    early->plan = *proof;
    (void)snprintf(early->plan.path_groups[0],
                   sizeof(early->plan.path_groups[0]), "%s", "dev_platform");
    early->plan.path_groups_len = 1;
    early->plan.closure_groups_len = 0;
    early->plan.dims[ZCL_DEVLOOP_DIM_SEMANTIC].status =
        ZCL_DEVLOOP_DIM_INCOMPLETE;
    early->ready = true;
    early->skip_reason = "";
    early->origin_us = platform_time_monotonic_us();
    return !zcl_devloop_plan_proof_admissible(&early->plan, NULL);
}

/* The selection the early stage must never change: byte-identical. */
static bool de_same_selection(
    const struct zcl_devloop_restart_proof_receipt *a,
    const struct zcl_devloop_restart_proof_receipt *b)
{
    return strcmp(a->groups, b->groups) == 0 &&
           strcmp(a->groups_sha256, b->groups_sha256) == 0 &&
           strcmp(a->deferred_groups, b->deferred_groups) == 0 &&
           strcmp(a->deferred_groups_sha256, b->deferred_groups_sha256) == 0 &&
           strcmp(a->priority_group, b->priority_group) == 0 &&
           strcmp(a->source_cas_sha3, b->source_cas_sha3) == 0;
}

/* The proof outputs the early stage must never change. */
static bool de_same_proof(const struct zcl_devloop_restart_proof_receipt *a,
                          const struct zcl_devloop_restart_proof_receipt *b)
{
    return de_same_selection(a, b) &&
           a->group_count == b->group_count &&
           a->groups_selected == b->groups_selected &&
           a->groups_immediate_selected == b->groups_immediate_selected &&
           a->deferred_group_count == b->deferred_group_count &&
           a->groups_ran == b->groups_ran &&
           a->groups_cached == b->groups_cached &&
           a->groups_failed == b->groups_failed &&
           a->test_processes == b->test_processes &&
           a->proof_complete == b->proof_complete &&
           a->immediate_proof_complete == b->immediate_proof_complete;
}

/* The log's first line is `first` and every later line is a proof run;
 * `proof_lines` of them. */
static bool de_log_is(const struct de_fixture *fx, const char *first,
                      size_t proof_lines)
{
    char *log = de_read(fx->log);
    size_t n = 0;
    bool ok = log != NULL;
    const char *line = log;
    if (ok && first) {
        size_t len = strlen(first);
        ok = strncmp(line, first, len) == 0 && line[len] == '\n';
        line += ok ? len + 1 : 0;
    }
    for (; ok && *line; n++) {
        ok = strncmp(line, "proof ", 6) == 0;
        const char *nl = strchr(line, '\n');
        line = nl ? nl + 1 : line + strlen(line);
    }
    if (!ok || n != proof_lines)
        printf("[log: %s] ", log ? log : "(absent)");
    free(log);
    (void)unlink(fx->log);
    return ok && n == proof_lines;
}

struct de_state {
    struct de_fixture fx;
    struct zcl_devloop_plan proof_plan;
    struct zcl_devloop_early_plan early_plan;
    struct zcl_devloop_restart_proof_receipt base, with;
    struct zcl_devloop_early_receipt early;
    struct zcl_devloop_early_skip hole;
    struct zcl_devloop_process_result process;
    char why[512];
    char early_line[4096 + 8];
};

static bool de_prove(struct de_state *s,
                     const struct zcl_devloop_early_plan *early_plan)
{
    const char *changed[] = { DE_CHANGED };
    memset(&s->with, 0, sizeof(s->with));
    memset(&s->early, 0, sizeof(s->early));
    s->why[0] = 0;
    bool ok = zcl_devloop_restart_prove_early(
        s->fx.root, changed, 1, &s->proof_plan, early_plan, &s->with,
        &s->early, &s->process, s->why, sizeof(s->why));
    if (!ok)
        printf("[prove: %s] ", s->why);
    if (s->early.reason && s->early.reason[0])
        printf("[early %s: %s %s] ", s->early.status, s->early.reason,
               s->early.detail);
    return ok;
}

static int de_test_order(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: the facts groups run first on the new candidate, "
         "then the unchanged full plan") {
        const char *changed[] = { DE_CHANGED };
        ASSERT(zcl_devloop_restart_prove(s->fx.root, changed, 1,
                                         &s->proof_plan, &s->base,
                                         &s->process, s->why,
                                         sizeof(s->why)));
        ASSERT(s->base.proof_complete);
        ASSERT(s->base.test_processes >= 1);
        ASSERT(de_log_is(&s->fx, NULL, s->base.test_processes));

        ASSERT(de_facts_plan(&s->proof_plan, &s->early_plan));
        ASSERT(de_prove(s, &s->early_plan));
        ASSERT_STR_EQ(s->early.status, "green");
        ASSERT_STR_EQ(s->early.reason, "");
        ASSERT(s->early.group_count >= 1);
        ASSERT(s->early.group_count < s->with.group_count);
        ASSERT(strcmp(s->early.groups, s->with.groups) != 0);
        ASSERT_EQ(s->early.groups_ran, s->early.group_count);
        ASSERT(s->early.origin_is_edit);
        ASSERT(s->early.first_exec_us > 0);
        ASSERT(s->early.wall_us > 0);
        ASSERT(s->early.full_first_exec_us >=
               s->early.first_exec_us + s->early.wall_us);
        ASSERT(s->early.full_wall_us > 0);
        printf("[edit->early first exec %lld us, early wall %lld us, "
               "edit->full first exec %lld us, full wall %lld us] ",
               (long long)s->early.first_exec_us, (long long)s->early.wall_us,
               (long long)s->early.full_first_exec_us,
               (long long)s->early.full_wall_us);
        ASSERT_STR_EQ(s->early.artifact_sha256, s->with.artifact_sha256);
        (void)snprintf(s->early_line, sizeof(s->early_line), "early %s",
                       s->early.groups);
        ASSERT(de_log_is(&s->fx, s->early_line, s->with.test_processes));
        ASSERT(de_same_proof(&s->base, &s->with));
        ASSERT(de_receipt_is_feedback(&s->early, "green", ""));
        PASS();
    } _test_next:;
    return failures;
}

static int de_test_red(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: a red early stage is reported and the full plan "
         "still runs exactly as before") {
        ASSERT(platform_environment_set(DE_FAIL_ENV, "1", 1) == 0);
        s->early_plan.origin_us = platform_time_monotonic_us();
        bool proved = de_prove(s, &s->early_plan);
        ASSERT(platform_environment_set(DE_FAIL_ENV, "0", 1) == 0);
        ASSERT(proved);
        ASSERT_STR_EQ(s->early.status, "red");
        ASSERT_STR_EQ(s->early.reason, "groups_failed");
        ASSERT_EQ(s->early.groups_failed, 1u);
        ASSERT(s->with.proof_complete);
        ASSERT(de_log_is(&s->fx, s->early_line, s->with.test_processes));
        ASSERT(de_same_proof(&s->base, &s->with));
        ASSERT(de_receipt_is_feedback(&s->early, "red", "groups_failed"));
        PASS();
    } _test_next:;
    return failures;
}

static int de_test_missing(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: a missing facts directory skips the stage in the "
         "restart proof with the same full plan") {
        const char *changed[] = { DE_CHANGED };
        ASSERT(zcl_devloop_early_plan_facts(s->fx.root, changed, 1,
                                            "build/no-facts-here", 0,
                                            &s->early_plan));
        ASSERT(!s->early_plan.ready);
        ASSERT(de_prove(s, &s->early_plan));
        ASSERT_STR_EQ(s->early.status, "skipped");
        ASSERT_STR_EQ(s->early.reason, "facts_dir_missing");
        ASSERT_EQ(s->early.group_count, 0u);
        ASSERT(de_log_is(&s->fx, NULL, s->with.test_processes));
        ASSERT(de_same_proof(&s->base, &s->with));
        ASSERT(de_prove(s, NULL));
        ASSERT_STR_EQ(s->early.reason, "facts_dir_unset");
        ASSERT(de_log_is(&s->fx, NULL, s->with.test_processes));
        ASSERT(de_same_proof(&s->base, &s->with));
        ASSERT(de_receipt_is_feedback(&s->early, "skipped",
                                      "facts_dir_unset"));
        PASS();
    } _test_next:;
    return failures;
}

/* ── closure-unchanged skipping (tools/dev/devloop_early_skip.c) ─────── */

#define DE_SKIP_ENV "ZCL_DEVLOOP_EARLY_SKIP"
#define DE_VOUCHED "test_devloop_early"
#define DE_UNVOUCHED "test_devagent_ticketkey"
#define DE_DEP_H "tests/harness/src/early_skip_dep.h"

/* A facts-narrowed plan naming `n` path groups, never admissible. */
static bool de_skip_plan(const struct zcl_devloop_plan *proof,
                         const char *const *groups, size_t n,
                         struct zcl_devloop_early_plan *early)
{
    memset(early, 0, sizeof(*early));
    early->plan = *proof;
    for (size_t i = 0; i < n; i++)
        (void)snprintf(early->plan.path_groups[i],
                       sizeof(early->plan.path_groups[i]), "%s", groups[i]);
    early->plan.path_groups_len = n;
    early->plan.closure_groups_len = 0;
    early->plan.dims[ZCL_DEVLOOP_DIM_SEMANTIC].status =
        ZCL_DEVLOOP_DIM_INCOMPLETE;
    early->ready = true;
    early->skip_reason = "";
    early->origin_us = platform_time_monotonic_us();
    return !zcl_devloop_plan_proof_admissible(&early->plan, NULL);
}

/* The vouched group's test file includes a header beside it; the other
 * group's test file reads the environment, which no key names. */
static bool de_skip_files(const struct de_fixture *fx, const char *dep)
{
    return de_write(fx->root, "tests/harness/src/" DE_VOUCHED ".c",
                    "#include \"early_skip_dep.h\"\n"
                    "int early_skip_fixture_group = EARLY_SKIP_DEP;\n") &&
           de_write(fx->root, DE_DEP_H, dep) &&
           de_write(fx->root, "tests/harness/src/" DE_UNVOUCHED ".c",
                    "#include <stdlib.h>\n"
                    "const char *early_skip_env(void)\n"
                    "{ return getenv(\"EARLY_SKIP_FIXTURE\"); }\n");
}

/* A fresh full proof with no early stage, over the tree as it is now: the
 * receipt every later run must reproduce byte for byte. */
static bool de_skip_base(struct de_state *s)
{
    const char *changed[] = { DE_CHANGED };
    bool ok = zcl_devloop_restart_prove(s->fx.root, changed, 1,
                                        &s->proof_plan, &s->base, &s->process,
                                        s->why, sizeof(s->why)) &&
              s->base.proof_complete;
    (void)unlink(s->fx.log);
    return ok;
}

static const struct zcl_devloop_early_skip_row *de_row(
    const struct zcl_devloop_early_receipt *r, const char *group)
{
    for (size_t i = 0; i < r->skip.n; i++)
        if (strcmp(r->skip.rows[i].group, group) == 0)
            return &r->skip.rows[i];
    return NULL;
}

static bool de_row_is(const struct zcl_devloop_early_receipt *r,
                      const char *group, const char *reason, bool skip)
{
    const struct zcl_devloop_early_skip_row *row = de_row(r, group);
    bool ok = row && row->reason && strcmp(row->reason, reason) == 0 &&
              row->skip == skip;
    if (!ok)
        printf("[row %s: %s %s] ", group,
               row && row->reason ? row->reason : "(none)",
               row ? row->detail : "");
    return ok;
}

static int64_t de_json_int(const struct json_value *o, const char *key)
{
    const struct json_value *v = o ? json_get(o, key) : NULL;
    return v ? json_get_int(v) : -1;
}

/* The early_feedback counters say `run` ran and `skipped` were skipped as
 * closure-unchanged, and the skipped row names its key. */
static bool de_skip_json(const struct zcl_devloop_early_receipt *r,
                         int64_t run, int64_t skipped)
{
    struct json_value doc;
    json_init(&doc);
    json_set_object(&doc);
    zcl_devloop_early_json(r, &doc);
    const struct json_value *e = json_get(&doc, "early_feedback");
    const struct json_value *result = e ? json_get(e, "result") : NULL;
    const struct json_value *timing = e ? json_get(e, "timing") : NULL;
    const struct json_value *cs = e ? json_get(e, "closure_skip") : NULL;
    bool ok = de_json_int(result, "groups_selected") == r->group_count &&
              de_json_int(result, "groups_run") == run &&
              de_json_int(result, "groups_skipped_closure_unchanged") ==
                  skipped &&
              de_json_int(cs, "groups_skipped_closure_unchanged") ==
                  skipped &&
              (skipped == 0 ||
               de_json_int(timing, "estimated_wall_saved_us") > 0) &&
              json_get(cs, "groups") && json_get(cs, "verify");
    json_free(&doc);
    return ok;
}

static bool de_store_sealed(const struct de_fixture *fx)
{
    char path[PATH_MAX], temp[PATH_MAX + 32];
    (void)snprintf(path, sizeof(path), "%s/build/dev-loop/early-skip.v1.tsv",
                   fx->root);
    (void)snprintf(temp, sizeof(temp), "%s.%ld.tmp", path, (long)getpid());
    char *text = de_read(path);
    bool ok = text && strncmp(text, "zcl.dev_early_skip_store.v1\n", 28) == 0 &&
              access(temp, F_OK) != 0;
    free(text);
    return ok;
}

static bool de_skip_setup(struct de_state *s)
{
    char store[PATH_MAX];
    const char *groups[] = { "devloop_early", "devagent_ticketkey" };
    (void)snprintf(store, sizeof(store),
                   "%s/build/dev-loop/early-skip.v1.tsv", s->fx.root);
    (void)unlink(store);
    return platform_environment_set(DE_SKIP_ENV, "on", 1) == 0 &&
           de_skip_files(&s->fx, "#define EARLY_SKIP_DEP 1\n") &&
           de_skip_base(s) &&
           de_skip_plan(&s->proof_plan, groups, 2, &s->early_plan);
}

static int de_test_skip_unchanged(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: an unchanged closure skips its group on the second "
         "run and counts it; an unvouched group always runs") {
        ASSERT(de_skip_setup(s));
        ASSERT(de_prove(s, &s->early_plan));
        ASSERT_STR_EQ(s->early.status, "green");
        ASSERT_EQ(s->early.group_count, 2u);
        ASSERT_EQ(s->early.run_count, 2u);
        ASSERT(de_row_is(&s->early, DE_VOUCHED, "no-record", false));
        ASSERT(de_row_is(&s->early, DE_UNVOUCHED, "unvouched", false));
        ASSERT(strstr(de_row(&s->early, DE_UNVOUCHED)->detail,
                      "reads-environment") != NULL);
        ASSERT_STR_EQ(s->early.skip.record_state, "written");
        ASSERT_EQ(s->early.skip.records_written, 1u);
        ASSERT(de_store_sealed(&s->fx));
        char first_key[65];
        (void)snprintf(first_key, sizeof(first_key), "%s",
                       de_row(&s->early, DE_VOUCHED)->key);
        ASSERT_EQ(strlen(first_key), 64u);
        ASSERT(de_same_proof(&s->base, &s->with));
        (void)unlink(s->fx.log);

        s->early_plan.origin_us = platform_time_monotonic_us();
        ASSERT(de_prove(s, &s->early_plan));
        ASSERT_STR_EQ(s->early.status, "green");
        ASSERT_EQ(s->early.run_count, 1u);
        ASSERT_EQ(s->early.skip.groups_skipped, 1u);
        ASSERT(de_row_is(&s->early, DE_VOUCHED, "closure-unchanged", true));
        ASSERT_STR_EQ(de_row(&s->early, DE_VOUCHED)->key, first_key);
        ASSERT(de_row_is(&s->early, DE_UNVOUCHED, "unvouched", false));
        ASSERT(s->early.skip.saved_us > 0);
        ASSERT(de_skip_json(&s->early, 1, 1));
        ASSERT(de_log_is(&s->fx, "early " DE_UNVOUCHED,
                         s->with.test_processes));
        ASSERT(de_same_proof(&s->base, &s->with));
        ASSERT(de_receipt_is_feedback(&s->early, "green", ""));
        PASS();
    } _test_next:;
    return failures;
}

static int de_test_skip_edit(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: editing a header in the closure reruns the group; "
         "the next unchanged run skips it again") {
        ASSERT(de_skip_files(&s->fx, "#define EARLY_SKIP_DEP 2\n"));
        ASSERT(de_skip_base(s));
        s->early_plan.origin_us = platform_time_monotonic_us();
        ASSERT(de_prove(s, &s->early_plan));
        ASSERT_STR_EQ(s->early.status, "green");
        ASSERT_EQ(s->early.run_count, 2u);
        ASSERT(de_row_is(&s->early, DE_VOUCHED, "key-changed", false));
        ASSERT(de_skip_json(&s->early, 2, 0));
        ASSERT(de_same_proof(&s->base, &s->with));
        (void)unlink(s->fx.log);

        s->early_plan.origin_us = platform_time_monotonic_us();
        ASSERT(de_prove(s, &s->early_plan));
        ASSERT(de_row_is(&s->early, DE_VOUCHED, "closure-unchanged", true));
        ASSERT(de_same_proof(&s->base, &s->with));
        (void)unlink(s->fx.log);
        PASS();
    } _test_next:;
    return failures;
}

static int de_test_skip_off(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: ZCL_DEVLOOP_EARLY_SKIP=off runs every group and "
         "counts what it would have skipped") {
        ASSERT(platform_environment_set(DE_SKIP_ENV, "off", 1) == 0);
        s->early_plan.origin_us = platform_time_monotonic_us();
        bool proved = de_prove(s, &s->early_plan);
        ASSERT(platform_environment_set(DE_SKIP_ENV, "on", 1) == 0);
        ASSERT(proved);
        ASSERT_STR_EQ(s->early.status, "green");
        ASSERT_EQ(s->early.run_count, 2u);
        ASSERT_EQ(s->early.skip.groups_skipped, 0u);
        ASSERT_EQ(s->early.skip.groups_skip_disabled, 1u);
        ASSERT(de_row_is(&s->early, DE_VOUCHED, "skip-off", false));
        ASSERT(de_same_proof(&s->base, &s->with));
        (void)unlink(s->fx.log);
        PASS();
    } _test_next:;
    return failures;
}

static int de_test_skip_verify(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: verify mode reruns a skipped group and counts the "
         "failure its unchanged key hid as a false narrow") {
        const char *only[] = { "devloop_early" };
        ASSERT(de_skip_plan(&s->proof_plan, only, 1, &s->early_plan));
        ASSERT(platform_environment_set(DE_SKIP_ENV, "verify", 1) == 0);
        ASSERT(platform_environment_set(DE_FAIL_ENV, "1", 1) == 0);
        bool proved = de_prove(s, &s->early_plan);
        ASSERT(platform_environment_set(DE_FAIL_ENV, "0", 1) == 0);
        ASSERT(platform_environment_set(DE_SKIP_ENV, "on", 1) == 0);
        ASSERT(proved);
        ASSERT_STR_EQ(s->early.status, "skipped");
        ASSERT_STR_EQ(s->early.reason, "closure_unchanged");
        ASSERT_EQ(s->early.run_count, 0u);
        ASSERT(de_row_is(&s->early, DE_VOUCHED, "closure-unchanged", true));
        ASSERT(s->early.skip.verify_ran);
        ASSERT_STR_EQ(s->early.skip.verify_status, "red");
        ASSERT_EQ(s->early.skip.verify_groups, 1u);
        ASSERT_EQ(s->early.skip.false_narrows, 1u);
        ASSERT_EQ(s->early.skip.records_forgotten, 1u);
        ASSERT(de_log_is(&s->fx, "early " DE_VOUCHED, s->with.test_processes));
        ASSERT(de_same_proof(&s->base, &s->with));
        ASSERT(de_receipt_is_feedback(&s->early, "skipped",
                                      "closure_unchanged"));

        /* The hidden failure dropped the record: the group runs again. */
        s->early_plan.origin_us = platform_time_monotonic_us();
        ASSERT(de_prove(s, &s->early_plan));
        ASSERT(de_row_is(&s->early, DE_VOUCHED, "no-record", false));
        ASSERT_EQ(s->early.run_count, 1u);
        ASSERT(de_same_proof(&s->base, &s->with));
        (void)unlink(s->fx.log);
        PASS();
    } _test_next:;
    (void)unsetenv(DE_SKIP_ENV);
    return failures;
}

/* ── inputs a key could miss: decided directly over the fixture ──────── */

#define DE_HOLE_A "tools/dev/early_hole_a.c"
#define DE_HOLE_B "tools/dev/early_hole_b.c"
#define DE_HOLE_FLAGS "-DZCL_TESTING -O0 -Itests/harness/include"

/* One row, the vouched group, over restart sources A and B, both linked
 * into the candidate its test binary runs. */
static void de_hole_decide(struct de_state *s, const char *cflags)
{
    static const char *const sources[] = { DE_HOLE_A, DE_HOLE_B };
    const struct zcl_devloop_early_toolchain tc = {
        .compiler_id = "fixture-cc", .base_generation = "fixture-base",
        .cflags = cflags, .ldflags = "-pthread", .libs = "-lm",
        .sources = sources, .source_count = 2,
    };
    memset(&s->hole, 0, sizeof(s->hole));
    s->hole.n = 1;
    (void)snprintf(s->hole.rows[0].group, sizeof(s->hole.rows[0].group),
                   "%s", DE_VOUCHED);
    zcl_devloop_early_skip_decide(s->fx.root, &tc, &s->hole);
}

/* The row's reason is `reason` and its detail holds `detail`. */
static bool de_hole_is(const struct de_state *s, const char *reason,
                       const char *detail)
{
    const struct zcl_devloop_early_skip_row *row = &s->hole.rows[0];
    bool ok = row->reason && strcmp(row->reason, reason) == 0 &&
              strstr(row->detail, detail) != NULL &&
              row->skip == (strcmp(reason, "closure-unchanged") == 0) &&
              row->vouched == (strcmp(reason, "unvouched") != 0);
    if (!ok)
        printf("[hole: %s %s] ", row->reason ? row->reason : "(none)",
               row->detail);
    return ok;
}

static bool de_hole_setup(struct de_state *s)
{
    char store[PATH_MAX];
    (void)snprintf(store, sizeof(store),
                   "%s/build/dev-loop/early-skip.v1.tsv", s->fx.root);
    (void)unlink(store);
    return platform_environment_set(DE_SKIP_ENV, "on", 1) == 0 &&
           de_skip_files(&s->fx, "#define EARLY_SKIP_DEP 1\n") &&
           de_write(s->fx.root, DE_HOLE_A,
                    "int early_hole_a(void) { return 1; }\n") &&
           de_write(s->fx.root, DE_HOLE_B,
                    "int early_hole_b(void) { return 1; }\n");
}

static int de_test_skip_linked(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: a linked restart source keys every group, so "
         "editing one the facts never attributed to the group reruns it") {
        ASSERT(de_hole_setup(s));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "no-record", ""));
        ASSERT(zcl_devloop_early_skip_record(s->fx.root, &s->hole, "", 1000));
        ASSERT_EQ(s->hole.records_written, 1u);
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "closure-unchanged", ""));
        /* B's own facts name no group: only the link list attributes it. */
        ASSERT(de_write(s->fx.root, DE_HOLE_B,
                        "int early_hole_b(void) { return 2; }\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "key-changed", ""));
        PASS();
    } _test_next:;
    return failures;
}

static int de_test_skip_helper(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: a helper in the closure that reads the environment "
         "or opens a computed path leaves the group unvouched") {
        ASSERT(de_hole_setup(s));
        ASSERT(de_skip_files(&s->fx,
            "#include <stdlib.h>\n"
            "static inline const char *early_dep_env(void)\n"
            "{ return getenv(\"EARLY_SKIP_DEP_ENV\"); }\n"
            "#define EARLY_SKIP_DEP 1\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "unvouched", "reads-environment"));
        ASSERT(de_skip_files(&s->fx,
            "#include <stdio.h>\n"
            "static inline FILE *early_dep_open(const char *path)\n"
            "{ return fopen(path, \"rb\"); }\n"
            "#define EARLY_SKIP_DEP 1\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "unvouched", "opens-file"));
        /* A comment calls nothing; a comment opener inside a literal, or
         * after a C23 digit separator, hides no call that follows it. */
        ASSERT(de_skip_files(&s->fx,
            "/* getenv(\"X\"), system(\"rm\") and fopen(path) */\n"
            "// execv(path, argv)\n"
            "#define EARLY_SKIP_DEP 1\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "no-record", ""));
        ASSERT(de_skip_files(&s->fx,
            "static const char *early_dep_s = \"/*\";\n"
            "static const char *early_dep_e(void) { return getenv(\"X\"); }\n"
            "/* */\n"
            "#define EARLY_SKIP_DEP 1\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "unvouched", "reads-environment"));
        ASSERT(de_skip_files(&s->fx,
            "static int early_dep_n = 1'000; static const char *early_dep_s ="
            " \"a'b // c\"; static const char *early_dep_e(void)"
            " { return getenv(\"X\"); }\n"
            "#define EARLY_SKIP_DEP 1\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "unvouched", "reads-environment"));
        /* An include's operand is keyed through the file it resolves to;
         * the same path as data is an input no key names. */
        ASSERT(de_write(s->fx.root, "tests/harness/src/early_skip_more.h",
                        "#define EARLY_SKIP_MORE 1\n"));
        ASSERT(de_skip_files(&s->fx,
            "#include \"tests/harness/src/early_skip_more.h\"\n"
            "#define EARLY_SKIP_DEP 1\n"));
        de_hole_decide(s, DE_HOLE_FLAGS " -I.");
        ASSERT(de_hole_is(s, "no-record", ""));
        ASSERT(de_skip_files(&s->fx,
            "static const char *early_dep_p =\n"
            "    \"tests/harness/src/early_skip_more.h\";\n"
            "#define EARLY_SKIP_DEP 1\n"));
        de_hole_decide(s, DE_HOLE_FLAGS " -I.");
        ASSERT(de_hole_is(s, "unvouched", "names-checkout-path"));
        ASSERT(de_write(s->fx.root, DE_HOLE_B,
                        "int open(const char *path, int flags, ...);\n"
                        "int early_hole_b(const char *p)\n"
                        "{ return open(p, 0); }\n"));
        ASSERT(de_skip_files(&s->fx, "#define EARLY_SKIP_DEP 1\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "unvouched", "opens-file"));
        /* A prototype names no input; a literal scratch path is keyed. */
        ASSERT(de_write(s->fx.root, DE_HOLE_B,
                        "#include <stdio.h>\n"
                        "int open(const char *path, int flags, ...);\n"
                        "FILE *early_hole_b(void)\n"
                        "{ return fopen(\"test-tmp/early_hole\",\n"
                        "               \"rb\"); }\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "no-record", ""));
        PASS();
    } _test_next:;
    return failures;
}

static int de_test_skip_suffix(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: nested includes in a header with an uncommon "
         "suffix remain in the early key") {
        ASSERT(de_hole_setup(s));
        ASSERT(de_write(s->fx.root,
                        "tests/harness/src/early_skip_outer.data",
                        "#include \"early_skip_inner.h\"\n"
                        "#define EARLY_SKIP_OUTER EARLY_SKIP_INNER\n"));
        ASSERT(de_write(s->fx.root,
                        "tests/harness/src/early_skip_inner.h",
                        "#define EARLY_SKIP_INNER 1\n"));
        ASSERT(de_write(s->fx.root, "tests/harness/src/" DE_VOUCHED ".c",
                        "#include \"early_skip_dep.h\"\n"
                        "#include \"early_skip_outer.data\"\n"
                        "int early_skip_fixture_group = "
                        "EARLY_SKIP_DEP + EARLY_SKIP_OUTER;\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "no-record", ""));
        ASSERT(zcl_devloop_early_skip_record(s->fx.root, &s->hole, "", 1000));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "closure-unchanged", ""));
        ASSERT(de_write(s->fx.root,
                        "tests/harness/src/early_skip_inner.h",
                        "#define EARLY_SKIP_INNER 2\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "key-changed", ""));
        PASS();
    } _test_next:;
    return failures;
}

static int de_test_skip_spliced_directive(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: line-spliced include directives keep their "
         "nested headers in the early key") {
        ASSERT(de_hole_setup(s));
        ASSERT(de_write(s->fx.root,
                        "tests/harness/src/early_skip_outer.h",
                        "#\\\ninclude \"early_skip_inner.h\"\n"
                        "#define EARLY_SKIP_OUTER EARLY_SKIP_INNER\n"));
        ASSERT(de_write(s->fx.root,
                        "tests/harness/src/early_skip_inner.h",
                        "#define EARLY_SKIP_INNER 1\n"));
        ASSERT(de_write(s->fx.root, "tests/harness/src/" DE_VOUCHED ".c",
                        "#include \"early_skip_dep.h\"\n"
                        "#include \"early_skip_outer.h\"\n"
                        "int early_skip_fixture_group = "
                        "EARLY_SKIP_DEP + EARLY_SKIP_OUTER;\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "no-record", ""));
        ASSERT(zcl_devloop_early_skip_record(s->fx.root, &s->hole, "", 1000));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "closure-unchanged", ""));
        ASSERT(de_write(s->fx.root,
                        "tests/harness/src/early_skip_inner.h",
                        "#define EARLY_SKIP_INNER 2\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "key-changed", ""));
        PASS();
    } _test_next:;
    return failures;
}

static int de_test_skip_has_include(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: an include-presence probe cannot reuse PASS "
         "after a file appears") {
        ASSERT(de_hole_setup(s));
        ASSERT(de_write(s->fx.root,
                        "tests/harness/src/early_skip_probe.h",
                        "#if __has_include(\"early_skip_optional.h\")\n"
                        "#define EARLY_SKIP_OUTER 2\n"
                        "#else\n#define EARLY_SKIP_OUTER 1\n#endif\n"));
        ASSERT(de_write(s->fx.root, "tests/harness/src/" DE_VOUCHED ".c",
                        "#include \"early_skip_dep.h\"\n"
                        "#include \"early_skip_probe.h\"\n"
                        "int early_skip_fixture_group = "
                        "EARLY_SKIP_DEP + EARLY_SKIP_OUTER;\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        bool vouched = s->hole.rows[0].vouched;
        if (vouched) {
            ASSERT(de_hole_is(s, "no-record", ""));
            ASSERT(zcl_devloop_early_skip_record(s->fx.root, &s->hole,
                                                  "", 1000));
        } else {
            ASSERT(de_hole_is(s, "unvouched", "has-include"));
        }
        ASSERT(de_write(s->fx.root,
                        "tests/harness/src/early_skip_optional.h",
                        "#define EARLY_SKIP_OPTIONAL 1\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, vouched ? "key-changed" : "unvouched",
                          vouched ? "" : "has-include"));
        PASS();
    } _test_next:;
    return failures;
}

static int de_test_skip_has_embed(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: an embed-presence probe cannot reuse PASS "
         "after a file appears") {
        ASSERT(de_hole_setup(s));
        ASSERT(de_write(s->fx.root,
                        "tests/harness/src/early_skip_embed_probe.h",
                        "#if __has_embed(\"early_skip_optional.bin\")\n"
                        "#define EARLY_SKIP_OUTER 2\n"
                        "#else\n#define EARLY_SKIP_OUTER 1\n#endif\n"));
        ASSERT(de_write(s->fx.root, "tests/harness/src/" DE_VOUCHED ".c",
                        "#include \"early_skip_dep.h\"\n"
                        "#include \"early_skip_embed_probe.h\"\n"
                        "int early_skip_fixture_group = "
                        "EARLY_SKIP_DEP + EARLY_SKIP_OUTER;\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        bool vouched = s->hole.rows[0].vouched;
        if (vouched) {
            ASSERT(de_hole_is(s, "no-record", ""));
            ASSERT(zcl_devloop_early_skip_record(s->fx.root, &s->hole,
                                                  "", 1000));
        } else {
            ASSERT(de_hole_is(s, "unvouched", "has-embed"));
        }
        ASSERT(de_write(s->fx.root,
                        "tests/harness/src/early_skip_optional.bin", "1"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, vouched ? "key-changed" : "unvouched",
                          vouched ? "" : "has-embed"));
        PASS();
    } _test_next:;
    return failures;
}

static int de_test_skip_probe_flag_alias(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: a command-line alias for an embed probe cannot "
         "reuse PASS after a file appears") {
        const char *flags = DE_HOLE_FLAGS " -DHE=__has_embed";
        ASSERT(de_hole_setup(s));
        ASSERT(de_write(s->fx.root,
                        "tests/harness/src/early_skip_flag_probe.h",
                        "#if HE(\"early_skip_flag_optional.bin\")\n"
                        "#define EARLY_SKIP_OUTER 2\n"
                        "#else\n#define EARLY_SKIP_OUTER 1\n#endif\n"));
        ASSERT(de_write(s->fx.root, "tests/harness/src/" DE_VOUCHED ".c",
                        "#include \"early_skip_dep.h\"\n"
                        "#include \"early_skip_flag_probe.h\"\n"
                        "int early_skip_fixture_group = "
                        "EARLY_SKIP_DEP + EARLY_SKIP_OUTER;\n"));
        de_hole_decide(s, flags);
        bool vouched = s->hole.rows[0].vouched;
        if (vouched) {
            ASSERT(de_hole_is(s, "no-record", ""));
            ASSERT(zcl_devloop_early_skip_record(s->fx.root, &s->hole,
                                                  "", 1000));
        } else {
            ASSERT(de_hole_is(s, "unvouched", "cflags-unmodeled"));
        }
        ASSERT(de_write(s->fx.root,
                        "tests/harness/src/early_skip_flag_optional.bin",
                        "1"));
        de_hole_decide(s, flags);
        ASSERT(de_hole_is(s, vouched ? "key-changed" : "unvouched",
                          vouched ? "" : "cflags-unmodeled"));
        PASS();
    } _test_next:;
    return failures;
}

static int de_test_skip_ambient_include(struct de_state *s)
{
    int failures = 0;
    const char *old = getenv("CPATH");
    char *saved = old ? strdup(old) : NULL;
    char external[PATH_MAX] = "";
    char header[PATH_MAX] = "";
    bool changed_env = false;
    TEST("devloop_early: an external CPATH header cannot reuse PASS after "
         "its bytes change") {
        ASSERT(!old || saved);
        ASSERT(de_hole_setup(s));
        ASSERT(snprintf(external, sizeof(external), "%s-ambient", s->fx.root)
               < (int)sizeof(external));
        ASSERT(snprintf(header, sizeof(header), "%s/early_env_choice.h",
                        external) < (int)sizeof(header));
        ASSERT(de_write(external, "early_env_choice.h",
                        "#define EARLY_ENV_CHOICE 11\n"));
        ASSERT(de_write(s->fx.root, DE_HOLE_A,
                        "#include <early_env_choice.h>\n"
                        "int early_hole_a(void) { return EARLY_ENV_CHOICE; }\n"));
        ASSERT(setenv("CPATH", external, 1) == 0);
        changed_env = true;
        de_hole_decide(s, DE_HOLE_FLAGS);
        bool vouched = s->hole.rows[0].vouched;
        if (vouched) {
            ASSERT(de_hole_is(s, "no-record", ""));
            ASSERT(zcl_devloop_early_skip_record(s->fx.root, &s->hole,
                                                  "", 1000));
        } else {
            ASSERT(de_hole_is(s, "unvouched", "ambient-include-path"));
        }
        ASSERT(de_write(external, "early_env_choice.h",
                        "#define EARLY_ENV_CHOICE 22\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, vouched ? "key-changed" : "unvouched",
                          vouched ? "" : "ambient-include-path"));
        PASS();
    } _test_next:;
    if (changed_env) {
        if (saved)
            (void)setenv("CPATH", saved, 1);
        else
            (void)unsetenv("CPATH");
    }
    free(saved);
    if (header[0])
        (void)unlink(header);
    if (external[0])
        (void)rmdir(external);
    return failures;
}

static int de_test_skip_volatile_macros(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: build-time macros cannot reuse an earlier PASS") {
        static const struct {
            const char *body;
            const char *reason;
        } cases[] = {
            {"int early_hole_a(void) { return __DATE__[0]; }\n",
             "volatile-macro"},
            {"int early_hole_a(void) { return __TIME__[0]; }\n",
             "volatile-macro"},
            {"int early_hole_a(void) { return __TIMESTAMP__[0]; }\n",
             "volatile-macro"},
            {"#define CAT(a, b) a ## b\n"
             "int early_hole_a(void) { return CAT(__DA, TE__)[0]; }\n",
             "macro-paste"},
        };
        for (size_t i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
            ASSERT(de_hole_setup(s));
            ASSERT(de_write(s->fx.root, DE_HOLE_A, cases[i].body));
            de_hole_decide(s, DE_HOLE_FLAGS);
            ASSERT(de_hole_is(s, "unvouched", cases[i].reason));
        }
        PASS();
    } _test_next:;
    return failures;
}

static int de_test_skip_flags(struct de_state *s)
{
    int failures = 0;
    TEST("devloop_early: include flags the resolver does not model and "
         "#include_next leave the group unvouched") {
        static const char *const unmodeled[] = {
            "-isystem vendor", "-idirafter vendor",
            "-include tests/harness/src/early_skip_dep.h",
            "-imacros tests/harness/src/early_skip_dep.h",
            "--sysroot=/opt/root", "--sysroot /opt/root",
            "-isysroot /opt/root", "-iwithprefix vendor", "-I-",
            "@build/flags.rsp",
        };
        char flags[8192];
        ASSERT(de_hole_setup(s));
        de_hole_decide(s, DE_HOLE_FLAGS " -iquote tests -Iplatform");
        ASSERT(de_hole_is(s, "no-record", ""));
        for (size_t i = 0; i < sizeof(unmodeled) / sizeof(unmodeled[0]);
             i++) {
            (void)snprintf(flags, sizeof(flags), "%s %s", DE_HOLE_FLAGS,
                           unmodeled[i]);
            de_hole_decide(s, flags);
            ASSERT(de_hole_is(s, "unvouched", "cflags-unmodeled"));
            ASSERT_EQ(s->hole.groups_unvouched, 1u);
        }
        ASSERT(de_skip_files(&s->fx,
            "#include_next \"early_skip_dep.h\"\n"
            "#define EARLY_SKIP_DEP 1\n"));
        de_hole_decide(s, DE_HOLE_FLAGS);
        ASSERT(de_hole_is(s, "unvouched", "include-next"));
        /* A later include directory may supply a header no earlier directory
         * has. The resolver must refuse when its directory bound is reached,
         * rather than silently ignore the next -I. */
        ASSERT(de_skip_files(&s->fx, "#define EARLY_SKIP_DEP 1\n"));
        size_t used = (size_t)snprintf(flags, sizeof(flags), "%s",
                                       DE_HOLE_FLAGS);
        ASSERT(used < sizeof(flags));
        for (size_t i = 0; i < 1023; i++) {
            int n = snprintf(flags + used, sizeof(flags) - used, " -I.");
            ASSERT(n > 0 && (size_t)n < sizeof(flags) - used);
            used += (size_t)n;
        }
        de_hole_decide(s, flags);
        ASSERT(de_hole_is(s, "no-record", ""));
        ASSERT(de_write(s->fx.root, "late/early_skip_late.h",
                        "#define EARLY_SKIP_LATE 1\n"));
        ASSERT(de_write(s->fx.root, "tests/harness/src/" DE_VOUCHED ".c",
                        "#include \"early_skip_dep.h\"\n"
                        "#include <early_skip_late.h>\n"
                        "int early_skip_fixture_group = "
                        "EARLY_SKIP_DEP + EARLY_SKIP_LATE;\n"));
        ASSERT((size_t)snprintf(flags + used, sizeof(flags) - used, " -Ilate") <
               sizeof(flags) - used);
        de_hole_decide(s, flags);
        ASSERT(de_hole_is(s, "unvouched", "cflags-unmodeled"));
        PASS();
    } _test_next:;
    (void)unsetenv(DE_SKIP_ENV);
    return failures;
}

#endif /* __linux__ */

static int de_test_restart(void)
{
    int failures = 0;
#if defined(__linux__)
    struct de_state *s = zcl_calloc(1, sizeof(*s), "de.state");
    bool ready = false;
    TEST("devloop_early: fixture candidate compiles and links with cc") {
        ASSERT(s != NULL);
        ASSERT(de_proof_plan(&s->proof_plan));
        ASSERT(de_fixture_open(&s->fx));
        ready = true;
        PASS();
    } _test_next:;
    if (ready) {
        failures += de_test_order(s);
        failures += de_test_red(s);
        failures += de_test_missing(s);
        failures += de_test_skip_unchanged(s);
        failures += de_test_skip_edit(s);
        failures += de_test_skip_off(s);
        failures += de_test_skip_verify(s);
        failures += de_test_skip_linked(s);
        failures += de_test_skip_helper(s);
        failures += de_test_skip_suffix(s);
        failures += de_test_skip_spliced_directive(s);
        failures += de_test_skip_has_include(s);
        failures += de_test_skip_has_embed(s);
        failures += de_test_skip_probe_flag_alias(s);
        failures += de_test_skip_ambient_include(s);
        failures += de_test_skip_volatile_macros(s);
        failures += de_test_skip_flags(s);
    }
    if (s)
        de_fixture_close(&s->fx);
    free(s);
#else
    printf("devloop_early: SKIP (the restart fixture links with GNU ld "
           "--allow-multiple-definition)\n");
#endif
    return failures;
}

int test_devloop_early(void)
{
    int failures = 0;
    failures += de_test_skips();
    failures += de_test_restart();
    return failures;
}
