/* Generated by tools/project-original-context.sh; do not hand-edit.
 * Zclassic 14a83d510ffd109d3fa09bf74ebf8c28854a263f consensus parameter data.
 * Copyright (c) 2018 The Zcash developers; MIT license, see
 * ../../docs/transaction-reference.LICENSE. No wallet implementation imported.
 */
#ifndef ZCL_CHAIN_CONTEXT_REFERENCE_H
#define ZCL_CHAIN_CONTEXT_REFERENCE_H
#include <stdint.h>
static const struct { int32_t activation[2]; uint32_t branch; } reference_epochs[] = {
    {{0, 0}, UINT32_C(0)}, /* BASE_SPROUT */
    {{-1, -1}, UINT32_C(0x74736554)}, /* UPGRADE_TESTDUMMY */
    {{476969, 20}, UINT32_C(0x5ba81b19)}, /* UPGRADE_OVERWINTER */
    {{476969, 20}, UINT32_C(0x76b809bb)}, /* UPGRADE_SAPLING */
    {{585318, 6350}, UINT32_C(0x821a451c)}, /* UPGRADE_BUBBLES */
    {{585322, -1}, UINT32_C(0x930b540d)}, /* UPGRADE_DIFFADJ */
    {{707000, 78856}, UINT32_C(0x930b540d)}, /* UPGRADE_BUTTERCUP */
};
enum { ZCL_REFERENCE_SAPLING_EPOCH = 3 };
#endif
