# Copyright 2026 Rhett Creighton. Licensed under Apache-2.0.
# Validate actual emitted commands, including providers and fuzz harnesses.
file(READ "${COMMANDS_FILE}" commands)
string(JSON count LENGTH "${commands}")
if(count EQUAL 0)
    message(FATAL_ERROR "No authored/provider compile commands were checked")
endif()
math(EXPR last "${count} - 1")
set(observed 0)
set(covered 0)
set(harnesses 0)
foreach(index RANGE 0 ${last})
    string(JSON entry GET "${commands}" ${index})
    string(JSON source GET "${entry}" file)
    if(source MATCHES "/native/(src|tests)/|/vendor/android-[^/]+/|/contexts/commons/packages/")
        string(JSON command GET "${entry}" command)
        # An earlier enabling flag cannot qualify a command with an opt-out.
        # Inspect actual arguments so quoted flags cannot evade this check,
        # and a macro value containing similar text is not mistaken for a flag.
        separate_arguments(arguments UNIX_COMMAND "${command}")
        set(has_coverage FALSE)
        set(flag_arguments)
        set(object_output "")
        set(output_count 0)
        set(expect_output FALSE)
        foreach(argument IN LISTS arguments)
            if(expect_output)
                set(object_output "${argument}")
                math(EXPR output_count "${output_count} + 1")
                set(expect_output FALSE)
                continue()
            elseif(argument STREQUAL "-o")
                set(expect_output TRUE)
                continue()
            endif()
            list(APPEND flag_arguments "${argument}")
        endforeach()
        if(expect_output OR NOT output_count EQUAL 1 OR object_output STREQUAL "")
            message(FATAL_ERROR "Exactly one compiler output is required for ${source}")
        endif()
        if(source MATCHES "/native/tests/")
            # Shared test/seed filenames do not identify a fuzz compilation.
            # Qualify every harness/helper compiled into an actual fuzz target.
            if(NOT object_output MATCHES "^CMakeFiles/fuzz_[^/]+\\.dir/")
                continue()
            endif()
            math(EXPR harnesses "${harnesses} + 1")
        else()
            math(EXPR observed "${observed} + 1")
        endif()
        foreach(argument IN LISTS flag_arguments)
            if(argument MATCHES "^-f(no-sanitize=|sanitize-recover=|no-sanitize-coverage=)")
                message(FATAL_ERROR "Sanitizer or coverage opt-out is forbidden for ${source}: ${argument}")
            endif()
            if(argument MATCHES "^-fsanitize=fuzzer(-no-link)?(,|$)")
                set(has_coverage TRUE)
            endif()
        endforeach()
        list(FIND flag_arguments "-fsanitize=address,undefined" sanitizer_position)
        list(FIND flag_arguments "-fno-sanitize-recover=all" failure_position)
        list(FIND flag_arguments
            "-fsanitize=unsigned-integer-overflow,implicit-integer-truncation,implicit-integer-sign-change"
            integer_position)
        if(sanitizer_position LESS 0 OR failure_position LESS 0)
            message(FATAL_ERROR "Required sanitizer or fail-on-finding flags missing for ${source}")
        endif()
        if(source MATCHES "/native/src/" AND integer_position LESS 0)
            message(FATAL_ERROR "Required authored integer checks missing for ${source}")
        endif()
        # Registered standalone unit tests compile some provider/source copies
        # for fault substitution. Those copies need sanitizers; coverage is
        # required on the libraries and source copies linked into fuzz targets.
        # Only the actual -o operand can establish that exemption. A macro,
        # include path or other argument containing a test path cannot do so.
        if(object_output MATCHES "^CMakeFiles/fuzz_[^/]+\\.dir/" OR
            NOT object_output MATCHES "^CMakeFiles/[^/]+_tests\\.dir/")
            if(NOT has_coverage)
                message(FATAL_ERROR "Required fuzz coverage instrumentation missing for ${source}")
            endif()
            math(EXPR covered "${covered} + 1")
        endif()
    endif()
endforeach()
if(observed EQUAL 0 OR covered EQUAL 0)
    message(FATAL_ERROR "No authored/provider compile commands were checked")
endif()
if(harnesses EQUAL 0)
    message(FATAL_ERROR "No fuzz harness compile commands were checked")
endif()
message(STATUS "Verified sanitizers/fail-on-finding on ${observed} authored/provider and ${harnesses} fuzz-harness compilations; fuzz coverage on ${covered} library/fuzz compilations")
