# Copyright 2026 Rhett Creighton. Licensed under Apache-2.0.
if(NOT DEFINED TEST_DIR OR NOT DEFINED CTEST_COMMAND)
    message(FATAL_ERROR "Test deadline check requires TEST_DIR and CTEST_COMMAND")
endif()
execute_process(COMMAND "${CTEST_COMMAND}" --test-dir "${TEST_DIR}" --show-only=json-v1
    RESULT_VARIABLE _result OUTPUT_VARIABLE _tests ERROR_VARIABLE _error TIMEOUT 10)
if(NOT _result STREQUAL "0")
    message(FATAL_ERROR "Cannot inspect registered test deadlines: ${_result}: ${_error}")
endif()
string(JSON _count LENGTH "${_tests}" tests)
if(_count LESS 1)
    message(FATAL_ERROR "Test deadline check found no registered tests")
endif()
math(EXPR _last "${_count} - 1")
foreach(_index RANGE 0 ${_last})
    string(JSON _name GET "${_tests}" tests ${_index} name)
    string(JSON _properties LENGTH "${_tests}" tests ${_index} properties)
    set(_bounded FALSE)
    if(_properties GREATER 0)
        math(EXPR _property_last "${_properties} - 1")
        foreach(_property RANGE 0 ${_property_last})
            string(JSON _key GET "${_tests}" tests ${_index} properties ${_property} name)
            if(_key STREQUAL "TIMEOUT")
                string(JSON _seconds GET "${_tests}" tests ${_index} properties ${_property} value)
                if(NOT _seconds MATCHES "^[0-9]+(\\.[0-9]+)?$" OR NOT _seconds GREATER 0)
                    message(FATAL_ERROR "${_name} has an invalid execution deadline: ${_seconds}")
                endif()
                set(_bounded TRUE)
            endif()
        endforeach()
    endif()
    if(NOT _bounded)
        message(FATAL_ERROR "${_name} has no explicit execution deadline")
    endif()
endforeach()
message(STATUS "Verified positive execution deadlines for ${_count} registered tests")
