/* Copyright 2026 Rhett Creighton. Licensed under Apache-2.0. */
#undef zcl_secure_zero
#undef zcl_random_bytes
#include "jni_support.h"
#include "zcl_keys.h"
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CHECK(v) do { if (!(v)) { fprintf(stderr, "JNI entropy check failed at %d\n", __LINE__); abort(); } } while (0)
JNIEXPORT jint JNICALL Java_org_zclassic_wallet_core_NativeCore_createEntropy(
    JNIEnv *, jclass, jbyteArray);

typedef struct { jsize length; uint8_t bytes[34]; } fake_array;
static fake_array output;
static bool pending, fail_length, fail_random, fail_transfer;
static unsigned reads, random_calls, writes, wipes;
static size_t requested, prefix;
/* Never dereference a retired scratch pointer. Observe retirement only through
 * the live zeroizer argument; all generated bytes here are public fixtures. */
static uintptr_t scratch;

void zcl_entropy_test_zero(void *pointer, size_t length)
{
    CHECK(pointer != NULL && (uintptr_t)pointer == scratch && length == 32);
    zcl_secure_zero(pointer, length);
    const uint8_t *bytes = pointer;
    for (size_t i = 0; i < length; ++i) CHECK(bytes[i] == 0);
    scratch = 0;
    ++wipes;
}

zcl_status zcl_entropy_test_random(uint8_t *bytes, size_t length)
{
    CHECK(!pending && bytes != NULL);
    CHECK(length == 16 || length == 32);
    ++random_calls;
    requested = length;
    scratch = (uintptr_t)bytes;
    bytes[0] = 0x42; /* A failing provider may already have written a prefix. */
    if (fail_random) return ZCL_IO_FAILURE;
    memset(bytes, 0x42, length);
    return ZCL_OK;
}

static jboolean JNICALL exception_check(JNIEnv *env)
{
    (void)env;
    return pending ? JNI_TRUE : JNI_FALSE;
}

static jsize JNICALL array_length(JNIEnv *env, jarray array)
{
    (void)env;
    CHECK(!pending && array == (jarray)&output);
    ++reads;
    if (fail_length) { pending = true; return 16; }
    return output.length;
}

static void JNICALL set_bytes(JNIEnv *env, jbyteArray array, jsize start,
    jsize length, const jbyte *bytes)
{
    (void)env;
    CHECK(!pending && array == (jbyteArray)&output && start == 0);
    CHECK(length == output.length && length > 0 && length <= 32);
    CHECK((uintptr_t)bytes == scratch);
    ++writes;
    size_t copied = (size_t)length;
    if (fail_transfer) { CHECK(prefix <= copied); copied = prefix; pending = true; }
    memcpy(output.bytes + 1, bytes, copied);
}

static const struct JNINativeInterface_ functions = {
    .ExceptionCheck = exception_check, .GetArrayLength = array_length,
    .SetByteArrayRegion = set_bytes
};
static JNIEnv environment = &functions;

static void reset(jsize length)
{
    output.length = length;
    memset(output.bytes, 0xa5, sizeof(output.bytes));
    pending = false; fail_length = false; fail_random = false; fail_transfer = false;
    reads = 0; random_calls = 0; writes = 0; wipes = 0;
    requested = 0; prefix = 0; scratch = 0;
}

static jint invoke(void)
{
    return Java_org_zclassic_wallet_core_NativeCore_createEntropy(
        &environment, NULL, (jbyteArray)&output);
}

static void verify_bytes(size_t transferred)
{
    CHECK(output.bytes[0] == 0xa5);
    for (size_t i = 1; i < sizeof(output.bytes); ++i)
        CHECK(output.bytes[i] == (i <= transferred ? 0x42 : 0xa5));
}

static void verify_random_call(size_t length)
{
    CHECK(reads == 1 && random_calls == 1 && requested == length);
    CHECK(wipes == 1 && scratch == 0);
}

static void positive(jsize length)
{
    reset(length);
    CHECK(invoke() == length);
    CHECK(!pending && writes == 1);
    verify_random_call((size_t)length);
    verify_bytes((size_t)length);
}

static void invalid_lengths(void)
{
    static const jsize lengths[] = {INT_MIN, -1, 0, 15, 17, 20, 24, 28, 31, 33, INT_MAX};
    for (size_t i = 0; i < sizeof(lengths) / sizeof(lengths[0]); ++i) {
        reset(lengths[i]);
        CHECK(invoke() == 0 && !pending && reads == 1);
        CHECK(random_calls == 0 && writes == 0 && wipes == 0);
        verify_bytes(0);
    }
}

static void rejected_entry(void)
{
    reset(16);
    CHECK(Java_org_zclassic_wallet_core_NativeCore_createEntropy(NULL, NULL,
        (jbyteArray)&output) == 0);
    CHECK(Java_org_zclassic_wallet_core_NativeCore_createEntropy(&environment, NULL, NULL) == 0);
    pending = true;
    CHECK(invoke() == 0 && reads == 0);
    CHECK(random_calls == 0 && writes == 0 && wipes == 0);
    verify_bytes(0);
}

static void length_failure(void)
{
    reset(16);
    fail_length = true;
    CHECK(invoke() == 0 && pending && reads == 1);
    CHECK(random_calls == 0 && writes == 0 && wipes == 0);
    verify_bytes(0);
}

static void provider_failure(jsize length)
{
    reset(length);
    fail_random = true;
    CHECK(invoke() == 0 && !pending && writes == 0);
    verify_random_call((size_t)length);
    verify_bytes(0);
}

static void transfer_failures(jsize length)
{
    for (size_t i = 0; i <= (size_t)length; ++i) {
        reset(length);
        fail_transfer = true; prefix = i;
        CHECK(invoke() == 0 && pending && writes == 1);
        verify_random_call((size_t)length);
        /* The managed owner clears these partial bytes in its finally block. */
        verify_bytes(i);
    }
}

int main(void)
{
    positive(16); positive(32);
    invalid_lengths(); rejected_entry(); length_failure();
    provider_failure(16); provider_failure(32);
    transfer_failures(16); transfer_failures(32);
    return 0;
}
