/* Copyright 2026 Rhett Creighton. Licensed under Apache-2.0. */
#ifndef ZCL_BLUE_REVIEW_LAYOUT_H
#define ZCL_BLUE_REVIEW_LAYOUT_H

#if !defined(__STDC_VERSION__) || __STDC_VERSION__ < 202311L
#error "The Blue review layout requires ISO C23"
#endif

enum {
    ZCL_BLUE_SCREEN_WIDTH = 320,
    ZCL_BLUE_SCREEN_HEIGHT = 480,
    ZCL_BLUE_HEADER_HEIGHT = 60,
    ZCL_BLUE_HEADER_TEXT_X = 20,
    ZCL_BLUE_HEADER_TEXT_WIDTH = 280,
    ZCL_BLUE_LINE_X = 10,
    ZCL_BLUE_LINE_FIRST_Y = 80,
    ZCL_BLUE_LINE_STEP_Y = 45,
    ZCL_BLUE_LINE_WIDTH = 300,
    ZCL_BLUE_LINE_HEIGHT = 40,
    ZCL_BLUE_BUTTON_Y = 390,
    ZCL_BLUE_TEXT_TOGGLE_Y = 350,
    ZCL_BLUE_TEXT_TOGGLE_HEIGHT = 35,
    ZCL_BLUE_LARGE_TITLE_Y = 80,
    ZCL_BLUE_LARGE_DETAIL_Y = 130,
    ZCL_BLUE_THEME_X = 225,
    ZCL_BLUE_THEME_Y = 12,
    ZCL_BLUE_THEME_WIDTH = 75,
    ZCL_BLUE_THEME_HEIGHT = 36,
    ZCL_BLUE_BUTTON_WIDTH = 130,
    ZCL_BLUE_BUTTON_HEIGHT = 40,
    ZCL_BLUE_NEXT_X = 20,
    ZCL_BLUE_EXIT_X = 170
};

#define ZCL_BLUE_COLOR_BODY 0xf9f9f9
#define ZCL_BLUE_COLOR_HEADER 0x1d2028
#define ZCL_BLUE_COLOR_TEXT 0x1d2028
#define ZCL_BLUE_COLOR_WHITE 0xffffff
#define ZCL_BLUE_COLOR_BUTTON 0x41ccb4
#define ZCL_BLUE_COLOR_DARK_BODY 0x13171e
#define ZCL_BLUE_COLOR_DARK_TEXT 0xf5f7f8
#define ZCL_BLUE_COLOR_DARK_BUTTON 0x49d9c1

#endif
