/* Copyright 2026 Rhett Creighton. Licensed under Apache-2.0. */
#ifndef ZCL_BLUE_WALLET_LAYOUT_H
#define ZCL_BLUE_WALLET_LAYOUT_H

enum {
    ZCL_WALLET_SCREEN_WIDTH = 320,
    ZCL_WALLET_SCREEN_HEIGHT = 480,
    ZCL_WALLET_TITLE_Y = 30,
    ZCL_WALLET_PATH_Y = 91,
    ZCL_WALLET_ADDRESS_1_Y = 160,
    ZCL_WALLET_ADDRESS_2_Y = 198,
    ZCL_WALLET_ADDRESS_3_Y = 236,
    ZCL_WALLET_INSTRUCTION_Y = 308,
    ZCL_WALLET_EXIT_Y = 393
};

enum {
    ZCL_WALLET_COLOR_BODY = 0x1d2028,
    ZCL_WALLET_COLOR_TEXT = 0xffffff,
    ZCL_WALLET_COLOR_ACCENT = 0x41ccb4
};

#endif
